### ISSUE TITLE
JSON nested arrays not mapping correctly

### ISSUE THREAD

**Issue by Andrew-Mace** [evermeer/EVReflection#1]
I just downloaded the most recent project and added these three lines to EVReflectionJsonTests.swift
        var test = userOriginal.company
        var test2 = userOriginal.friends
        var test3 = userOriginal.friends.first?.name

line 1 returns incorrect values for name/address (e.g. "\x88a\xc4\xba\xde\x7f")
line 2 returns an empty object (([EVReflectionTests.User]) test2 = {})
line 3 crashes the application

Nothing else was modified.

**Comment by evermeer** [comment]
Thanks for reporting this. I already noticed the problem with nested objects. I am working on a fix. I hope it will be ready tomorrow. The problem is that an array of dictionary instead of an array of friends was put in the friends property.

**Comment by Andrew-Mace** [comment]
Any progress? I'm still getting funny results for Company values. I tried doing some recursive reflection mapping using your setPropertiesfromDictionary but no luck yet.

Perhaps something like :
func enumerateJSONToFindKeys(object:AnyObject, forKeyNamed named:String?) {
    if let dict = object as? NSDictionary {
        for (key, value) in dict {
            enumerateJSONToFindKeys(value, forKeyNamed: key as? String)
        }
    }
    else if let array = object as? NSArray {
        for value in array {
            enumerateJSONToFindKeys(value, forKeyNamed: nil)
        }
    }
    else {
        EVReflection.setPropertiesfromDictionarySingle(...)
        println("found key (named) value (object)")
    }
}

**Comment by evermeer** [comment]
This issue appeared to be more difficult than expected. I did make some progress. The only problem that i now have that if you have an array of a specific object it will return an array of NSObjects. Because of that it won't have any fields populated. If I don't succeed today, then I will push this to GitHub since it's already improved somewhat.

**Comment by evermeer** [comment]
I created a separate branch for this issue called Child-objects-and-arrays. I keep on coming back to a generics issue that the creation of a new object results in a NSObject instead of the actual type.

**Comment by evermeer** [comment]
The branch Child-objects-and-arrays now functions good for sub objects and arrays of sub objects. 
There is one bug left and that is the crash the moment NSJSONSerialization.dataWithJSONObject is called. I will try to fix that one now.

**Comment by Andrew-Mace** [comment]
Awesome man, great library!

**Comment by evermeer** [comment]
I pushed a some final changes to the Child-objects-and-arrays branch. It still has a problem.
On line 60 the friends array is set and on line 61 it will be printed, but on line 66 the data is gone. 
I can't figure out why this is. I tried putting in different kind of arrays. (NSMutableArray, Array<Friends>, [Friends])

**Comment by evermeer** [comment]
SOLVED! phew... That was a hard one... Took me almost a week to fix... 
All tests are green. It's pushed to the Child-objects-and-arrays branch.
I will clean up some code and then pus and merge to master...

I have done some Extreme Swift Generics Reflection code Refactoring

**Comment by evermeer** [comment]
it's pushed to master as version 2.2.0.
