### ISSUE TITLE
EVReflection valueForAny fails with long number

### ISSUE THREAD

**Issue by kukudas** [evermeer/EVReflection#10]
At the bottom of this function there is the following switch statement:

...
switch(theValue){
  case let longValue as Int64:
    return (NSNumber(long: CLong(longValue)), "NSNumber")
  case let intValue as Int:
    return (NSNumber(Int: CInt(intValue)),"NSNumber")
...

If theValue is typed as NSNumber with a high value e.g 458347978508 then the second case is selected instead of the first one. This leads to a EXC_BAD_INSTRUCTION.

I think the problem is that the value fits into an Int within a 64 Bit enviorment but not into a CInt. However i'm not sure why the first case is skipped.

I think maybe it should be like this:

...
switch(theValue){
  case let longValue as Int64:
    return (NSNumber(long: CLongLong(longValue)), "NSNumber")
  case let intValue as Int:
    return (NSNumber(Int: CLong(intValue)),"NSNumber")
...

CLong is actually a typealias for Int and CLongLong is a typealias for Int64.

**Comment by evermeer** [comment]
Thanks for reporting this. I fixed this issue by adding more types to the check and putting them in the right order. I also added a unit test for this situation. This fix has now been pushed to the trunk and is available with the new cocoapod version 2.4.1
