### ISSUE TITLE
Is it possible to deserialize immutable classes?

### ISSUE THREAD

**Issue by sp-1234** [evermeer/EVReflection#100]
I mean, classes which have their properties declared with `let`

**Comment by evermeer** [comment]
When i declare a class like this:

```
class TestLet: EVObject {
    let p1 = "property 1"
    let p2 = "property 2"
}
```

You can then instantiate such a class and create json (or a dictionary) using code like this:

```
        let c = TestLet()
        let json = c.toJsonString()
        print("json = \(json)")
```

When you then try to create a new object based on that json with colde like this:

```
        let c2 = TestLet(json: json)
        print("object = \(c2)")
```

You will see the folowing warnings in your output window:

```
WARNING: The class 'TestLet' is not key value coding-compliant for the key 'p2'
WARNING: The class 'TestLet' is not key value coding-compliant for the key 'p1'
```

 You could then still do something with these values if you implemented the:

```
    internal override func setValue(value: AnyObject!, forUndefinedKey key: String) {
```

**Comment by evermeer** [comment]
If you have any more questions, then just ask...

**Comment by sp-1234** [comment]
> setValue

Immutable objects, by definition, cannot have anything like setValue, because they cannot change after initialization. So to deserialize them, the constructor have to be used. (Or some other magic, which I guess doesn't exist in Swift)
