### ISSUE TITLE
copy object

### ISSUE THREAD

**Issue by biskit** [evermeer/EVReflection#101]
how do i copy an object of type EVObject to of type Object.

ie:

```
class Test: EVObject {
    var field1: String?
    var field2: Bool?
}
```

to

```
class Test2: Object {
     var field1: String?
     var field2: Bool?
}
```

doing something like

```
func fcopy<T:EVObject, R:Object>(inobj: T, outobj: R) {
    for case let (label?, anyValue) in Mirror(reflecting:inobj).children {
        print("\(label) - \(anyValue)")
        let value = anyValue as? AnyObject
        outobj.setValue(value, forKey: label)
    }
}
```

the copy to bool value crashes.

BTW: the Object class comes from Realm. I'm trying to JSON -> EVObject -> Realm

crashes with this:
**\* Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<RLMStandalone_ 0x7f8a714acaa0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key .

**Comment by evermeer** [comment]
The problem is the optional Bool. You have the following options to make the .setValue work:
- Make field2 non optional (set default value to false or true)
- implement the function setvalue forUndefinedKey like this:

```
    override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        switch key {
        case "field2":
            self.field2 = value as? Bool
        default:
            NSLog("WARNING: setValue for key '\(key)' should be handled.")
        }
    }


```

**Comment by biskit** [comment]
I did something like this. I would prefer not to set specific fields as I want this copy to be generic.

```
func fcopy<T:EVObject, R:Object>(inobj: T, outobj: R) {
    for c in Mirror(reflecting:inobj).children {
        let tp = Mirror(reflecting:c.value)
        print("\(c.label): \(c.value): \(c.value.dynamicType): \(tp.subjectType)")
        if tp.subjectType == String?.self {
            outobj.setValue(c.value as? String, forKey: c.label!)
        } else if tp.subjectType == Int?.self {
            outobj.setValue(c.value as? Int, forKey: c.label!)
        } else if tp.subjectType == Bool?.self {
            outobj.setValue(c.value as? Bool, forKey: c.label!)
        } else if tp.subjectType == Float?.self {
            outobj.setValue(c.value as? Float, forKey: c.label!)
        } else if tp.subjectType == Array<String>?.self {
            outobj.setValue(c.value as? Array<String>, forKey: c.label!)
        } else if tp.subjectType == Array<Int>?.self {
            outobj.setValue(c.value as? Array<Int>, forKey: c.label!)
        } else if tp.subjectType == Array<Float>?.self {
            outobj.setValue(c.value as? Array<Float>, forKey: c.label!)
        } else if tp.subjectType == AnyObject?.self {
            outobj.setValue(c.value as? AnyObject, forKey: c.label!)
        }
    }
}
```

when i do this, the bool value does not seem to stick!
when i print Test2, i only see the String value. however, no crash :)

**Comment by evermeer** [comment]
what if you set a breakpoint at the .setValue for the Bool. Is it hit? What is in the output log?

Instead of doing a Mirror, you could try using inobj.toDictionary()
The toDictionary function will do some basic value conversion that also works better with .setValue
See the valueForAny function:
https://github.com/evermeer/EVReflection/blob/14a94f0983507e70589ca042c2d2fb2465b82dfe/EVReflection/pod/EVReflection.swift#L552
An other benefit is that it will also get all properties of a baseclass.

**Comment by evermeer** [comment]
O, and did you try:

```
let test = Test()
let test2: Test2 = test.mapObjectTo()
```

**Comment by biskit** [comment]
tried the mapObjectTo() option. get the same error message... 

Terminating app due to uncaught exception 'NSUnknownKeyException',

**Comment by evermeer** [comment]
Yes, but you still need to change the Bool to non optional or implement the 'setValue forUndefinedKey'. You need to do that because of a swift limitations. 

The code below will succeed:

```
func testIssue88() {
        let x = XTest()
        x.field1 = "A"
        x.field2 = true
        let y: XTest2 = x.mapObjectTo()
        XCTAssert(y.field1 == "A")
        XCTAssert(y.field2 == true)
    }

class XTest: EVObject {
    var field1: String?
    var field2: Bool = false
}

class XTest2: NSObject {
    var field1: String?
    var field2: Bool = false
}
```

**Comment by evermeer** [comment]
And this is the second option:

```
    func testIssue88() {
        let x = XTest()
        x.field1 = "A"
        x.field2 = true
        let y: XTest2 = x.mapObjectTo()
        XCTAssert(y.field1 == "A")
        XCTAssert(y.field2 == true)
    }

class XTest: EVObject {
    var field1: String?
    var field2: Bool?
}

class XTest2: NSObject {
    var field1: String?
    var field2: Bool?

    override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        switch key {
        case "field2":
            self.field2 = value as? Bool
        default:
            NSLog("WARNING: setValue for key '\(key)' should be handled.")
        }
    }
}
```

**Comment by biskit** [comment]
neither of them crash  now, but second version (the one just above this comment) does not set values. dumping XTest2 does not print the boolean field. 

i guess boolean should not be non-optional... i'm not trying with NSObject as base class, but Object (from Realm) as base class. that could be the difference, don't know.

**Comment by evermeer** [comment]
I don't have Realm here so I used NSObject instead.  Object will have NSObject as it's base class otherwise you won't be able to do a .setValue. So it should behave the same.

If you set a breakpoint at `self.field2 = value as? Bool`is it hit?

**Comment by biskit** [comment]
Q: If you set a breakpoint at `self.field2 = value as? Bool` is it hit?

if declared as `var field2: Bool?` it does. i was really expecting something more from Swift in the respect. what could be done with a line in java and GSON makes me spray more lines of code everywhere!.
atleast EVReflection removes a lot of the mapping nonsense the other libraries makes you do.

**Comment by biskit** [comment]
once i copy this way with 
```
let test = Test()
let test2: Test2 = test.mapObjectTo()
```
if I access `test2["field1"]` I get `"A"`
if I access `test2.field1` I get `nil`

it seems like its a KVC object not a true object?

**Comment by evermeer** [comment]
The setValue comes from Objective-C. That's also why it needs to have NSObject as a base class. Fortunately Realm also uses NSObject as a base class. Because of this it won't work with a couple of Swift specific types like nullable structs and generics. For a summary of all limitations see: https://github.com/evermeer/EVReflection#known-issues

**Comment by evermeer** [comment]
EVReflection can now be used as a protocol. This makes it possible to extend Realm with all functionality from EVReflection. The only thing you need to add in your Realm project is:

`extension Object: EVReflectable { }`

You could  add extra EVReflection functions to that extension like the initValidation, propertyMapping, propertyConverters, skipPropertyValue and getSpecificType.

So you can just instantiate a Realm object by using code like this:
`Test2(json: theJsonString)`
There is no need to first put it in an EVObject and then map it to an Object
