### ISSUE TITLE
When CFBundleName contains spaces or special characters, getCleanAppName should replace them by underscore

### ISSUE THREAD

**Issue by fredboutin** [evermeer/EVReflection#103]
Bundle names containing spaces or special characters seem to be replaced by underscore in swift namespace. So with a Product Name like "Foo Bar!" and a class file like "Test.swift", you must call NSClassFromString with the string "Foo_Bar_.Test" to get the class. I don't have the list of special characters that are replaced and I did not find it in my quick google search. I guess it's somewhere in apple's documentation. If I get the time, I'll look later this week to find it and make a pull request. I'm sorry I can't fix it now, I'm kind of in the middle of a rush. Feel free to fix it if you find the list.

**Comment by evermeer** [comment]
Currently I only cleanup spaces and dashes. I am also searching for a complete list of characters that should be replaced. If you can find it, that would be great..

Currently the locic is here:
https://github.com/evermeer/EVReflection/blob/6cc2389ec6ec3d9a197c41cff73651633bcf01e2/EVReflection/pod/EVReflection.swift#L416-L416
and here:
https://github.com/evermeer/EVReflection/blob/6cc2389ec6ec3d9a197c41cff73651633bcf01e2/EVReflection/pod/EVReflection.swift#L455-L455

**Comment by evermeer** [comment]
I just replaced it by the following code:
`let cleanAppName = appName.componentsSeparatedByCharactersInSet(illegalCharacterSet).joinWithSeparator("_")
`
Using these as the illegal characters:
`private static let illegalCharacterSet = NSCharacterSet(charactersInString: " -&%#@!$^*()<>?.,:;")
`
It's easy to extend if it's not complete
