### ISSUE TITLE
How can i set Optinal Keys 

### ISSUE THREAD

**Issue by krymtn** [evermeer/EVReflection#107]
I have an optinal keys in my JSON 

```
dataList =     (
                {
            Cities =             (
                CityA
            );
            ConfigName = Config0;
            Configurations =             {
                desc = "Desc2";
                evening = "Evening";
                morning = "Morning";
            };
        },
                {
            Cities =             (
            );
            ConfigName = Config1;
            Configurations =             {
                desc = "Desc";
            };
       }
)
```

For Configurations object evening & morning keys are optional. How can i set my object class for this situation.

**Comment by evermeer** [comment]
when parsing json to an object all properties will be treated as optional. If you do want to enforce required fieds, then you have to override the function initValidation and call the initMustContainKeys function. For more information see: 
https://github.com/evermeer/EVReflection/blob/7f1ce05e74d644f0375031cb5009ba3aa8325175/README.md#deserialisaton-class-level-validations

If you want to write your object back to json, you can override the skipPropertyValue function and return false if the value is nil. For more information see: 
https://github.com/evermeer/EVReflection#skip-the-serialisaton-or-deserialisation-of-specific-values

**Comment by krymtn** [comment]
In my SubConfigurationModel i set like this

```
class EVSubConfigurationModel: EVObject {

    var desc: String?
    var evening: String?
    var morning: String?

    override public func initValidation(dict: NSDictionary) {
        self.initMayNotContainKeys(["desc","morning","evening"], dict: dict)
    }
}
```

And main Configuration model

```
class EVAPIConfigurationModel: EVObject {

    var ConfigName:String?
    var Configurations:EVSubConfigurationModel?
    var Cities:[String]?
}
```

Whats the wrong ? Gives me this error
WARNING: EVAPIConfigurationModel `Configurations` type, `__NSDictionaryM, doesn't match expected type.

**Comment by evermeer** [comment]
What you have above, is that really the json? 
Because you indicate the arrays using round brackets ( instead of square brackets [

Besides that, you now used initMayNotContainKeys which will create forbidden keys. And since you are saying that all your keys are forbidden you will get a status message for these.

The following unit test does work:

```
    func testIssue107() {
        let dataList = "[{" +
            "    \"Cities\" :  [\"CityA\"]," +
            "    \"ConfigName\" : \"Config0\"," +
            "    \"Configurations\" :             {" +
            "        \"desc\" : \"Desc2\"," +
            "        \"evening\" : \"Evening\"," +
            "        \"morning\" : \"Morning\"," +
            "    }" +
            "}," +
            "{" +
            "    \"Cities\" : [\"\"]," +
            "    \"ConfigName\" : \"Config1\"," +
            "    \"Configurations\" :             {" +
            "        \"desc\" : \"Desc\"" +
            "    }" +
            "}]"

        let c = [EVAPIConfigurationModel](json: dataList)
        print©

        for i:EVAPIConfigurationModel in c {
            if let conf: EVSubConfigurationModel = i.Configurations {
                print("Errors: \(conf.evReflectionStatuses)")
            }
        }
    }
```

And the print statement will print out 4 issues.
3 for your first object where you specified all 3 keys
1 for your second object where you specified only 1 key.

**Comment by evermeer** [comment]
This issue was added as a unit test and discussed in a private email conversation

The unit test can be found here:
https://github.com/evermeer/EVReflection/blob/405d94dce91578ff3743019d0faf7e4a83083dfe/EVReflection/EVReflectionTests/EVReflectionIssue107.swift#L27-L27
