### ISSUE TITLE
Convert to/from arrays

### ISSUE THREAD

**Issue by hegra** [evermeer/EVReflection#112]
Creating an array of objects from json is feasable by:

```
let json:String = "[{\"id\": 27, \"name\": \"Bob Jefferson\"}, {\"id\": 29, \"name\": \"Jen Jackson\"}]"
let array:[User] = [User](json: json)
```

But how to convert an array from an array of dictionaries and vice versa, i.e:
`let array:[User] = [User](array: <[Dictionary]>)`
and 
`let dictionaryArray:[Dictionary] = <[User]>.toDictionaryArray()`

The reason for this feature request is that some json rest api sdks return half parsed objects and not raw strings, and serializing them back to json first seems to be a waste of time.

**Comment by evermeer** [comment]
I think this would be the easiest way to do this:

```
        let dictionaryArray: [NSDictionary] = ...
        let array: [User] = dictionaryArray.map { User(dictionary: $0) }
        let newArray: [NSDictionary] = array.map { $0.toDictionary() }
```

**Comment by hegra** [comment]
Worked great! 
Should be in the documentation.

Thanks

**Comment by evermeer** [comment]
@hegra That's a good one....

I also just found out I already had helper methods for these..
You could have used this:

```
        let dictionaryArray: [NSDictionary] = ...
        let array2 = [User](dictionaryArray: dictionaryArray)
        let newArray2 = array2.toDictionaryArray()
```
