### ISSUE TITLE
Instantiating generics

### ISSUE THREAD

**Issue by hegra** [evermeer/EVReflection#113]
Hi.

Any reason why,

EVObject{
init(dictionary: ... 
init(json: ...
}
are convenience only and not convenience required?

Would be nice to have them convenience required to be able to instantiate generics...

**Comment by evermeer** [comment]
Hmm... I remember having problems with making those 2 required... but... I just tried it and everything seems to work... Let me do some more test with the other libraries that are using EVReflection to see if the problem is there...

**Comment by evermeer** [comment]
All seems to work... I will make the change and push it to GitHub. It's still running through my mind that there was something with it... well, I will handle that when that surfaces again. It's now version 2.43.0
