### ISSUE TITLE
 Cant Parse Int object

### ISSUE THREAD

**Issue by iAviatorJose** [evermeer/EVReflection#115]
I have a the below model class 

Language : Swift  
version : 1.2

class UserProfile : EVObject {
  var uid : String?
   var mobile: Int?  -->
}

and i get the following warning: while doing this 

var user  = UserProfile(dictionary: userDict)

WARNING: The class 'UserProfile' is not key value coding-compliant for the key 'mobile'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information

**Comment by evermeer** [comment]
As the warning says there is no support for optional types like int? (there is for String?) This is a limitation of Swift. When calling the setValue forKey for such a field you will get that warning. For more information see https://github.com/evermeer/EVReflection#known-issues There are workarounds for this. You can do one of these things:
- change from optional Int to a non optional Int (with a default value of ..)
- change the optional int to an optional NSNumber. (var mobile: NSNumber?)
- add the function 'setValue forUndefinedKey' for a demo see https://github.com/evermeer/EVReflection/blob/ddb5bc7c754a388745457610a5b087b9ba4d4fec/EVReflection/EVReflectionTests/EVReflectionConversionOptionsTest.swift#L59-L59

**Comment by iAviatorJose** [comment]
@evermeer  Thank You for your attention. I have made changes according to your suggestions.
And thank you for your wonderful library.  :) 👍

**Comment by evermeer** [comment]
you're welcome...
