### ISSUE TITLE
Minimum macOS version supported

### ISSUE THREAD

**Issue by tylerlong** [evermeer/EVReflection#117]
![image](https://cloud.githubusercontent.com/assets/733544/17997714/e662c8f2-6ba2-11e6-849c-27880ca49649.png)

Installed the framework via Carthage and got the error above.

Is it possible to support as low as macOS 10.9 since it's the oldest version which can run Swift?

**Comment by evermeer** [comment]
I just pushed this as a new version to CocoaPods and GitHub as version 2.45.1
