### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by falkobuttler** [evermeer/EVReflection#122]
Is there any plan to officially support Swift 3? The Swift3 branch is outdated and also doesn't actually compile (more than 60 errors). Some of the errors seem very hairy and not easy to fix for an outsider like me, otherwise I would have created a PR.

**Comment by evermeer** [comment]
I was holding back the push with the latest updates because of a reflection problem with enums. I just pushed it anyway to the Swift3 branch. There is only 1 unit test still failing. This can happen when using an enum in an array and you want to write it to json. I'm still looking for a workaround.

**Comment by jacamallonga** [comment]
For Swift3 branch is not possible to inherit from 'EVObject' since it needs to be an open class and right now is public only. Is there any update coming soon for that? Thanks. 

The error is: "Cannot inherit from non-open class 'EVObject' outside of its defining module"

**Comment by evermeer** [comment]
Ah, I did not know about the new open access control level. I will change that the moment I get home (in about 3 hours)

**Comment by evermeer** [comment]
It's now converted from public to open.

**Comment by evermeer** [comment]
I think this is now good enough to move this to master.
If there are no objections, then I will do that this weekend.

**Comment by froimer** [comment]
Hi, Swift 3 branch was merged to master? Thanks.

**Comment by falkobuttler** [comment]
Please go ahead with the merge. Thanks!

**Comment by evermeer** [comment]
master is now updated to swift3
