### ISSUE TITLE
Crashing Swift3

### ISSUE THREAD

**Issue by hardikdevios** [evermeer/EVReflection#124]
**Not working** : `Xcode 8, Swift 3 
`
**Was Working Fine** : `Xcode 7.3.x, Swift 2.2`

![screen shot 2016-09-20 at 2 05 38 am](https://cloud.githubusercontent.com/assets/6657591/18648156/fd871352-7ed6-11e6-8dc6-2924f759ddff.png)

**MY Model**
![screen shot 2016-09-20 at 2 08 25 am](https://cloud.githubusercontent.com/assets/6657591/18648213/49807e38-7ed7-11e6-99e7-d7b7a237a550.png)

**What i am Doing** 
![screen shot 2016-09-20 at 2 09 08 am](https://cloud.githubusercontent.com/assets/6657591/18648222/5b415e08-7ed7-11e6-80ec-8fdf98855de0.png)

> I have not changed anything Just Automatic Swift 3 Xcode Tool migration. Any Help ?

**Comment by evermeer** [comment]
I assume that you are using the EVReflection Swift3 branch is that right?

**Comment by evermeer** [comment]
I see that the error occurs inside the check for type enum. In your sample code I don't see any enums. Are you sure that this error comes from the code that you show here? Could you send me the .plist file?

**Comment by hardikdevios** [comment]
Yes Swift 3 branch
Just a min sending plist file

**Comment by hardikdevios** [comment]
Pod file 
![screen shot 2016-09-20 at 2 46 33 am](https://cloud.githubusercontent.com/assets/6657591/18649323/9622e744-7edc-11e6-8174-a2c4f51c975e.png)

**.Plist**
[MoreScreen.plist.zip](https://github.com/evermeer/EVReflection/files/481141/MoreScreen.plist.zip)

> Let me know anything you need

**Comment by evermeer** [comment]
I added a test for your issue and it runs without any problem. At what line in your own source does the crash happen?

You can find the test here:
https://github.com/evermeer/EVReflection/blob/Swift3/EVReflection/EVReflectionTests/EVReflectionIssue124.swift#L27

**Comment by hardikdevios** [comment]
ohk let me run on my pc again will update you or close the issue if its something needs to be fixed from my side, but thanks for great support

**Comment by hardikdevios** [comment]
ok i have found something.

**Non optional** //Crash 👎 

```
class MoreSection: EVObject {
    var SectionOrder: NSNumber!
    var values: [MoreObject]!
}
```

**With optional** //Worked 👍 

```
class MoreSection: EVObject {
    var SectionOrder: NSNumber?
    var values: [MoreObject]?
}

```

**Crash screen**
![screen shot 2016-09-20 at 12 07 09 pm](https://cloud.githubusercontent.com/assets/6657591/18659854/d88f5858-7f2a-11e6-8ab6-0c5a6b7f276a.png)

> Now, the question is do we need to set the Optional even if we know that this field never going to be nil ? **this was working in Swift 2.x with Xcode 7.3.x**

**Comment by evermeer** [comment]
I have added support for ImplicitlyUnwrappedOptional to the Swift 3 branch. I have also updated your unit test.
