### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by kuyazee** [evermeer/EVReflection#126]
what pod version should I use for swift 2.3 support?

**Comment by kuyazee** [comment]
the swift 2.3 branch tells me to use version EVReflection version 2.6 but this error seems to be popping
"“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly."

and yes I've set the project to use legacy swift.

**Comment by evermeer** [comment]
I think you should add something like this to your podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
```

You could also manually set this in the pod project afeter a 'pod install' is done.

**Comment by kuyazee** [comment]
yeah I think it's fixed now somehow

what I did was I deintegrated cocoapods from the project and then reinstalled cocoapods to the project and somehow it got fixed. weird

thanks for the effort though :)
