### ISSUE TITLE
The class is not key value coding-compliant for the key

### ISSUE THREAD

**Issue by allemattio** [evermeer/EVReflection#130]
Hi, 
I'm using EVReflection in my app.
I'm trying to deserialize this JSON:
`{
    "fields": [
        {
            "name": "client_interested",
            "type": "text",
            "title": "Test title",
            "hint": "test hint"
        }
    ],
    "validator": {
        "client_interested": {
            "required": true
        }
    }
}`

in this class:

```
class FeedbackForm: EVObject {
    var fields = [FeedbackField]()
    var validator = [String: Any]()

    required init() {
        print("init")
    }
}
```

But I get the error:
`The class 'Optional("FeedbackForm")' is not key value coding-compliant for the key 'validator'`

Can someone explain me why? Are dictionaries not supported?

**Comment by evermeer** [comment]
values are set using the .setValue forKey This is also the reason why the base class should alwas be NSObject. (Which is the base of EVObject). There are a couple of property types that can not be set wit the .setValue forKey (swift limitation) Unfortunately there is no other way to set a property based on it's key.

For all of these limitations there are workarounds available. The most obvious one that works for all is implementing the method setvalue forUndefinedKey. See the unit test in EVReflectionWorkaroundsTests for a sample. An other option would be by changing the property to a NSDictionary
