### ISSUE TITLE
Model file in diffrent lib

### ISSUE THREAD

**Issue by hardikdevios** [evermeer/EVReflection#132]
Lets say i have created one Lib file `EVLib.framework` and have one model file with pod of `EVReflection` . 

Model file 

```
import Foundation
import EVReflection
open class Withings:EVObject{

    public var attrib:NSNumber?
    public var category:NSNumber?
    public var grpid:NSNumber?
    public var date:NSNumber?
    public var measures:[WithingMeasures]?
    public var comment:String?


}


open class WithingMeasures:EVObject{



    public var type:NSNumber?
    public var unit:NSNumber?
    public var value:NSNumber?
    public var realValue:NSNumber {

        return NSNumber(value: (self.value?.floatValue ?? 0.0) * pow(10.0,self.unit?.floatValue ?? 0.0) )


    }



}

```

Now i have App call `EVApp` imported this lib in my App 
Now will this function work ?

Taken from `EVReflection` file 

```
public class func swiftClassTypeFromString(_ className: String) -> AnyClass? {
        if let c = NSClassFromString(className) {
            return c
        }

        // The default did not work. try a combi of appname and classname
        if className.range(of: ".", options: NSString.CompareOptions.caseInsensitive) == nil {
            let appName = getCleanAppName()
            if let c = NSClassFromString("\(appName).\(className)") {
                return c
            }
        }

        if let bundleIdentifiers = bundleIdentifiers {
            for aBundle in bundleIdentifiers {
                if let existingClass = NSClassFromString("\(aBundle).\(className)") {
                    return existingClass
                }
            }
        }

        return nil
    }
```

I am getting this **error** 

> ERROR: Could not create an instance for type WithingMeasures
> `measures` with Type of `WithingMeasures` is not getting map

**Comment by evermeer** [comment]
As you can see in the swiftClassTypeFromString EVReflection will use the app identifier as the default for locating your classes. When you place your class definitions in a framework, then you have to make EVReflection aware of that by setting the bundle identifier (or indentifiers) by hand. You can do that by calling the following line (only have to do that once, can be done on app startup:
`EVReflection.setBundleIdentifier(Withings.self)`

P.S. When you have multiple frameworks, then use the .setBundleIdentifiers function

**Comment by hardikdevios** [comment]
Ok great will apply that but i think you should update README.md with this info.

**Comment by evermeer** [comment]
As you sugested I added instructions to the readme (only Swift3 branch)
