### ISSUE TITLE
skipPropertyValue should be open rather than public

### ISSUE THREAD

**Issue by lchoquel** [evermeer/EVReflection#134]
Hi,
skipPropertyValue must be open instead of public, otherwise compiler doesn't allow to override it outside module (XCode 8.1).

This way it works for me:
    open func skipPropertyValue(_ value: Any, key: String) -> Bool {
        return false
    }

**Comment by evermeer** [comment]
Ah, sorry, missed that one. 
I did an extensive refactor and this one slipped in.
I just pushed version 3.2.1 to GitHub and Cocoapods with the fix.

**Comment by lchoquel** [comment]
It works.
Btw, thanks for this project, it rocks.
