### ISSUE TITLE
getSpecificType overridden by getGenericType

### ISSUE THREAD

**Issue by jwardle** [evermeer/EVReflection#135]
EVGenericsKVC classes with getGenericType override EVObjects with a getSpecificType method declared. This breaks ClassObject<GenericType> implementations where GenericType itself can have specific types that subclass it. 

Within EVReflection.swift (Swift 3 branch) it appears an `else` keyword is missing on line 1138 as such:

```
for item in array {
            //var org = result.getTypeInstance() does not work !?
            var org = swiftClassFromString(subtype)
            if let evResult = org as? EVObject {
                org = evResult.getSpecificType(item as? NSDictionary ?? NSDictionary())
            }
            // ** ELSE is missing            
            else if let evResult = anyObject as? EVGenericsKVC {
                org = evResult.getGenericType()
            }

            let (arrayObject, valid) = dictToObject(subtype, original:org, dict: item as? NSDictionary ?? NSDictionary(), conversionOptions: conversionOptions)
            if arrayObject != nil && valid {
                result.append(arrayObject!)
            }
        }
```

**Comment by evermeer** [comment]
A couple of hours ago I pushed a major change of EVReflection where most functionality is moved to a protocol with default implementations. Also the part that you mentioned was changed. The current version is:

```
        for item in array {
            //var org = result.getTypeInstance() does not work !?
            var org = swiftClassFromString(subtype)
            if let evResult = org as? EVReflectable {
                if let specific = evResult.getSpecificType(item as? NSDictionary ?? NSDictionary()) as? NSObject {
                    org = specific
                }
            }
            if let evResult = anyObject as? EVGenericsKVC {
                org = evResult.getGenericType()
            }
            let (arrayObject, valid) = dictToObject(subtype, original:org, dict: item as? NSDictionary ?? NSDictionary(), conversionOptions: conversionOptions)
            if arrayObject != nil && valid {
                result.append(arrayObject!)
            }
        }
```

I do see that it is also missing the else. I will push a change in the next 10 minutes.

Thanks for reporting this!
It was a good description that even included the fix.
You are making my life easy 😀

**Comment by evermeer** [comment]
Ah... but that does not work... When a class is a EVGenericsKVC it's also EVReflecable so it will never come in the else... The .getSpecificType also always will return the class itself if the method is not implemented, so the else also cannot be moved  to the 'if let specific...'

I have to see if there is a way to see if the .getSpecificType returned something else than the class itself. This will take a little more than 10 minutes...

**Comment by evermeer** [comment]
I just pushed release 3.2.2 to GitHub and CocoaPods with the fix where the specificType has precedence over the genericType. I do still need to create a good unit test for this.

**Comment by jwardle** [comment]
Awesome! Will test it out & close. Glad I didn't PR now - as obviously more
complex than my quick fix!

**Comment by jwardle** [comment]
Fixed! Thanks for the rapid resolution :)
