### ISSUE TITLE
how do I add this to my cartfile?

### ISSUE THREAD

**Issue by kuyazee** [evermeer/EVReflection#136]
using Swift 2.3?

github "evermeer/EVReflection" :branch => 'Swift2.3'

**Comment by evermeer** [comment]
I'm not a Carthage expert (I use cocoapods) but I think you should put it in your cartfile like this:
github "evermeer/EVReflection" "Swift2.3"

**Comment by kuyazee** [comment]
Thanks it worked.  I'm studying how to make frameworks and what I've found for building a framework on top of a framework is by using Carthage, and I've no idea how to use Cocoapods to build frameworks on top of frameworks.

**Comment by evermeer** [comment]
Great to hear that it worked. 

For the framework issue: I have done that using Cocoapods. For instance EVWordpressApi is using AlamofireJsonToObjects which is using Alamofire and EVReflection. No idea if it should work with Carthage

**Comment by kuyazee** [comment]
thanks I'll have a look at how that library is set up cause I'm also trying to make a framework using both Alamofire and EVReflection. btw thanks your library is awesome

**Comment by grago** [comment]
Hello, i am trying to add EVReflection/Moya to my project using Carthage, but the extension doesn't seem to be loaded.

Here's my Cartfile:

```
github "Moya/Moya"
github "evermeer/EVReflection"
```

I am able to import EVReflection module and use the classes, but response object doesn't seem to have the extension methods available (like mapArray)

Do i need to specify a tag or branch? Thanks.

**Comment by evermeer** [comment]
I only created a Carthage framework for the core EVReflection.
I have no experience with Carthage.
If someone can create a pull request with Carthage support for all
subspaces, then that would be great.
For now you could just add the EVReflection framework and add the following
class to your project:
https://github.com/evermeer/EVReflection/blob/master/Source/Alamofire/Moya/Response%2BEVReflectable.swift





2017-03-31 14:13 GMT+02:00 Gustavo Rago <notifications@github.com>:

**Comment by grago** [comment]
@evermeer I understand. I did what you suggested and got it working. Thanks a lot.
