### ISSUE TITLE
New keyword can't add into object

### ISSUE THREAD

**Issue by jtianling** [evermeer/EVReflection#14]
zone, private

**Comment by evermeer** [comment]
Thanks, I added those keywords to the list of exceptions. I pushed version 2.5.4 to GitHub
You can now use these keywords with an underscore as a variable like:
var _zone: String
If you know any other keywords that I am missing, then just let me know.

**Comment by biskit** [comment]
description is another common one...

**Comment by evermeer** [comment]
Thanks @biskit , but it's already in the keyword lis. This is the current lis:

`
    private static let keywords = ["self", "description", "class", "deinit", "enum", "extension", "func", "import", "init", "let", "protocol", "static", "struct", "subscript", "typealias", "var", "break", "case", "continue", "default", "do", "else", "fallthrough", "if", "in", "for", "return", "switch", "where", "while", "as", "dynamicType", "is", "new", "super", "Self", "Type", "__COLUMN__", "__FILE__", "__FUNCTION__", "__LINE__", "associativity", "didSet", "get", "infix", "inout", "left", "mutating", "none", "nonmutating", "operator", "override", "postfix", "precedence", "prefix", "right", "set", "unowned", "unowned", "safe", "unowned", "unsafe", "weak", "willSet", "private", "public", "internal", "zone"]
`
