### ISSUE TITLE
Question: can I serialize to plist dictionary/deserialize from plist dictionary?

### ISSUE THREAD

**Issue by kas-kad** [evermeer/EVReflection#144]
Hello, as you may know `UILocalNotification.userInfo: [AnyHashable : Any]?` has a restriction: values must be of valid Property List types. So I wonder, is it possible to serialize an arbitrary Swift struct/class to a plist compatible dictionary using EVReflection? Deserialization is also needed.

UPDATE: moved my question to gitter chat https://gitter.im/evermeer/EVReflection

**Comment by evermeer** [comment]
And for anyone else that ends up here, the result of the chat is:

You can find a plist serialisation sample at https://github.com/evermeer/EVReflection/blob/master/EVReflection/EVReflectionTests/EVReflectionIssue124.swift#L28 I have never done any tests with UILocalNotification.userInfo So I’m not sure if there could be any issues there.

And handling a dictionary in an object can be handled with code like this:
In short... You need to implement the setValue forUndefinedKey

```

func testPlistEncoding() {
    let bdate = Date()
    let data = ["fav meal": "pizza"]
    let fname = "andrey"
    let me = Person(firstname: fname, birthdate: bdate, data: data)

    let dict = me.toDictionary()

    let p = Person(dictionary: dict, conversionOptions: ConversionOptions.DefaultDeserialize, forKeyPath: nil)
    XCTAssertEqual(p.birthdate, me.birthdate)
    XCTAssertEqual(p.data, me.data) // failed: [:] is not equal ["fav meal": "pizza"]
    XCTAssertEqual(p.firstname, me.firstname)
}
class Person: EVObject {
var firstname: String
var data: [String: String]
var birthdate: Date
init(firstname: String, birthdate: Date, data: [String: String]) {
    self.firstname = firstname
    self.data = data
    self.birthdate = birthdate
}

required convenience init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
}

required init() {
    self.firstname = ""
    self.data = [String: String]()
    self.birthdate = Date()
}

override open func setValue(_ value: Any!, forUndefinedKey key: String) {
    switch key {
    case "data":
        if let dict = value as? NSDictionary {
            self.data = [:]
            for (key, value) in dict {
                self.data[key as? String ?? ""] = (value as? String)
            }
        }
    default:
        print("---> setValue for key '\(key)' should be handled.")
    }
}
}

```
