### ISSUE TITLE
Deserialize AnyObject?

### ISSUE THREAD

**Issue by luky0007** [evermeer/EVReflection#145]
Hi!,
I use your great library for serialize and deserialize jsons in swift. To this day I use version not from pod but manually downloaded from github far time ago and issue that I described worked - so probably you do some fixes who was now problematic for me. Today I want to update my project na use pod. Now I use: 
pod 'SwiftyRSA', :git => 'https://github.com/TakeScoop/SwiftyRSA.git', :branch => 'swift-2.3'

I have rsp object like this:

```
class LoginRspData : EVObject{
    var token:String?
    var data:AnyObject?
}
```

for some reason I don't want to mapping all data because its very complicated object, but also for some reason I want to have reference for AnyObject data to pass them to another place. So when I deserialize like this:

```
        let rsp = LoginRspData(json: json)
        print(rsp.description)

```
data is now empty, but is not correct for me - I want to do somethink only like this:
```
class AnotherClass: EVOObject{
var alfa:String
var beta:String
var data: AnyObject?
}

let another = AnotherClass()
another.beta = "test"
another.alfa = "test"
another.data = loginRspDataObject.data
print(another.toJsonString())
```
so I want to print in last line show me my complicated data object, I don't do anythink with this data object, only want pass them to another system (for example backend system) so I don't want to deserialize it filed by field, object by object. Can you help me? Meybe you rememeber what changed, or meybe I have other problem.

update
I try founded: 

```
    override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        switch key {
        case "data":
            if let dict = value as? NSDictionary {
                self.data = [:]
                for (key, value) in dict {
                    self.data[key as? String ?? ""] = (value as? String)
                }
            }
        default:
            print("---> setValue for key '\(key)' should be handled.")
        }
    }
```
but my data is complicated: some values in this part of json are Arrays, some Strings, some NSNumber, so this forUndefinedKey, not deserialize complite my data, only this were values is string. So still no result :(

**Comment by evermeer** [comment]
EVReflection is using the default Apple JSONSerialization class for converting a json string to a dictionary and back. When you initialize your object with LoginRspData(json: json) then JSONSerialization will create a dictionary for that json. In your case you will probably have a data key with a dictionary which you want to place in the AnyObject.

EVReflection will go through that dictionary and try to set it on the object using the function 'setValue forKey'. Before doing so there is some type checking done to see if you are allowed to execute that function or that it needs to be converted first. 

Without doing extensive tests I don't see why this would fail now. A NSDictionary can be casted to an AnyObject so this should be possible. Do you see anything in the console output what could indicate what's going wrong? EVReflection should log something if it fails to set a value.

**Comment by luky0007** [comment]
thanks for feedback, I checked and 
this now not work:
```
class LoginRspData : EVObject{
    var token:String?
    var data:AnyObject?
}
```
but this worked:
```
class LoginRspData : EVObject{
    var token:String?
    var data:NSDictionary?
}
```
there are not any intresting log in console

**Comment by evermeer** [comment]
Thanks, I will have a look to see why the AnyObject does not work...

**Comment by evermeer** [comment]
I have just pushed version 3.5.1 to GitHub and Cocoapods with a fix for this issue.
You can find the unit test for this here:
https://github.com/evermeer/EVReflection/blob/master/EVReflection/EVReflectionTests/EVReflectionIssue145.swift#L29

**Comment by luky0007** [comment]
Thanks a lot!
