### ISSUE TITLE
a little issue

### ISSUE THREAD

**Issue by MemorySeal** [evermeer/EVReflection#146]
I have been paying attention for a long time, a small problem has not been solved.
Have you tested when an array property does not exist?

if theValue is Array< Any > {
            return ((theValue as! Array< Any >) as AnyObject, valueType, false)
        }

will crash(if Array< Any >  is nil), make it to 

if theValue is Array< Any >  {
            return (theValue as AnyObject, valueType, false)
        }
will be work

**Comment by evermeer** [comment]
Thanks for reporting this. I found a couple of other unnecessary double casts and removed those too. This has now been pushed to GitHub and Cocoapods as version 3.5.2
