### ISSUE TITLE
Convert to Current Swift Syntax?

### ISSUE THREAD

**Issue by frios** [evermeer/EVReflection#147]
When installing via CocoaPods using 

pod "EVReflection"

I get the convert to current swift syntax message upon opening my project. My project is using Xcode 8.2.1 and all files are Swift 3. Is this not installing the correct version of EVReflection?

**Comment by evermeer** [comment]
I have seen this before that for some reason it does not download the latest version. If you do a pod update you should see that version 3.5.2 was downloaden. I suspect that you get an older version. If that's the case, could you try force getting the 3.5 version by using:
`pod 'EVReflection', '~> 3.5'`

Maybe it's the minimum iOS version that is set. Do you have it set to iOS 7? I currently have set it to iOS 8 in the podspec. If you have set the minimum to 7, then maybe cocoapods is getting a version where i still had it on 7. I will now do some tests to see if it can support iOS 7

**Comment by frios** [comment]
My minimum version was set to 8.1. I have used 
`pod 'EVReflection', '~> 3.5'`
It installed 3.5.2 but I still get the error

![screen shot 2016-12-30 at 1 27 54 pm](https://cloud.githubusercontent.com/assets/6867187/21572938/f9f19d22-ce93-11e6-8692-50b399490762.png)

**Comment by frios** [comment]
Did not mean to close it...

My minimum version was set to 8.1. I changed it to 9.0 
I have used 
`pod 'EVReflection', '~> 3.5'`
It installed 3.5.2 but I still get the error

![screen shot 2016-12-30 at 1 27 54 pm](https://cloud.githubusercontent.com/assets/6867187/21572938/f9f19d22-ce93-11e6-8692-50b399490762.png)

**Comment by evermeer** [comment]
Strange... 
3.5.2 is the latest version which is definitely for Swift 3. 
For Cocoapods I even have a .swift-version file that is set to 3.0
I added EVReflection to one of my other projects that is in Swift 3 and it just worked.

Could you try one other thing? Could you remove the EVReflection from your podfile, then do a `pod update`, then add it back in and do a `pod install`. Just to be sure there is no cocoapods caching issue. I will look around on the internet to see if I can find something about this issue.

Thansk for your help

**Comment by frios** [comment]
Well I updated cocoapods and I made sure that my source code was Swift 3.0 compliant and also removed and re added EVReflection. Something worked! I think it was updating Cocoapods. In any case, its all working now. Thank you.

**Comment by evermeer** [comment]
OK, then it looks like a cocoapods issue. Closing this one...
