### ISSUE TITLE
.PrettyPrinted in branche swift 2.3

### ISSUE THREAD

**Issue by luky0007** [evermeer/EVReflection#148]
Hi again!
I use branche for swift 2.3 via cocoapods because my project is in swift 2.3 (not want to update now):
  pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git', :branch => 'Swift2.3'

I have a problem with PrettyPrinted - I send our json's to Javascript side and not want pretty print with '\n' I check that you use in  NSJSONSerialization.dataWithJSONObject PrettyPrinted as default
let jsonData = try NSJSONSerialization.dataWithJSONObject(dict, options: .PrettyPrinted), I also check and in next version of EVReflection for Swift 3.0 you send is as parametr and it not hardcoded to PrettyPrinted. It's possible to change it also on branche 2.3? It's very complicated to use inherited or somethink else to change it yourself.

**Comment by evermeer** [comment]
I guess I could add the .PrettyPrinted as an option to the 2.3 branch. 
You do have to be aware that I only fix bugs in the master (Swift 3.0)
The 2.3 branch is now more than 5 months old.

**Comment by evermeer** [comment]
Done... It's now also in the Swift 2.3 branch

**Comment by luky0007** [comment]
Thanks Thanks Thanks Thanks and thank you!!!
![keep-calm-and-remember-you-are-awesome-4](https://cloud.githubusercontent.com/assets/24697462/21604389/3c43c9fe-d1a3-11e6-9d41-695a7d8ad4f4.jpg)
