### ISSUE TITLE
Enheritance?

### ISSUE THREAD

**Issue by RenniePet** [evermeer/EVReflection#149]
Your readme uses the word "enheritance" 4-5 times. Is this a spelling mistake or am I missing something?

**Comment by evermeer** [comment]
Oeps, yes its a spelling mistake... Thanks for reporting this... I will change it to 'inheritance' now.

**Comment by evermeer** [comment]
Done...

**Comment by RenniePet** [comment]
And one "enherited".

Glad you could use my input. A lot of people get irritated when I unleash my OCD ...

**Comment by evermeer** [comment]
Thanks again... At least i was consequent... I fount 5 'enherited' also in code comment.
As a dyslectic non native English speaker I always welcome tips like these.
