### ISSUE TITLE
When set value from a int to a string, it will crash.

### ISSUE THREAD

**Issue by jtianling** [evermeer/EVReflection#15]
When the type from string to the object is mismatch, it will crash. For example, It's int type in the string and string type in the object. I think it should not crash in any situation, it could throw a exception.

**Comment by evermeer** [comment]
When using JSON it's allowed to put a number in a string and a string in a number. 
If you do the same directly in a dictionary it will also pass.
The following tests will pass:

```
class EVReflectionJsonTests: XCTestCase {
    func testTypeJson() {
        let json:String = "{\"myString\":1, \"myInt\":\"2\"}"
        let a = MyStringInt(json: json)
        XCTAssertEqual(a.myString, "1", "myString should contain 1")
        XCTAssertEqual(a.myInt, 2, "myInt should contain 2")
    }
    func testTypeDict() {
        let dictOriginal = [
            "myString": 1,
            "myInt": "2"
        ]        
        let a = MyStringInt(dictionary: dictOriginal)
        XCTAssertEqual(a.myString, "1", "myString should contain 1")
        XCTAssertEqual(a.myInt, 2, "myInt should contain 2")
    }
}

public class MyStringInt: EVObject {
    var myString : String = ""
    var myInt : Int = 0
}
```

In your case, did you create your own dictionary and tried to create an object from that? And you put an Int value for a field that should be a String? Of course that's wrong. But you are right, It should not crash. I will have a look at this.

**Comment by jtianling** [comment]
I knew there was a mistake, But it is a normal condition that parsing the data from server and I can't control what it is. In that situation, I could parse the data and ignore it, but it should not crash.

**Comment by evermeer** [comment]
As I said, you are right :) I only can't reproduce the crash. As you can see in the tests above you should be able to put a number in a string and a string into a number. Could you show me at what line exactly the crash happens and maybe include the values of the variables at that line? I added the above tests to the project on Github. It would even be greater if you were able to create a test that fails.

**Comment by jtianling** [comment]
The same test code failed in XCode7 beta4, the swift2 branch.
20: error: -[EVReflectionTests.EVReflectionJsonTests testTypeJson] : failed: caught "NSInvalidArgumentException", "-[__NSCFNumber length]: unrecognized selector sent to instance 0xb000000000000013"

29: error: -[EVReflectionTests.EVReflectionJsonTests testTypeDict] : failed: caught "NSInvalidArgumentException", "-[__NSCFNumber length]: unrecognized selector sent to instance 0xb000000000000013"

**Comment by evermeer** [comment]
Ah, that helps! I already fixed that bug in the trunk. I guess it's time to do another merge to the 2.0 branch. I will do that later today. Thanks for your help!

**Comment by evermeer** [comment]
I just pushed the merge to the Swift 2.0 branch. The tests can be found as testTypeDict and testTypeJson

If you find any other issue, then please let me know.
Thanks for reporting this.
