### ISSUE TITLE
Swift2.3+EVReflection2.46.0 memory leak

### ISSUE THREAD

**Issue by 8ggmaker** [evermeer/EVReflection#150]
Hi,I tested our App with Instruments, and found memory leak when call 'toJsonString' function. It caused a memory leak when checking type in function 'valueForAnyDetail':
```Swift
if theValue is NSNumber {
            return (theValue as! NSNumber, "NSNumber", false)
}
```
I think it is a bug of Swift2.3 when using protocol argument (the argument 'theValue' is type of 'Any', a protocol argument) [SR-1205](https://bugs.swift.org/browse/SR-1205).
And I have test with Swift3.0, it works normally without memory leak, it only occurs in Swift2.x
Maybe it can use 'AnyObject' replace 'Any' to resolve this problem by doing some boxing and unboxing jobs with Struct types?
Thanks!

**Comment by evermeer** [comment]
Thanks for reporting this. Swift 2.3 does have a low priority for me. Are you actively using the Swift 2.3 branch and is this issue a real issue for you?

If you do find a solution for this issue, then a pull request would be very welcome. 😊

**Comment by 8ggmaker** [comment]
Thanks for reply. We will prepare to migrate our code to Swift 3.0, it seems that this is not an urgent problem. Just post this issue in case others may encounter this problem
