### ISSUE TITLE
Create copy of model class

### ISSUE THREAD

**Issue by Pinank** [evermeer/EVReflection#156]
How can i create a copy of a particular model instance to avoid the referencing issue?

**Comment by evermeer** [comment]
It's easy to create a copy of an object.
If you have a class named MyObject, then you could do this:
```swift
let obj1 = MyObject()
obj1.title = "some data"
let obj2 = MyObject(usingValuesFrom: obj1)
obj1.title = "some other data"
```
In this code obj1.title will be "some other data" and in obj2.title it will be "some other data"

**Comment by evermeer** [comment]
O, and you could use the same usingValuesFrom while using different types that have similar properties. It was originally intended to create an object mapping mechanism (from one type to an other)

**Comment by Pinank** [comment]
Thanks Edwin for the response,

Actually the issue is, Let's

let obj1 = [MyObject]()
let obj2 = [MyObject]()

Obj2 with an array with all or some less values than obj1 depending on the user selection, I'm removing and adding object at selected index. While doing this, its removing the data from obj1. It should remain static as its the main object. The adding and removing should only going to perform on  obj2 only.

**Comment by evermeer** [comment]
Do I understand correctly that the objects in obj2 are the same objects as in obj1? Removing and adding objects from only obj2 should not influence what's in obj1 array. I think that could only happen when the 2 arrays point to the same array. How are those arrays initiated? Is the second array created based on the 1st?

**Comment by Pinank** [comment]
Lets Say, obj1 is an array of 5  objects and rendered on a tableview, now i select 2nd and 3rd from it so i'll add 2nd and 3rd in obj2. It'll work. Now i'm deselecting 3rd object. So, what i do is remove that object from obj2 array. Its creating issue at this point. Its removing object from obj1 also.

**Comment by Pinank** [comment]
class MyObject: EVObject {
	var name : String = “”
	var subMyObj : [SubMyObj]
}

class SubMyObj: EVObject {
	var surname : String = “”
}

Response

[
{
	“name” : “abc”,	
	“subMyObj” : [
	{
	“surname” : “test”
	},
	{
	“surname” : “test”
	},
	{
	“surname” : “test”
	},
	{
	“surname” : “test2”
	}
},
{
	“name” : xyz,	
	“subMyObj” : [
	{
	“surname” : "gfd"
	},
	{
	“surname” : “tfghjk”
	}
}
]
}

Obove response if obj1, it'll render in a table view. now i select 2nd cell. So i'll add 2nd object with its sub object in obj2 now if i remove one of its sub object than its removing from the obj1 also

**Comment by evermeer** [comment]
This should work as any Swift code where you work with an array of objects. So it would be something like this:
```swift
let obj1: [String] = ["asd", "jkl"]
let obj2: [String] = [obj1[0], obj1[1]]
obj2.remove(at: 0)
```
then obj1 should still have the 2 texts while obj2 only will have the jkl text.

ah, i just see your new comment...

You have to be aware that these are classes with references. So if you have an object with an array and you assign that object to a 2nd variable, then the reference to the array will be the same. When removing from the 1st array it will also be removed from the 2nd array. You could solve this by creating a copy of the objects instead of directly assigning them. You could use the technique that I put in my first answer to this question.

**Comment by Pinank** [comment]
Hmm ok let me try with that

**Comment by Pinank** [comment]
Yes Working

Thanks @evermeer
