### ISSUE TITLE
Keywords when converting to jsonString

### ISSUE THREAD

**Issue by tghsoftdev** [evermeer/EVReflection#157]
I have a class with an attribute called "description", since description is a keyword I'm using _description for mapping it, but when I  convert it into jsonString the attribute is named "_description" instead of "description". Is there any way to do it?

**Comment by evermeer** [comment]
You could add a property mapping by implementing the following function in your object:
```
    override func propertyMapping() -> [(String?, String?)] {
        return [("_description", "description")]
    }
```

I'm wondering if there should be an automatic conversion for properties that start with an underscore. It would not be hard to implement. But then if you do want an underscore in the json then you need the propertyMapping function again. I think it comes down to what situation would happen most.
