### ISSUE TITLE
toDictionary() or toJson() with only selected keys?

### ISSUE THREAD

**Issue by superarts** [evermeer/EVReflection#158]
Sorry for the noob question, is there a way to convert `EVObject` `toDictionary()` or `toJson()` with only selected keys? For example:

class Person {
  var email: String?
  var name: String?
}

// can I call Person().toDictionary(keys: ["email"]) and get ["email": "a@b.com"] please?

**Comment by evermeer** [comment]
Hi, it's OK, 
You could achieve this by implementing the function:

```
override internal func propertyMapping() -> [(String?, String?)] {
        return [("name", nil)]
    }
```
That function can be used for custom property mapping. In the sample above the name field from the object will be mapped to nothing in the json. You can add as much fields as you like. You could also make that array dynamic based on some setting.

**Comment by superarts** [comment]
Thanks! I added my own `toDictionary` with a whitelist based on your hint, so that by calling `myObject.toDictionary(keys: ["email"])` I'll be able to retrieve only emails. This is useful when I only want to submit a limited portion of the object to server, like when I'm updating a person's email address.

```
class ABEntity: EVObject {
    private var _whitelist: [String]?
    func toDictionary(keys: [String]) -> NSDictionary {
		_whitelist = keys
		let dict = toDictionary()
		_whitelist = nil
		return dict
	}
	override internal func propertyMapping() -> [(String?, String?)] {
		if let whitelist = _whitelist {
			var keys = [(String?, String?)]()
			var mirror: Mirror? = Mirror(reflecting: self)
			while mirror != nil {
				for property in mirror!.children {
					if let key = property.label, !whitelist.contains(key) {
						keys.append((key, nil))
					}
				}
				mirror = mirror!.superclassMirror
			}
			return keys
		}
		return [("", nil)]
    }
}
```

**Comment by superarts** [comment]
Thanks for help!

**Comment by superarts** [comment]
To whoever that comes to this topic: recently I've switched from `AlamofireJsonToObjects` to `EVReflection/Alamofire`, and there's a weird issue with `Swift 3` / `Xcode 8`:

This line gives me `segmentation fault ` from Swift compiler: `override open func propertyMapping() -> [(String?, String?)]`

To fix just change it to: `override open func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)]`

**Comment by evermeer** [comment]
Thanks @superarts, that's indeed a change implemented in a recent release of EVReflection.  Since AlamofirJsonToObjects has a dependency to EVReflection you would also have got that issue there. I knew it was a breaking change, but still wanted to implement it. The code will now look a lot more readable, especially when there are a lot of mappings. See the sample below. Besides the propertyMapping function also the propertyConverters() function has changed in the same way. 

If you have an idea how to better communicate these kind of changes to the users, then please let me know.

```
    override public func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
        return [(keyInObject: "internalIban", keyInResource: "internal"),
                (keyInObject: "externalIban", keyInResource: "external")]
    }

    override public func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [(key: "imageData",
                 decodeConverter: { value in
                    // NA
                }, encodeConverter: {
                    var array: [NSDictionary] = []
                    for element in self.imageData ?? [] {
                        var result = NSMutableDictionary()
                        result["content"] = element
                        array.append(result)
                    }
                    return array
                })]
    }
```
