### ISSUE TITLE
Nested evobject fails to deserialize - App name contains a dot

### ISSUE THREAD

**Issue by icbmike** [evermeer/EVReflection#159]
I have two class like this: 
```
import EVReflection

class DocumentDetails : EVObject{
    var reference = ""
    var documentContent = ""
    var documentAttachmentLinks : [DocumentAttachmentLink]? = []
}

class DocumentAttachmentLink : EVObject {
    var attachmentId = ""
    var fileName = ""
    var dateCreated = ""
}
```

Whenever I try to create an instance of DocumentDetails it fails to deserialize the documentAttachmentLinks with the following error: 

```
ERROR: Could not create an instance for type DocumentAttachmentLink
dict:{
    AttachmentId = 340cfe14bfa14531ad7e781566be9d8f;
    DateCreated = "2017-02-10T14:29:22.4831934+13:00";
    DateDownloaded = "2017-02-13T00:54:35.9319384+00:00";
    DocumentId = 1067783;
    FileName = "1_UblPreview.pdf";
    Id = 5;
}
```

I've tried stepping through the EVReflection code but can't figure out what I'm doing wrong.

**Comment by icbmike** [comment]
I don't know how you would get to that particular error, but maybe a reason why an instance couldn't be created would be great.

**Comment by evermeer** [comment]
Could it be that your data objects are in a different framework than where you run the deserialisation from? If so, then you can tell EVReflection to also include that framework. Just add the following line anywhere in your code as long as it is executed before you start deserialising:

        EVReflection.setBundleIdentifier(DocumentDetails.self)

**Comment by icbmike** [comment]
It's the same framework unfortunately

**Comment by evermeer** [comment]
Could it be that you use special characters in your bundle name? 
Currently I do filter some of these out like: ` -&%#@!$^*()<>?.,:;`
It could be that I am missing a character there.
Could you still try adding this line to see if it helps:
`EVReflection.setBundleIdentifier(DocumentDetails.self)`

**Comment by icbmike** [comment]
I added that line before the call to the initializer and before the key line in my test case, no luck

**Comment by evermeer** [comment]
The error `ERROR: Could not create an instance for type` is on line 1206 of EVReflection.swift
You will only get there is the swiftClassFromString at line 1189 dit not return a class.
There it will go to line 595 and execute a NSClassFromString(className) I assume that className is "DocumentAttachmentLink". Could you set a breakpoint there and see if that's the case? And if it's not, could you also tell me what the appName and aBundle variables in the lines below that are?

**Comment by icbmike** [comment]
once I started calling `setBundleIdentifiers` rather than `setBundleIdentifier`, I got `aBundle` as 'dx2' and `className` as `Swift.Array<DocumentAttachmentLink>`

`getCleanAppName()` returns 'dx2' as well, which is unsurprising.

**Comment by evermeer** [comment]
Thanks for your patience...

So far I'm not able to figure out why this is failing in your case. 
As you can see half way in this unit test:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionTests.swift#L380
It should not be a problem that you have an optional array of other objects.

Could you send me the json where you have the problem with? Then I will create a unit test for this to see if I can replicate your problem.

**Comment by icbmike** [comment]
```
{
    "GroupId": 1067820,
    "Reference": "imageAttachment",
    "SentDate": "2017-02-14T13:58:39.8130000",
    "DocumentTypeName": "fasdsad",
    "TradingPartnerName": "Timocratic Peoples Republic of the North Island",
    "Direction": "Send",
    "Status": "Complete",
    "HasDownloadableDocuments": true,
    "HasUndownloadedDocuments": false,
    "GroupedDocuments": [
        {
            "Id": 1067820,
            "Reference": "imageAttachment",
            "DocumentTypeName": "fasdsads",
            "Status": "FileSplitted",
            "InternalDocumentType": "Sender",
            "Label": "asddagasd",
            "IsLongtail": true,
            "Success": false,
            "StatusCode": 0
        },
        {
            "Id": 1067821,
            "Reference": "imageAttachment",
            "DocumentTypeName": "Invoice",
            "Status": "asdasdgfasd",
            "InternalDocumentType": "asdadgfF",
            "Label": "TRAA TTT",
            "IsLongtail": false,
            "Success": false,
            "StatusCode": 0
        }
    ],
    "DocumentAttachmentLinks": [
        {
            "Id": 20,
            "DocumentId": 1067820,
            "FileName": "Screen Shot 2016-04-05 at 2.08.47 pm.png",
            "AttachmentId": "8d95da0ef14942da9375f872ba7c1714",
            "DateCreated": "2017-02-14T13:58:39.9056956+13:00",
            "DateDownloaded": "2017-02-14T01:01:57.5855438+00:00"
        },
        {
            "Id": 21,
            "DocumentId": 1067822,
            "FileName": "imageAttachment_Preview.pdf",
            "AttachmentId": "ce861c30662f450588e4466a01b8519e",
            "DateCreated": "2017-02-14T13:59:02.6122139+13:00",
            "DateDownloaded": "0001-01-01T00:00:00.0000000+00:00"
        }
    ],
    "Success": true,
    "Message": "OK",
    "StatusCode": 200
}
```

**Comment by evermeer** [comment]
I added a unit test for this. I completed the object (added the missing fields)
You can find the test here:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionIssue159.swift#L31
It runs without any warnings.
I still have no idea why it fails in your case.

**Comment by icbmike** [comment]
I'll recreate that test specifically and see what the difference is to my actual usage.

Off the top of my head, my source files are in a separate folder rather than just a group, I don't know if that affects namespacing.

**Comment by evermeer** [comment]
Dat does not influence anything. It could only be an issue If you define classes inside other clases. But that should also be OK to use.

**Comment by icbmike** [comment]
I think I've found the issue.

I stepped through `swiftClassTypeFromString` again and found that getCleanAppName()/aBundle returns "dx2" or "dx2Tests".

Then `NSClassFromString("\(appName).\(className)")` returns nil for DocumentAttachmentLink.

If I manually evaluate `NSClassFromString("nz_co_olympic_dx2Tests.DocumentAttachmentLink")` it returns a non nil value.

I think I'm just a pleb and haven't named my app properly

![image](https://cloud.githubusercontent.com/assets/1059311/22962999/46939cfc-f3b5-11e6-96cb-96c6c74e8fc9.png)

**Comment by evermeer** [comment]
Ah! I now think I know what the problem is. See the function below that is used for getting the name for the bundle. It first does a split on the dot and then replaces the illegal characters. The dot is an illegal character. But since it's already split, you won't have any illegal characters and you get only the dx2 instead of the complete name.

As you can see from your bundle identifier, there it would be ok to split for the dot and take the last part because it already has dashes in the name instead of dots. So now I'm wondering if the split function should only be inside the if where the appName is set from the bundleIdentifier. I think that would have solved your issue. But then... Someone also could have added the dot syntax inside the kCFBundleNameKey.

I will dive into the issue some more and try to figure out what would be the best solution that works in all situations. 

```
    fileprivate static func nameForBundle(_ bundle: Bundle) -> String {
        // get the bundle name from what is set in the infoDictionary
        var appName = bundle.infoDictionary?[kCFBundleNameKey as String] as? String ?? ""
        
        // If it was not set, then use the bundleIdentifier (which is the same as kCFBundleIdentifierKey)
        if appName == "" {
            appName = bundle.bundleIdentifier ?? ""
        }
        appName = appName.characters.split(whereSeparator: {$0 == "."}).map({ String($0) }).last ?? ""
        
        // Clean up special characters
        return appName.components(separatedBy: illegalCharacterSet).joined(separator: "_")
    }
```

**Comment by icbmike** [comment]
I'm surprised that other people haven't run into this issue (I assume).

Have I not named my application in a conventional way?

**Comment by evermeer** [comment]
I was able to fix this issue. 
I tested this by changing the target UnitTestsOSX to UnitTest.OSX With the old code there where tests failing, with the new code they succeeded.

**Comment by JayeshMardiya** [comment]
I have same issue, not identify
