### ISSUE TITLE
Support for array of dictionaries

### ISSUE THREAD

**Issue by krisanthony** [evermeer/EVReflection#162]
Hey great work here, really this is amazing.

I've come across a scenario where I'm needing to serialize an array of dictionaries e.g. `[{"key": value, ...}]` into an object with an array of objects. 

Not supported yet so as a quick fix I created an object with an array and mapped the property to `""`, e.g.:

```
class ObjectArray: EVNetworkingObject {
    var objects: [Object] = []

    override func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
        return [("objects", "")]
    }
}
```

And modified the `EVReflectionSerializer` to support arrays of dictionaries:

```
else if let array = result.value as? NSArray {
    JSONToMap = NSDictionary.init(dictionary: ["": array])
}
```
see [here](https://github.com/krisanthony/EVReflection/blob/master/Source/Alamofire/DataRequest%2BEVReflectable.swift)

I'm sure there is a more elegant solution to be thought up but this is working for now. I know there is the `responseArray:` method, but I'd like to have an object wrapping the array as above. I'd be interested in your thoughts.

**Comment by evermeer** [comment]
There is already an array initialiser for that. You can just call:

```
let myDictArray: [NSDictionary] = getYourDataFunction()
let objects: [Object] = [Object](dictionaryArray: myDictArray)
```

**Comment by evermeer** [comment]
I think i misunderstood. You want the array as a property in an other object.
Shouldn't you just do that after you get the response? 
Your server is returning an array of objects, so the result of the call should also be an array of objects.
So just get the `responeArray` and after that create you ObjectArray object and assign the results to the objects property.

**Comment by krisanthony** [comment]
Right yeah I could do that. I liked having it done automatically in `responseObject`. Perhaps it is just a preference. Is there any reason to not do it the way I proposed? Some case I am not considering?

**Comment by evermeer** [comment]
I think your solution has to sink in a little. Since the code is inside the normal response object, it could be a valid solution. So if you are asking for an object, but you get an array, then do the conversion. The conversion to a property with the name "" is actually smart. Because that will never happen with an actual result.

**Comment by krisanthony** [comment]
Right that is my thinking as well.

**Comment by evermeer** [comment]
Now I think of it I could do the same the other way around. When asking for the responseArray and an object is returned, then that object could be placed inside an array. Let me do some more thinking about this.

**Comment by evermeer** [comment]
I also added the same solution to the Moya response extension. It seems to work. I will add some more unit tests for it tomorrow and then publish a new version.

**Comment by evermeer** [comment]
This has now been added to version 4.3.3
