### ISSUE TITLE
NSDictionary inside custom object

### ISSUE THREAD

**Issue by kerem1905** [evermeer/EVReflection#163]
I want to use NSDictionary type inside custom object.  But conversion fails on 

 if useType != "Struct" {
            (original as? EVReflectable)?.addStatusMessage(.InvalidClass, message: "Could not create an instance for type \(type)\ndict:\(dict)")
            print("ERROR: Could not create an instance for type \(useType)\ndict:\(dict)")
        }

Whats should I do ? I read documentation but I didn't find anything about this.

My code looks like :
```
class CustomModel: EVObject {
    var variable1: NSNumber = NSNumber(value: false) // works fine
    var variable2: NSDictionary? // doesnt work
}
```

**Comment by evermeer** [comment]
strange, should work... See for instance User145b in testIssue145 in EVReflectionIssue145.swift. What's exactly in the output? It should print out the dictionary.

**Comment by evermeer** [comment]
Do you still have an issue with this?

**Comment by kerem1905** [comment]
No it was my bad. Thanks

**Comment by evermeer** [comment]
No problem 😃
