### ISSUE TITLE
Non-optional values and error handling

### ISSUE THREAD

**Issue by szantogab** [evermeer/EVReflection#165]
Hi!

Is there any way in this library to have a model class containing properties, that are of non-optional type? Like this:

```
class User: EVObject {
 var firstName: String!
 var lastName: String!
}
```

What I would like to achieve, is basically to validate the JSON so that if a user's firstName or lastName property is nil, then make the library throw an exception, which I can catch and present an error to the user.

Is this possible? It would be awesome :)

Thanks.

**Comment by evermeer** [comment]
I have an other mechanism for that. The initValidation function is meant to handle this sort of validation.

    open override func initValidation(_ dict: NSDictionary) {
        self.initMayNotContainKeys(["error"], dict: dict)
        self.initMustContainKeys(["requiredKey1", "requiredKey2", "requiredKey3"], dict: dict)
        if dict.value(forKey: "requiredKey1") as? String == dict.value(forKey: "optionalKey1") as? String {
            // this could also be called in your property specific validators
            self.addStatusMessage(.Custom, message: "optionalKey1 should not be the same as requiredKey1")
        }
    }

DeserializationStatus is an OptionSet. You could have multiple status messages for one serialisation. You can get the combined status by using .evReflectionStatus(). You could compare if this is not equeal with .none. If you want the individual statusses, then you can loop through test.evReflectionStatuses.

**Comment by evermeer** [comment]
If you have any other questions, then please let me know.
