### ISSUE TITLE
toJsonData() propertyConverters() enums

### ISSUE THREAD

**Issue by krisanthony** [evermeer/EVReflection#168]
Having an issue where I am propertyConverter. I have an enum, which I am using property converter to return the raw value and converting raw value to enum in the decoder.

    override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [
            (
                "requestType",
                { return self.requestType = ChatRequestType($0 as! String) },
                { return self.requestType.rawValue }
            )
        ]
    }
However on encoding, here is the JSON:

`requestType = realtime`

should be

`requestType = "realtime"`

Am I doing something wrong here?

**Comment by evermeer** [comment]
Enums should be handled by adding the EVRaw protocol to it and then implementing the function:

```
override func setValue(_ value: Any!, forUndefinedKey key: String) {
        switch key {
        case "requestType":
            if let rawValue = value as? Int {
                if let status =  ChatRequestType(rawValue: rawValue) {
                    self. requestType = status
                }
            }
       default:
          print("Unhandled \(key)")
    }
```

Do you mean that you get:
`{ 'requestType': realtime}`
instead of:
`{ 'requestType': 'realtime'}`

**Comment by krisanthony** [comment]
Yes exactly I get `realtime` instead of `"realtime"` but I am thinking maybe that is just how console prints it out. I think it is working fine with property converters any reason to use the EVRaw protocol over that?

**Comment by evermeer** [comment]
True, the property converters also work for this. 

You should use EVRaw when your enum raw value is different than you variable name. But then still you could use property converters. 

```
enum test: String {
   case one = "Number One"
  case two = "The second"
}
```

When you add EVRaw then EVReflection is able to get to the string value and use that.

**Comment by krisanthony** [comment]
That makes sense. Property converter works for what I was doing, actually
the problem I was having was unrelated to my property converter after
debugging a little further. So the issue can be closed. Thanks for the
quick response!
