### ISSUE TITLE
Generic dictionary parsing

### ISSUE THREAD

**Issue by szantogab** [evermeer/EVReflection#170]
Hi again :)

I would like to deserialize a data structure that contains a generic Swift dictionary:

```
class RatingDetail: BaseModel {
    var answers: [String: Answer]?
....
}

class Answer: BaseModel {
    var explanation: String?
    var rating: Rating? = .neutral
}

I get an error message for this code during deserialization:
ERROR: Could not create an instance for type Swift.Dictionary<_TtCC5Swift20String, SmartiMarket6Answer>
dict:{
    13 =     {
        explanation = "<null>";
        rating = 2;
    };
```

Is it possible to deserialize this somehow?

**Comment by Minthos** [comment]
Rating is an enum, enums need a workaround. Maybe that's the problem.

**Comment by szantogab** [comment]
The whole Answer class looks like this, so it handles the enum.
```
class Answer: BaseModel {
    var explanation: String?
    var rating: Rating? = .neutral

    override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [
            ( "rating", { self.rating = Rating.init(rawValue: Int($0 as! String) ?? 0) }, { return self.rating?.rawValue })
        ]
    }
}

```

**Comment by evermeer** [comment]
Hmm... this is a new one for me. 
When you have the dictionary as a non optional like this, then it might work (have to test it)
`var answers: [String: Answer] = [:]`
Because then there is no need to create an instance because it's already there.
If you do want to make it an optional, then you have to use a propertyConverters function to create it.
I will hava a look to see if there is a way to instantiate it anyway.

**Comment by evermeer** [comment]
Ah, I was wrong... I did test this. See:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionWorkaroundsTests.swift#L135
instead of the 'setValue forUndefinedKey' function you could also use the propertyConverters function to do the same thing.

**Comment by szantogab** [comment]
Awesome, it works now, thank you!
