### ISSUE TITLE
How convert a EVObject to [String: AnyObject] ?

### ISSUE THREAD

**Issue by fukhaos** [evermeer/EVReflection#171]
I want to pass a USER as parameter to Almofire in a POST Request:

![captura de tela 2017-03-16 as 12 26 03](https://cloud.githubusercontent.com/assets/1226155/24004018/eb2f02de-0a43-11e7-89db-1f8e6f3ccc32.png)

Thanks

**Comment by fukhaos** [comment]
this code works !
was my fault.

**Comment by evermeer** [comment]
No problem
