### ISSUE TITLE
RealmObject and EVObject

### ISSUE THREAD

**Issue by ahmedAlmasri** [evermeer/EVReflection#172]
Hello ,, 

EVObject not support polymorphism 
How can I use non-inheritable
thank you

**Comment by evermeer** [comment]
Hi, 

All functionality will be availing by extending the Realm Object with the EVReflectable protocol. The only thing you need to do to make it available in all your realm objects is:

```
extension Object: EVReflectable {}
```

Hmm.. I just found out that I forgot the base implementation for the costomConverter function. For now you need to use the extension below. I will fix this later today.

```
extension Object: EVReflectable {
    public func customConverter() -> AnyObject? {
        return nil
    }
}
```

You do have to be aware that if this is the only thing you do, that you are missing a couple of EVObject specific features. See the functions that are in the EVObject. For instance the main issue will be:
If you syncronise json which contains keys that are not in your object model, then an error will be thrown. If you want to fix that, then you should include the 'setValue forUndefinedKey' function in the extension.

**Comment by ahmedAlmasri** [comment]
thank you  , it's working

**Comment by evermeer** [comment]
The update described above is now pushed to GitHub as version 4.5.1. The Cocoapods publish is now running (can take up to 20 minutes) 

To prevent it in the future I added an extra test so that it's enforced that you can extend with EVReflectable without the need to implement a function.
see: https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionExtendingNSObjects.swift

**Comment by ahmedAlmasri** [comment]
hello 

realm data type List<MyObject> or realm array "RLMArray"

not parsing

**Comment by evermeer** [comment]
I just pushed a Realm unit test to GitHub. It's not yet a new version. I'm still looking if I can improve the code.
https://github.com/evermeer/EVReflection/blob/master/UnitTests/RealmTests/RealmTests.swift#L32

**Comment by evermeer** [comment]
... getting close... Will probably finalise this tomorrow.

**Comment by evermeer** [comment]
I just pushed version 4.8.0 to GitHub. The CocoaPod will be published in about 20 minutes

You do have to be aware that you need the following extension in your code:

```
extension List : EVCustomReflectable {
    public func constructWith(value: Any?) {
        if let array = value as? [NSDictionary] {
            self.removeAll()
            for dict in array {
                if let element: T = EVReflection.fromDictionary(dict, anyobjectTypeString: _rlmArray.objectClassName) as? T {
                    self.append(element)
                }
            }
        }
    }
    public func toCodableValue() -> Any {
        return self.enumerated().map { ($0.element as? EVReflectable)?.toDictionary() ?? NSDictionary() }
    }
}
```

I thought about making a CocoaPods subspec for this but I'm not sure if that is what users wish (it's so small). What do you think?

**Comment by carlosjac** [comment]
Hi, 
including extension List : EVCustomReflectable, I get these errors

Initializer for conditional binding must have Optional type, not '<<error type>>'
Use of undeclared type 'T'

Using Swift3 and EVReflection 4.19.0

Any idea?

**Comment by evermeer** [comment]
@carlosjac That release is almost a year old. Can't you update to Swift4 and use the latest version. There are quite some bug fixes since then.

Could you show some lines of code where you have these errors?
