### ISSUE TITLE
Converto to Bool

### ISSUE THREAD

**Issue by bhnicoletti** [evermeer/EVReflection#173]
I recevied from web service:
`"adicional":false`

and i have in class :
`var adicional:Bool!`

but this value is not convert to boolean in swift, this is bug of framework or fail of my code?

`WARNING: The class 'Ingrediente' is not key value coding-compliant for the key 'adicional'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information`

**Comment by evermeer** [comment]
There are a couple of types where a workaround is needed. One of these is an optional Bool. Since you user an exclamation mark, the easiest solution would be to just make it a bool and assign a default value. If you dont want that, then you should use the `setValue forUndefinedKey` function. See the workaround unit tests for more information

**Comment by bhnicoletti** [comment]
thanks! it's works.

**Comment by bj97301** [comment]
Setting a default value has unintended side effects for me.  It would be nice to have an easy conversion of Bool to Bool?

**Comment by evermeer** [comment]
@bj97301 The core of EVReflectin is the use of Mirror to read value from objects and `setValue forKey` for setting property values. Unfortunately the `setValue forKey` function has some limitations (see readme). As stated above the only workaround is to implement the `setValue forUndefinedKey` function. Here is some sample code:

```
class TestObject3: EVObject {
    var adicional: Bool!
    
    override func setValue(_ value: Any!, forUndefinedKey key: String) {
        switch key {
        case "adicional":
            nullableType = value as? Bool
        default:
            NSLog("WARNING: setValue for key '\(key)' should be handled.")
        }
    }
}
```
