### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by Minthos** [evermeer/EVReflection#174]
While testing serializing/deserializing objects in multiple threads (different objects of course) I discovered some thread safety issues in my own code (the first and most obvious was the global variable I used in my enum workaround but there were a few others).

I stumbled upon a potential issue in EVReflection as well.

```
    static var properiesCache = NSMutableDictionary()
    static var typesCache = NSMutableDictionary()
```

These two are being read and written by this function:

```/**
     Convert an object to a dictionary while cleaning up the keys
     
     - parameter theObject: The object that will be converted to a dictionary
     - parameter conversionOptions: Option set for the various conversion options.
     
     - returns: The dictionary that is created from theObject plus a dictionary of propery types.
     */
    public class func toDictionary(_ theObject: NSObject, conversionOptions: ConversionOptions = .DefaultSerialize, isCachable: Bool = false, parents: [NSObject] = []) -> (NSDictionary, NSDictionary) {
```

I don't think my code calls that function but I figured I should bring it to your attention. Maybe protect those two dicts with an NSLock or something.

**Comment by evermeer** [comment]
Thanks for mentioning this. I think you are right. I will try to implement this improvement soon.

**Comment by evermeer** [comment]
I have just pushed version 4.6.0 to GitHub with a fix for this. Cocoapods publish is now running (will take 20 minutes)
