### ISSUE TITLE
Xcode 8.3 warnings

### ISSUE THREAD

**Issue by jabez1314** [evermeer/EVReflection#176]
Xcode 8.3 warnings

**Comment by jkgwak** [comment]
Xcode 8.3 warnings

**Comment by SamuraiJack76** [comment]
![datarequest_evreflectable_swift2](https://cloud.githubusercontent.com/assets/13968660/24403605/ebae4958-13bd-11e7-8f59-3cafbaf60dfd.png)
![datarequest_evreflectable_swift](https://cloud.githubusercontent.com/assets/13968660/24403606/ebae7ae0-13bd-11e7-9e82-d095d0fae627.png)

**Comment by evermeer** [comment]
Downloading XCode 8.3 .....

**Comment by evermeer** [comment]
This has been pushed as version 4.7.0
