### ISSUE TITLE
EVReflection + Realm's List<MyClass> throwing exception

### ISSUE THREAD

**Issue by daerimin** [evermeer/EVReflection#178]
Hi,

I am very new to Swift so I apologize for my lack of understanding.  

I have several custom classes which include each other in various ways.  The problem I'm having is this:

Class "Event" is an "Object", being stored in Realm - and has a property "Users" which is of type `List<User>`.  User is another custom class under Realm.  When getting event data from the server, the JSON may include users, or it may give a blank array, indicating that there are no users for this event.  When I try and run:

`let event = Event(dictionary: dict)`

I get this:

> Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '(
)' for property 'id''

I fear that nested objects may be responsible for this, but the raw JSON coming from the server does not include this string, so I cannot tell where it's coming from.  If I use propertyMapper to exclude "Users" from the Event, no exception occurs.

I realize this may not be enough to go on, so please let me know what else I can provide to make this more clear.  Any assistance would be appreciated.

Thanks!

**Comment by Minthos** [comment]
https://github.com/evermeer/EVReflection#known-issues

EVReflection does not work with generic types. List<User> is a generic type. Array<User> should work though. Can you convert it from a list to an array?

**Comment by evermeer** [comment]
At this moment I am trying to create a good solution for the Realm List problem.
I have added Realm unit tests to EVReflection.
I hope to have a solution for this later today.

**Comment by evermeer** [comment]
I just pushed the Realm unit test to GitHub. It's not yet a new version. I'm still looking if I can improve the code.
https://github.com/evermeer/EVReflection/blob/master/UnitTests/RealmTests/RealmTests.swift#L32

**Comment by evermeer** [comment]
... getting close... Will probably finalise this tomorrow.

**Comment by daerimin** [comment]
Thank you very much for your efforts.   I greatly appreciate it.

**Comment by evermeer** [comment]
I just pushed version 4.8.0 to GitHub. The CocoaPod will be published in about 20 minutes

You do have to be aware that you need the following extension in your code:

```
extension List : EVCustomReflectable {
    public func constructWith(value: Any?) {
        if let array = value as? [NSDictionary] {
            self.removeAll()
            for dict in array {
                if let element: T = EVReflection.fromDictionary(dict, anyobjectTypeString: _rlmArray.objectClassName) as? T {
                    self.append(element)
                }
            }
        }
    }
    public func toCodableValue() -> Any {
        return self.enumerated().map { ($0.element as? EVReflectable)?.toDictionary() ?? NSDictionary() }
    }
}
```

I thought about making a CocoaPods subspec for this but I'm not sure if that is what users wish (it's so small). What do you think?

**Comment by daerimin** [comment]
It looks like it's solved!  Can't tell you how much I appreciate it!

Regarding the subspec, if I were you I would simply include that snipped in your docs.  I found your library because it mentions Realm, and I searched for "Swift 3 Realm JSON decode" or something like that - so if you put that snippet in there, should be enough for most people I'd think.  :)
