### ISSUE TITLE
Correct "What to do when you use object inheritance" in documentation.

### ISSUE THREAD

**Issue by noobs2ninjas** [evermeer/EVReflection#179]
Documentation example show this. 

```
override func getSpecificType(dict: NSDictionary) -> EVObject {
        if dict["justBar"] != nil {
            return Bar()
        } else if dict["justBaz"] != nil {
            return Baz()
        }
        return self
    }
```

However looking through the source it seems that the only function called getSpecificType returns a EVReflectable

```
open func getSpecificType(_ dict: NSDictionary) -> EVReflectable? {
        return nil
   }
```

So Im getting 

> Method does not override any method from its superclass.

**Comment by evermeer** [comment]
Thanks for mentioning this. I have updated the documentation. You can find sample code here:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVRelfectionInheritanceTests.swift#L83

**Comment by noobs2ninjas** [comment]
Awesome!
