### ISSUE TITLE
 'CKRecordID' is only available on iOS 8.0 or newer

### ISSUE THREAD

**Issue by HelloPig** [evermeer/EVReflection#18]
EVReflection.swift:373:35: 'CKRecordID' is only available on iOS 8.0 or newer
![image](https://cloud.githubusercontent.com/assets/14272771/9942734/50e67190-5daf-11e5-9a1a-8e5c745cee83.png)

**Comment by evermeer** [comment]
Ah... that's a remains of the time when EVReflection was part of EVCloudKitDao. I was able to remove the CloudKit dependency. I will create a new release in a moment.

**Comment by evermeer** [comment]
It's released as version 2.7.7
