### ISSUE TITLE
Is this easiest way to do property converters when subclassing? 

### ISSUE THREAD

**Issue by noobs2ninjas** [evermeer/EVReflection#181]
Seems like theres got to be an easier way to do this. 

The problem is that by subclassing and overriding propertyConverters on the subclass, no superclasses property converters are included from the superclass. 

Heres the only thing I could think to do in order to include the super classes property converters.

```
override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        var converters = [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))]()
        
        converters.append(contentsOf: super.propertyConverters())
        return converters
}
```

Im assuming that using override getSpecificType() doesn't automatically run the superclasses propertyConverters() first? If so, I think it would be helpful to note that in documentation.

**Comment by evermeer** [comment]
That is indeed the way to go. You could make it a little shorter by merging the 3 lines of code like this:

```
open class TestObject6: EVObject {
    var isGreat: Bool = false
    
    override open func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [( 
                key: "isGreat",
                decodeConverter: { self.isGreat = ($0 as? String == "Sure") },
                encodeConverter: { return self.isGreat ? "Sure": "Nah"})]
    }
}

open class TestObject6child: EVObject {
    var seconOverride: String?
    override open func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [( 
            key: "seconOverride",
            decodeConverter: { self.seconOverride = $0 as? String ?? "") },
            encodeConverter: { return self.seconOverride })].append(contentsOf: super.propertyConverters())
    }
}

```

**Comment by noobs2ninjas** [comment]
Nice! I like it. I definitely think a good idea in the future would be that when EVReflection sees that something other than the current class is being returned by getSpecificType() , propertyConverters() is automatically ran from the super class prior to interacting with the returned class. That or documentation would be easier I guess lol.
