### ISSUE TITLE
Support Swift Package Manager?

### ISSUE THREAD

**Issue by ejmartin504** [evermeer/EVReflection#187]
Are there any plans to support Swift PM for this library?

**Comment by evermeer** [comment]
I have never worked with SPM. It would be nice if it was supported. Maybe someone has an idea what steps I should take to support SPM.

**Comment by kdawgwilk** [comment]
This would only be useful if there are no dependencies on Objective-C or iOS specific frameworks so that it can be used with Server Side Swift running on Linux

**Comment by ejmartin504** [comment]
Foundation should be usable in Linux environments at this point no? Otherwise there don't seem to be any other dependencies that make it unusable in Linux

**Comment by evermeer** [comment]
EVReflection is roughly based on 2 things:

- The Mirror object for getting information from your objects (used when creating a dictionary or json from your objects. This one works in almost any situation. There are only workarounds needed when using enums. See the readme for more info.
- the 'setValue forKey' function for setting values on objects. This function comes from Objective C. This is also the reason why objects need to have NSObject as it's base class (Which is the base of EVObject) Unfortunately there is a list of property types where this function cannot be used for. The most annoying ones are types like optional int 'Int?' but also pure swift dictionaries like [String: String]. Fortunately NSMutableDictionary is available as a workaround for this. See the readme or the workaround unit test to see all situations where a workaround like this is needed.

So for the second part there is a dependency to a Objective-C specific framework (Foundation)

**Comment by kdawgwilk** [comment]
I have a fork that supports SPM here: [kdawgwilk/EVReflection](https://github.com/kdawgwilk/EVReflection) just wanted to mess around with it
