### ISSUE TITLE
Can't parse to Dictionary

### ISSUE THREAD

**Issue by peterdk** [evermeer/EVReflection#188]
I tried to initalize the following object:

```
var country: String = ""
var translations:[String:String] = [:]
```
With this json:
```
{
  "country":"NL",
  "translations": {
       "key":"value"
      "key2": "value2"
  }
}
```

It says

`The class 'classname' is not key value coding-compliant for the key 'translations'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information`

I tried to use NSMutableDictionary, and that worked:
```
var translations: NSMutableDictionary = NSMutableDictionary()
```
Is this a bug? Or am I supposed to not use Swift types?

Great library by the way. It's awesome.

**Comment by evermeer** [comment]
EVReflection is roughly based on 2 things:
- The Mirror object for getting information from your objects (used when creating a dictionary or json from your objects. This one works in almost any situation. There are only workarounds needed when using enums. See the readme for more info.
- the 'setValue forKey' function for setting values on objects. This function comes from Objective C. This is also the reason why objects need to have NSObject as it's base class (Which is the base of EVObject) Unfortunately there is a list of property types where this function cannot be used for. The most annoying ones are types like optional int 'Int?' but also pure swift dictionaries like [String: String]. Fortunately NSMutableDictionary is available as a workaround for this. See the readme or the workaround unit test to see all situations where a workaround like this is needed.

**Comment by peterdk** [comment]
Ok, interesting. Too bad that Swift doesn't allow to set property values then outside of setValue forKey using NSObject.
