### ISSUE TITLE
'EVObject' has been explicitly marked unavailable here

### ISSUE THREAD

**Issue by ttsik** [evermeer/EVReflection#191]
Hi guys, I having a similar issue when building for release. when I build for debug everything works as expected.

I am using Xcode 8.3.

The exact error I am getting is
'EVObject' is unavailable: cannot find Swift declaration for this class
'EVObject' has been explicitly marked unavailable here

My code looks like this
class SynchronizableEntity: EVObject {
    
    required init(){

    //......
    //......
    //......
        
        super.init()
    }

Thanks a lot in advance for the help

BTW I already checked the https://github.com/evermeer/EVReflection/issues/67 but as the issue was closed I had to open a new one

**Comment by evermeer** [comment]
Strange, I'm not able to replicate this issue...

Do you also have that issue of you create a new project, copy your SynchronizalbeEntity object in it and then build for release?

**Comment by evermeer** [comment]
Just let me know if you still have issues with this.
