### ISSUE TITLE
using  description 

### ISSUE THREAD

**Issue by ahmedAlmasri** [evermeer/EVReflection#192]
Cannot override with a stored property 'description'

**Comment by evermeer** [comment]
description is a standard property which is always available. There are more similar keywords that can not be used. EVReflection has a mechanism for this. It will automatically add an underscore in front of it. So it will look if you have a property named _description.

The keywords are:

`["self", "description", "class", "deinit", "enum", "extension", "func", "import", "init", "let", "protocol", "static", "struct", "subscript", "typealias", "var", "break", "case", "continue", "default", "do", "else", "fallthrough", "if", "in", "for", "return", "switch", "where", "while", "as", "dynamicType", "is", "new", "super", "Self", "Type", "__COLUMN__", "__FILE__", "__FUNCTION__", "__LINE__", "associativity", "didSet", "get", "infix", "inout", "left", "mutating", "none", "nonmutating", "operator", "override", "postfix", "precedence", "prefix", "right", "set", "unowned", "unowned", "safe", "unowned", "unsafe", "weak", "willSet", "private", "public", "internal", "zone"]`
