### ISSUE TITLE
NSURL conversion issue

### ISSUE THREAD

**Issue by JackYoustra** [evermeer/EVReflection#194]
convertValueForJsonSerialization fails when given an NSURL - no implicit conversion to string supported. Workaround or should fix?

**Comment by evermeer** [comment]
True, there is no reflection support for NSURL. See https://github.com/apple/swift/commit/d1121a3d8608ab609297fa3ba1ce611bd44f09c1

So there would not be an easy fix for this... But I think I could extend it with EVCustomReflectable...

**Comment by JackYoustra** [comment]
This won't work -NSURL is immutable

**Comment by evermeer** [comment]
Ah, but NSURL is part of foundation, so I could just add logic in EVReflection to initiate a NSURL with the right data. I will give that a go.

**Comment by evermeer** [comment]
That seems to be working, will push a new version...

**Comment by evermeer** [comment]
This has been pushed as version 4.12.0
You can find a unit test here: https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/ProfilePhotoUrlListTest.swift#L72
