### ISSUE TITLE
Struct sub EVObjects

### ISSUE THREAD

**Issue by JackYoustra** [evermeer/EVReflection#195]
Hello,
I've got a class structure as follows: EVObject subclass contains EVObject subclass contains Struct contains EVObject subclass. I use the setValue forUndefinedKey workaround for the struct, but the EVObject subclass inside the struct still doesn't work. A custom property converter in the EVObject containing the struct for the EVobject inside the struct isn't called, preventing me from using that. The problem is found somewhere inside the toDictionary function (EVReflection.swift line 147) - the field is null after that.

**Comment by evermeer** [comment]
Hi,

the setValue function is called after EVReflection has tried to clean up
thing. It looks like you should be a step earlier. You can do that using
the propertyConverters. They almost work the same as the setValue function.
You have to implement something like:

    override open func propertyConverters() -> [(key: String,
decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {

        return [( // We want a custom converter for the field isGreat

            key: "seconOverride",

            // isGreat will be true if the json says 'Sure'

            decodeConverter: { self.seconOverride = YourConversion($0) },

            // The json will say 'Sure  if isGreat is true, otherwise it
will say 'Nah'

            encodeConverter: { return self.seconOverride })]

    }

**Comment by JackYoustra** [comment]
propertyConverters don't work on this level, only triggered for upper-level struct. Ended up trying to implement custom JSON at that level, failed, and converted the struct to a class as a workaround.
