### ISSUE TITLE
Swift 2.0 Support

### ISSUE THREAD

**Issue by idelgado** [evermeer/EVReflection#2]
There are a few try/catch refactors needed and removal of redundant superclasses from EVObject.

**Comment by GerdC** [comment]
Most important change for swift 2 in public class func valueForAny:

write: 
            var subtype: String = (split("(mi)".characters) {$0 == "<"} .map{String($0)} [1]).stringByReplacingOccurrencesOfString(">", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
                return (NSNull(), subtype)
            }

because the compiler crashes without this change and you get not error messages in the editor. With this change you get error messages which makes the task less hard.

Gerd

**Comment by evermeer** [comment]
I created a branch named Swift2 and pushed an initial conversion. There is still one bug left to fix.

**Comment by evermeer** [comment]
The Swift 2 version seems to be working now. The unit tests now pass. I will do some more tests later today. If you want to start using this version, then put this line in your pod file:

pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git', :branch => 'Swift2'

**Comment by evermeer** [comment]
Now also successfully tested with https://github.com/evermeer/AlamofireJsonToObjects
Updated the readme
If you find any errors, then please let me know.

**Comment by jpaas** [comment]
In Xcode 7 beta 5, I'm getting these compilation errors using the Swift2 branch...

.../Pods/EVReflection/EVReflection/pod/EVReflection.swift:364:24: 'split(_:maxSplit:allowEmptySlices:isSeparator:)' is unavailable: Use the split() method instead.

.../Pods/EVReflection/EVReflection/pod/EVReflection.swift:403:25: 'split(_:maxSplit:allowEmptySlices:isSeparator:)' is unavailable: Use the split() method instead.

**Comment by evermeer** [comment]
Thanks @jpaas , I'm still on beta 4. I will upgrade to beta 5 this evening and will make the necessary changes.

**Comment by evermeer** [comment]
I just updated the Swift 2.0 branch. It will now only run in Xcode 7 beta 5
