### ISSUE TITLE
Nested Object convert failed

### ISSUE THREAD

**Issue by HelloPig** [evermeer/EVReflection#20]
hi, i'm using the master version with xcode7 & swift2.0, and my objects like this:
class Comment: EVObject {
    var commentid = ""
    var content = ""
    var ctime = ""
    var status = "2"
    var img = ""
    var vote = "0"
    var userinfo : UserInfo?  
}

class UserInfo: EVObject{
    var avatar = ""
    var uid = ""
    var telnum = ""
    var is_seller = "0"
    var sex = "M"
    var name = "TestUser"
    var interest = ""  
}

then i use the code like this

var test =  "[{\"status\":\"0\",\"content\":\"goodjob\",\"ctime\":\"1439986013\",\"img\":\"\",\"userinfo\":{\"avatar\":\"/5602503cc79de.jpg\",\"uid\":\"88ffab2d738393fa467a2e98cad855d9\",\"telnum\":\"18520284321\",\"sex\":\"M\",\"name\":\"\",\"interest\":\"\"},\"commentid\":\"18\", \"vote\" : \"0\"}]"
var comments = EVReflection.arrayFromJson(Comment(), json: test)
print(comments[0].userinfo.uid)

error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).
The process has been returned to the state before expression evaluation.

**Comment by evermeer** [comment]
userInfo is an optional, so when printing it you should check for that. Use something like
        print(comments[0].userinfo?.uid)
One other tip. You can create the array much easier. There is now support for this syntax:
        var comments = [Comment](json: test)
Below you can see a complete unit test that will run and below that you can see the output

```
class EVReflectionTests2: XCTestCase {
    func testTemp() {

        var test = "[{\"status\":\"0\",\"content\":\"goodjob\",\"ctime\":\"1439986013\",\"img\":\"\",\"userinfo\":{\"avatar\":\"/5602503cc79de.jpg\",\"uid\":\"88ffab2d738393fa467a2e98cad855d9\",\"telnum\":\"18520284321\",\"sex\":\"M\",\"name\":\"\",\"interest\":\"\"},\"commentid\":\"18\", \"vote\" : \"0\"}]"
        var comments = EVReflection.arrayFromJson(Comment(), json: test)
        var comments2 = [Comment](json: test)

        print(comments[0].userinfo?.uid)
        print(comments2[0].userinfo?.uid)
    }
}

class Comment: EVObject {
    var commentid = ""
    var content = ""
    var ctime = ""
    var status = "2"
    var img = ""
    var vote = "0"
    var userinfo : UserInfo?

}

class UserInfo: EVObject{
    var avatar = ""
    var uid = ""
    var telnum = ""
    var is_seller = "0"
    var sex = "M"
    var name = "TestUser"
    var interest = ""   
}
```

Test Suite 'Selected tests' started at 2015-09-29 21:48:30.022
Test Suite 'EVReflectionTests' started at 2015-09-29 21:48:30.023
Test Case '-[EVReflection_OSX_Tests.EVReflectionTests testTemp]' started.
Optional("88ffab2d738393fa467a2e98cad855d9")
Optional("88ffab2d738393fa467a2e98cad855d9")
Test Case '-[EVReflection_OSX_Tests.EVReflectionTests testTemp]' passed (0.009 seconds).
Test Suite 'EVReflectionTests' passed at 2015-09-29 21:48:30.033.
     Executed 1 test, with 0 failures (0 unexpected) in 0.009 (0.010) seconds
Test Suite 'Selected tests' passed at 2015-09-29 21:48:30.033.
     Executed 1 test, with 0 failures (0 unexpected) in 0.009 (0.011) seconds
Program ended with exit code: 0

**Comment by HelloPig** [comment]
The code works fine in the TestCase, but when i use some string returned by the HTTP request using AFNetworking, just the same string with the test string, it didn't work and turn out that error.

the code in the callback of AFNetworking like this:

self.comments = EVReflection.arrayFromJson(Comment(), json: commentJson)

po the commentJson:
"[\n  {\n    \"status\" : \"0\",\n    \"content\" : \"Shuru\",\n    \"ctime\" : \"1438250556\",\n    \"img\" : \"\",\n    \"userinfo\" : {\n      \"avatar\" : \"/5602503cc79de.jpg\",\n      \"uid\" : \"d8b81b21c72f1177300247e2d8d88ec5\",\n      \"telnum\" : \"\",\n      \"is_seller\" : \"0\",\n      \"sex\" : \"男\",\n      \"name\" : \"\",\n      \"interest\" : \"\"\n    },\n    \"fabric\" : null,\n    \"commentid\" : \"22\",\n    \"sound\" : \"\",\n    \"vote\" : \"0\",\n    \"is_vote\" : 0,\n    \"seller_card\" : null\n  }\n]"

**Comment by evermeer** [comment]
OK, I did found the bug that was causing the crash. Besides that the variable name for the inner object was wrong. it should be testuserinfo instead of userinfo. If you do want to user userinfo, then have a look at the custom property mapping in the readme. For the bug will push a new version in a moment 

```
class EVReflectionTests2: XCTestCase {
    func testTemp() {

        let test = "[\n {\n \"status\" : \"0\",\n \"content\" : \"Shuru\",\n \"ctime\" : \"1438250556\",\n \"img\" : \"\",\n \"testuserinfo\" : {\n \"avatar\" : \"/5602503cc79de.jpg\",\n \"uid\" : \"d8b81b21c72f1177300247e2d8d88ec5\",\n \"telnum\" : \"18565280137\",\n \"is_seller\" : \"0\",\n \"sex\" : \"男\",\n \"name\" : \"\",\n \"interest\" : \"\"\n },\n \"fabric\" : null,\n \"commentid\" : \"22\",\n \"sound\" : \"\",\n \"vote\" : \"0\",\n \"is_vote\" : 0,\n \"seller_card\" : null\n }\n]"
        print("\(test)")
        var comments = EVReflection.arrayFromJson(Comment(), json: test)
        var comments2 = [Comment](json: test)

        print(comments[0].testuserinfo?.uid)
        print(comments2[0].testuserinfo?.uid)
    }
}

class Comment: EVObject {
    var commentid = ""
    var content = ""
    var ctime = ""
    var status = "2"
    var img = ""
    var vote = "0"
    var sound: String?
    var is_vote: Bool = false
    var seller_card: String?
    var fabric: String?
    var testuserinfo: UserInfo?
}

class UserInfo: EVObject{
    var avatar = ""
    var uid = ""
    var telnum = ""
    var is_seller = "0"
    var sex = "M"
    var name = "TestUser"
    var interest = ""
}
```

**Comment by HelloPig** [comment]
i have edited the posted content, it's "userinfo". Thx, i will test the new version later.

**Comment by HelloPig** [comment]
the new version i use "testuserinfo" instead
print(comments[0].testuserinfo)
print 'nil'

**Comment by evermeer** [comment]
Strange. The unit test above does work and it outputs the 2 correct uid fields. I have to go now... I will try to push the bug fix for the crash in about 4 hours from now. I will keep you posted. Is there something in the output window? If parsing went wrong you should see some indication in the log.

**Comment by HelloPig** [comment]
let commentsJson = json["data"].rawString()?.stringByReplacingOccurrencesOfString("userinfo", withString: "testuserinfo")
print(commentsJson)
self.comments.appendContentsOf(EVReflection.arrayFromJson(Comment(), json: commentsJson))
print(self.comments[0].testuserinfo?.avatar)

output:

Optional("[\n  {\n    \"status\" : \"0\",\n    \"content\" : \"Shuru\",\n    \"ctime\" : \"1438250556\",\n    \"img\" : \"\",\n    \"isvote\" : 0,\n    \"testuserinfo\" : {\n      \"avatar\" : \"\",\n      \"uid\" : \"d8b81b21c72f1177300247e2d8d88ec5\",\n      \"telnum\" : \"18565280137\",\n      \"is_seller\" : \"0\",\n      \"sex\" : \"男\",\n      \"name\" : \"\",\n      \"interest\" : \"\"\n    },\n    \"commentid\" : \"22\",\n    \"fabric\" : null,\n    \"sound\" : \"\",\n    \"vote\" : \"0\",\n    \"seller_card\" : null\n  }\n]")
nil

**Comment by evermeer** [comment]
But your avatar in the json is empty. So you won't get it in the output.
I also see you changed the is_vote to vote. But that's not any problem as
long as you also changed your object.
The test below is using the same json and prints the telnum.

```
func testTemp2() {

    let test = "[\n {\n \"status\" : \"0\",\n \"content\" :
```

\"Shuru\",\n \"ctime\" : \"1438250556\",\n \"img\" : \"\",\n \"isvote\" :
0,\n \"testuserinfo\" : {\n \"avatar\" : \"\",\n \"uid\" :
\"d8b81b21c72f1177300247e2d8d88ec5\",\n \"telnum\" : \"18565280137\",\n
\"is_seller\" : \"0\",\n \"sex\" : \"男\",\n \"name\" : \"\",\n \"interest\"
: \"\"\n },\n \"commentid\" : \"22\",\n \"fabric\" : null,\n \"sound\" :
\"\",\n \"vote\" : \"0\",\n \"seller_card\" : null\n }\n]"

```
    let comments = EVReflection.arrayFromJson(Comment(), json: test)

    print(comments[0].testuserinfo?.telnum)

}
```

}

class Comment: EVObject {

```
var commentid = ""

var content = ""

var ctime = ""

var status = "2"

var img = ""

var vote = "0"

var sound: String?

var isvote: Bool = false

var seller_card: String?

var fabric: String?

var testuserinfo: UserInfo?
```

}

class UserInfo: EVObject{

```
var avatar = ""

var uid = ""

var telnum = ""

var is_seller = "0"

var sex = "M"

var name = "TestUser"

var interest = ""
```

}

2015-10-02 15:08 GMT+02:00 HelloPig notifications@github.com:

**Comment by HelloPig** [comment]
so crazy and i'm still confused
1.use the newest code
2.copy the test code written by u
3.run the test
4.output:
Test Case '-[ZBBuyerTests.ZBBuyerTests testExample]' started.
[
 {
 "status" : "0",
 "content" : "Shuru",
 "ctime" : "1438250556",
 "img" : "",
 "testuserinfo" : {
 "avatar" : "/5602503cc79de.jpg",
 "uid" : "d8b81b21c72f1177300247e2d8d88ec5",
 "telnum" : "18565280137",
 "is_seller" : "0",
 "sex" : "男",
 "name" : "",
 "interest" : ""
 },
 "fabric" : null,
 "commentid" : "22",
 "sound" : "",
 "vote" : "0",
 "isvote" : 0,
 "seller_card" : null
 }
]
nil
nil
Test Case '-[ZBBuyerTests.ZBBuyerTests testExample]' passed (0.076 seconds).

but run the test codes in your project get correct result
is there anything maybe related to this problem, like the app settings or something else?

**Comment by HelloPig** [comment]
I step in the codes and find the problem causing this error.

when using the func swiftClassFromString()  to init the UserInfo class, the bundle name of my project is not the same as my projectname, so the getCleanAppName() return wrong name, and the init return nil.

fixed it! Thx God! Thx U! :laughing:

**Comment by evermeer** [comment]
Great to hear that you solved the problem.
