### ISSUE TITLE
Issue in parsine dictionary with custom class

### ISSUE THREAD

**Issue by HPRaval** [evermeer/EVReflection#202]
Hi,

 I am trying to parse a json to dictionary but its  not working. Please help me

Here is my JSON.
`{\"chartConfigs\":{\"config_id\":\"651c3f71-3d44-11e7-b0b9-276d909080a8\",\"autorefresh\":false,\"background\":{\"0\":{\"background_color\":\"#feffea\",\"border_color\":\"#3264c8\",\"border_width\":2.0,\"inner_radius\":0.0,\"outer_radius\":0.0,\"shape\":\"\"}},\"chart_type\":\"Column and Bar Chart/Column with rotated labels\"}`

Here is my code

import EVReflection

```
class BackgroundPOJO : EVObject{
    
    var background_color: String = ""
    var border_color: String = ""
    var border_width: Float = 0.0
    var inner_radius: Float = 0.0
    var outer_radius: Float = 0.0
    var shape: String = ""
    
    required init() {
        //
    }
}

class ChartConfigPojo : EVObject{
    
    var config_id: String = ""
    var autorefresh: Bool = false
    
    var background : [Int:BackgroundPOJO] = [:]
    var chart_type: String = ""

    override func setValue(_ value: Any!, forUndefinedKey key: String) {
        switch key {
        case "background":
            //print("value....\(value)")
            if let dict = value as? NSDictionary{
                self.background = [:]
                for (key,val) in dict{
                    print("key...\(key)...value....\(val)")
                    self.background[key as! Int] = val as? BackgroundPOJO
                }
            }

}
```

I am getting print output as expected but my dictionary object of chart is empty always.

**Comment by evermeer** [comment]
could it be that val is a NSDictionary and not a BackgroundPOJO? If thats the case, then set it to:

```
if val = val as? NSDictionary {
   self.background[key as! Int] = BackgroundPOJO(dictionary: val)
}
```

If this is the case than (as I already suspect) do not have code in place to detect if items of a dictionary are EVReflectable. If so, then I will add that to my todo list.

**Comment by HPRaval** [comment]
No, val is not a NSDictionary. Let me show you my output in print statement

print("value....\(value)"):-

value....Optional({
    0 =     {
        "background_color" = "#feffea";
        "border_color" = "#3264c8";
        "border_width" = 2;
        "inner_radius" = 0;
        "outer_radius" = 0;
        shape = "";
    };
})

print("key...\(key)...value....\(val)"):-

key...0...value...{ "background_color" = "#feffea";
        "border_color" = "#3264c8";
        "border_width" = 2;
        "inner_radius" = 0;
        "outer_radius" = 0;
        shape = "";
    }

Let me know if you need any more info.

**Comment by evermeer** [comment]
I have created a unit test for this issue. See:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionIssue202.swift

As I was suspecting val is indeed a dictionary.

I have seen some strange compiler issues when the dictionary key was of type Int, so I have changed it to string.

**Comment by evermeer** [comment]
I have just pushed version 4.17.1 to GitHub that contains a refactor that also seems to have solved this issue. As you can see in EVReflectionIssue202 it does not crash anymore when printing the object.
