### ISSUE TITLE
Object instantion error: Class not key-value coding complaint for normal array attribute

### ISSUE THREAD

**Issue by Dantali0n** [evermeer/EVReflection#203]
Hello I have the following structure

```
public class Model : EVObject {
  // this part is just to circumvent having to use enums
  public static let STATUS : [NSString] = [
    "success",
    "failed",
    "unset"
  ]
  
  public static let STATUS_SUCCESS : Int = 0
  public static let STATUS_FAILED = 1
  public static let STATUS_UNSET = 2
  // end

  public var status : NSString = STATUS[STATUS_UNSET]
  public var subject : NSString = "unset"
  public var message : NSString = ""
}


public class BeaconModel : EVObject {
  public var uuid : NSString = ""
  public var major : Int = -1
  public var minor : Int = -1
  public var accuracy : Double = -1
}

public class BeaconsModel : Model {
  public var beacons : [BeaconModel] = [] // this part is not key-value coding compliant
}
```

When I call `toJsonString()` on BeaconsModel everything goes perfectly fine and the JSON looks clean and well formatted. But when I try to instantiate an instance of BeaconsModel using the JSON string I receive an error. 
The error is that key  `beacons` of model is not key-value compliant which to me is slightly confusing since the base model does not contain this attribute. The second is that while reading the documentation it seemed possible to use normal arrays without optionals in conjunction with EVReflection or am I mistaken? 
I also receive the error "could not create instance for type BeaconModel" but I feel that is due to key-value error raised beforehand.

Please note that serialization and deserilization with the Model class works perfectly fine its only when the array attribute in BeaconsModel is added when I start having problems.

My question is: This should be possible but its not working, am I doing something wrong or is this a bug?

**Comment by evermeer** [comment]
Could it be that you have the classes defined outside your main bundle? Like for instance in a framework? If so, then could you try calling:
`        EVReflection.setBundleIdentifier(BeaconsModel.self)`
Then EVReflection Will also look in the bundle that contains BeaconsModel
You only have to do that once (on app or test startup)

**Comment by Dantali0n** [comment]
Thank you for the quick response. Indeed the classes are defined outside the main bundle, all three classes are part of an framework.

The structure of the framework is created using:
```
public struct CogDirect {
  public struct Modules {
  }
  public struct Model {
  }
}
```

All three classes are part of the model struct, unfortunately calling `EVReflection.setBundleIdentifer(CogDirect.Model.BeaconsModel.self)` inside appDelegate of the importing app did not resolve the issue.

**Comment by evermeer** [comment]
Hmm.. I assumed that was it, because when I copy paste the code below to a unit test inside EVReflections it works as expected. 

... ah... When I put it inside the CogDirect.Model struct I do get the error. 

When I change the CogDirect and Model from a struct to a class it works again.

I will do some more investigation to see what's the real problem.

```
    class Model : EVObject {
        // this part is just to circumvent having to use enums
        public static let STATUS : [NSString] = [
            "success",
            "failed",
            "unset"
        ]
        
        public static let STATUS_SUCCESS : Int = 0
        public static let STATUS_FAILED = 1
        public static let STATUS_UNSET = 2
        // end
        
        public var status : NSString = STATUS[STATUS_UNSET]
        public var subject : NSString = "unset"
        public var message : NSString = ""
    }
    
    
    class BeaconModel : EVObject {
        public var uuid : NSString = ""
        public var major : Int = -1
        public var minor : Int = -1
        public var accuracy : Double = -1
    }
    
    class BeaconsModel : Model {
        public var beacons : [BeaconModel] = [] // this part is not key-value coding compliant
    }
    
    
    func testXXX() {
        let x = BeaconsModel()
        x.beacons.append(BeaconModel())
        let json = x.toJsonString()
        print(json)
        let nx = BeaconsModel(json: json)
        print(nx)
    }
```

**Comment by evermeer** [comment]
In your warning you probably saw a mangled name for the class. For instance when I run it in a unit test I get this as the class name: _TtCCCC12UnitTestsOSX12TestIssue1979CogDirect5Model11BeaconModel

Since this is a mangled name, it should be creatable with the NSClassFromString function like this:
        let y = NSClassFromString("_TtCCCC12UnitTestsOSX12TestIssue1979CogDirect5Model11BeaconModel")

unfortunately the result is nil. Since there is no other way to instantiate the object, this seems like a Swift limitation.

So I guess your workaround is to change the structs to classes or to put the class definitions outside the struct.

**Comment by Dantali0n** [comment]
Excellent, I will look into which of the workarounds best fits my design. Thank you for your time and effort.
Cheers,
Dantali0n
