### ISSUE TITLE
Custom String Converter

### ISSUE THREAD

**Issue by tdouglas1313** [evermeer/EVReflection#204]
I am trying to decode all Strings to unicode from when decoding JSON and encode all Strings to unicode when I encode to JSON. 

I know how to convert to and from unicode, just not for all Strings when using EVReflection.

Is there a generic way to handle this. Or do I have to just override propertyConverters().

**Comment by evermeer** [comment]
Hmm, my initial thought was that you could achieve this with:

```
extension String : EVCustomReflectable {
    public  func constructWith(value: Any?) {
        self= value as? String ?? ""
    }
    public func toCodableValue() -> Any {
        return self
    }
}
```

Where in your case you should add the encode and decode code to the functions. This does mean however that it will be used on all String fields that are used with EVReflection.

but then constructWith should have been mutable. I tried to do a quick fix for this but unfortunately that did not solve it completely. I will try to fix that this weekend.

I'm not sure yet, but I think I will add the following 2 functions to the EVReflectable protocol. This would give you a little more control over what should be encoded and decoded. You could then on class level decide if you want to convert all values of type String. 

```
override func decodePropertyValue(value: Any, key: String) -> Any {
override func encodePropertyValue(value: Any, key: String) -> Any {
```

If you have any other ideas about how this could/should be solved, then let me know.

**Comment by tdouglas1313** [comment]
I also took a look at making the `EVCustomReflectable` protocol mutating, I quickly decided it was not the best solution. I agree that having the  `decodePropertyValue` and `encodePropertyValue` functions would be a much cleaner solution. 

Currently I went with  overriding `propertyConverters()` to fix my issue. This works, but its not the ideal solution. I would agree that adding those two functions would give the control needed and allow for much more customizations for handling property conversion.

**Comment by evermeer** [comment]
Encoding and Decoding has now been added. It can also be disabled using the conversion options. For more information see: https://github.com/evermeer/EVReflection#encoding-and-decoding
For a unit test see: https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionIssue204.swift#L27
