### ISSUE TITLE
NSManagedObject subclassing does not work as expected - propertyMapping issue

### ISSUE THREAD

**Issue by bra1nDump** [evermeer/EVReflection#207]
I am using CoreData with EVReflection framework and I ran into a problem. Here is the setup of my data model:

```
class BaseEntity: EVManagedObject {
    @NSManaged var id: String
    ...
}

class User: BaseEntity: BaseEntity {
    @NSManaged var userProperty: String
    ...
}
```

When I am calling the initializer with a signature: `init(context: , json: )` I am receiving strange logs such as: `WARNING: The class 'User_User_' is not key value coding-compliant for the key '_id'`

When calling the initializer `init(dictionary: )`, which worked before adding CoreData integration, it also gives me an error (but at least correctly recognizes the class name `User`.

**Comment by evermeer** [comment]
That User_User_ is indeed strange. Could you print the following?
```
let auger = User(...)
NSStringFromClass(type(of: aUser))
```
Because that's all thats executed.

the warning for the key _id probably comes from the fact that id is actually a keyword from the Objective C area. For all keywords EVReflection will try to map it to a variable with the same name with an underscore in front if it. 

I will now do some tests with your structure to see what's going on exactly.

**Comment by evermeer** [comment]
ah... Could you try adding the @objc(CDUser) so that you end up with something like:

```
import Foundation
import CoreData
import EVReflection

@objc(CDUser)
public class CDUser: BaseEntity {
    @NSManaged var userProperty: String
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<CDUser> {
        return NSFetchRequest<CDUser>(entityName: "CDUser")
    }
}

public class BaseEntity: EVManagedObject {
    @NSManaged var id: String
}
```

**Comment by evermeer** [comment]
I added a unit test for your issue. You can find it here:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/CoreDataTests/CoreDataTests.swift#L95

And the class definition is here:
https://github.com/evermeer/EVReflection/blob/master/UnitTests/CoreDataTests/CDUser%2BCoreDataClass.swift

**Comment by bra1nDump** [comment]
Thanks for a quick response! I will check if that works and get back to you. ps: Did use @objc(User)

**Comment by bra1nDump** [comment]
This is my code setup in an empty project. The example that you provided indeed works. But I want to be able to initialize objects from an API response that I am not in charge of (which has `_id` as one of the keys), thus I have a custom mapping setup (tried adding in both `User` and `BaseEntity` classes. The error that I am getting:

```
WARNING: The class 'User_User_' is not key value coding-compliant for the key '_id'
```

in AppDelegate:
```
    let container = NSPersistentContainer.init(name: "Test")

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        
        let obj = User(context: container.viewContext, json: "{\"_id\" : \"11\", \"property1\" : \"Vermeer\"}")
        
        print(obj)
        print("\(obj.id ) \(obj.property1 )")
        
        
        // Just testing if the json parse was successfull
        let status = obj.evReflectionStatus()
        print("Json parse errors : \(status)")
        
        
        // Override point for customization after application launch.
        return true
    }
...
```

And the data model definition:
```
import CoreData
import EVReflection

@objc(User)
public class User: BaseEntity {
    @NSManaged var property1: String
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<User> {
        return NSFetchRequest<User>(entityName: "User")
    }
}

@objc(BaseEntity)
public class BaseEntity: EVManagedObject {
    @NSManaged var id: String
    
    override public func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
        return [
            ("id", "_id")
        ]
    }
}
```

**Comment by evermeer** [comment]
Ah! That's where the _id came from. I just changed my test to use the _id and the property mapping and I get the same warning as you. I will do some investigation where that comes from.

**Comment by evermeer** [comment]
I just found out that there is a strange issue when using core data objects and reading properties before a value has been set. With coredata these properties are not returned when doing a Mirror. This information is needed for the property mapping functionality to work. I think this can be fixed in EVReflection.

For now you could use this workaround:

```
import Foundation
import CoreData
import EVReflection

@objc(CDUser)
public class CDUser: BaseEntity {
    @NSManaged var userProperty: String
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<CDUser> {
        return NSFetchRequest<CDUser>(entityName: "CDUser")
    }
}

public class BaseEntity: EVManagedObject {
    @NSManaged var id: String
    
    override public func setValue(_ value: Any!, forUndefinedKey key: String) {
        if key == "_id", let value = value as? String {
            id = value
        }
    }
}
```

**Comment by evermeer** [comment]
I just pushed version 4.17.0 to GitHub which contains a refactor for property mapping plus a fix for NSManagedObjedt to dictionary mapping. Could you please have a look if this issue is now solved for you?
