### ISSUE TITLE
Error in Realm extension and EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by grago** [evermeer/EVReflection#208]
Hello, it seems that there's a little error in the Realm List extension for this library. However when correcting this issue, a memory access error appears, which is oddly only replicable on a device, and not on a simulator.

When performing toCodableValue() on the List object, the function casts each element of the collection to EVReflectable in order to encode it. However, the cast is being incorrectly made on the tuple pair returned from the enumeration, instead of the element itself, so the cast always fails and the objects inside the collection are never encoded.

Instead of this:

```swift
if let b = o as? EVReflectable
```

It should read as follows:

```swift
if let b = o.element as? EVReflectable
```

As i mentioned, when this error is corrected, a EXC_BAD_ACCESS memory appears when performing the cast, which unfortunately i don't know how to debug it. 

This error only arises when testing on a device (i've tested in 3 different devices), while it appears to be working fine in the simulator.

I've noticed there's a commented compact version of the toCodableValue() function which does not have the cast error, but the access memory error happens using this code too:

```swift
return self.enumerated().map { ($0.element as? EVReflectable)?.toDictionary() ?? NSDictionary() }
```

I would be happy to provide a sample project where the crash occurs, at least on my devices.

Many thanks.

**Comment by grago** [comment]
For some reason, using this weird trick seems to avoid the crash on the device:

```swift
public func toCodableValue() -> Any {
        
    var q = [NSDictionary]()
        
    for case let e as Any in self {
            
        q.append((e as? EVReflectable)?.toDictionary([.PropertyConverter, .KeyCleanup, .PropertyMapping, .DefaultSerialize]) ?? NSDictionary())
            
    }
        
    return q
        
}
```

Just had to cast the element to Any before casting down again to EVReflectable.

I am not sure the reason behind it, and i am sure this  is not the proper way of doing it, but it worked for me.

**Comment by evermeer** [comment]
Well, if it works, then it should be good enough... I have had more of these kind of strange issues. I will have a look at this later this evening (I'm now at work, just started the day)

I commented out the one liner because I had the same crash happening. I was under the impression that I fixed it. Strange enough the unit tests seems to work.

**Comment by evermeer** [comment]
It seems to work... I just pushed this as version 4.16.1. The publish to Cocoapods is running (will take ½ an hour)
