### ISSUE TITLE
Usage in Swift 1.2

### ISSUE THREAD

**Issue by Naoto-Ida** [evermeer/EVReflection#21]
Hi, I tried to install your library with CocoaPods, after receiving your reply here.
http://stackoverflow.com/questions/32844042/cloudkit-and-priority/32852212#32852212

I seem to be having issues pinpointing a version that conforms to Swift 1.2,
because when I install EVCloudKitDao, EVReflection is also installed,
but the syntax seems to be Swift 2.

Which ones should I use? Thanks.

**Comment by evermeer** [comment]
Did you get the correct EVCloudKitDao version using:
pod "EVCloudKitDao", '~> 2.6'
Could you try also forcing the correct version of EVReflection by adding this to your pod file:
pod "EVReflection", "swift1.2"
Make sure it's before the EVCloudKitDao line

**Comment by Naoto-Ida** [comment]
@evermeer Thank you, tried it out, but seems it doesn't recognize the try catch code in EVCloudData with '~> 2.6' of "EVCloudKitDao".

**Comment by evermeer** [comment]
OK, let me try to install an older version of Xcode so that I could try this out myself.

**Comment by Naoto-Ida** [comment]
@evermeer Thank you so much, I'm really excited about using your code!

**Comment by evermeer** [comment]
Hmm... It can't be downloaded anymore. I asked around. A colleague of my still has Xcode 6.4 This afternoon I will be able to test this. I will keep you posted...

**Comment by Naoto-Ida** [comment]
@evermeer Thank you!

**Comment by evermeer** [comment]
The SwiftTryCatch dependency was missing in the Swift1.2 podspec. I just added it. Or you could just add it to your podfile like this:

use_frameworks!
pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git', :branch => 'Swift1.2'
pod 'SwiftTryCatch'
pod 'EVCloudKitDao', '~> 2.6'

**Comment by Naoto-Ida** [comment]
@evermeer Thank you so much, will try it out.
