### ISSUE TITLE
Warning for not kv coding compliant for key 

### ISSUE THREAD

**Issue by krisanthony** [evermeer/EVReflection#214]
Hey any thoughts on adding an option to opt out of those warnings? Sometimes I don't need to implement the full object but get a bunch of warnings for each variable that's not used.

**Comment by evermeer** [comment]
There is. See https://github.com/evermeer/EVReflection#print-options

**Comment by krisanthony** [comment]
Ha! Not sure how I missed that, thanks again.

**Comment by krisanthony** [comment]
Ah I see, the project was using an older build of evreflection, which did not have that option. All good now!
