### ISSUE TITLE
Json starts with array

### ISSUE THREAD

**Issue by kosratdev** [evermeer/EVReflection#216]
Hi,

I'm using Alamofire for network request and my json starts with array how to deal with that

this is my json

    [
        {
            "id": 1503,
            "title": "ZMC express courier logistics",
            "content": "With ZMC express now we can...",
            "date": "2017-05-28 17:13:37",
            "image": "http://www.zmcexpress.com/...jpg"
        }
    ]

**Comment by gitjafar** [comment]
Your question isn't clear. What do you mean by Alomfire? How is that relevant to the question?

If you want to parse json arrays to object arrays then thats pretty straight forward:

let array = [User](json: json)

Thats just basic stuff explained in the readme file :)

**Comment by gitjafar** [comment]
Sorry didn't notice the nameless array. I don't know if thats possible in evreflection.

**Comment by evermeer** [comment]
Instead of using `.resp`onseObject you should use `.responseArray` like this:

```
        Alamofire.request(URL)
        .responseArray { (response: DataResponse<[Forecast]>) in
```

See the unit tests for the worked out demo

**Comment by kosratdev** [comment]
Thank you very much

**Comment by evermeer** [comment]
Your welcome.
