### ISSUE TITLE
EVReflection + Moya + Realm + RxSwift - Could not create an instance for type dict

### ISSUE THREAD

**Issue by AndrejJurkin** [evermeer/EVReflection#217]
Hello! I'm stuck putting all of the above together. I'll appreciate if I can get any input. Here's my short setup:

```
typealias RealmObject = Object

extension RealmObject : EVReflectable {
    
    open override func setValue(_ value: Any?, forUndefinedKey key: String) {
        
    }
}

class Product: RealmObject {
    
    dynamic var productId: String = ""  
    let productLanguages = List<ProductLanguage>()
   
    override static func primaryKey() -> String? {
        return "productId"
    }
}

class ProductLanguage: RealmObject {
    
    dynamic var productLanguageId: String = ""
    dynamic var languageCode: String = ""
    dynamic var productName: String = ""
   
    override static func primaryKey() -> String? {
        return "productLanguageId"
    }
}

```
To fetch product details I use Moya and RxSwift:

```
func getProduct(productItemKey: String) -> Observable<Product> {
    return provider.request(.product(productId: productItemKey)).map(to: Product.self)
}
```
I think `.map(to: Product.self)` does not work with realm Lists out of the box. For each object inside the list I get an error:
 ```
ERROR: Could not create an instance for type 
dict:{
    CreateDate = "2015-10-12T11:11:50.013Z";
    IngredientList = "Acao ingredient";
    LanguageCode = "en-US";
    ProductId = "d6bb0084-6838-11e5-9225-00ac14ef2300";
    ProductLanguageId = "f96848d0-df77-4594-99b7-d390bb127891";
    ProductName = Acao;
    Tagline = "The smart drink - 100% organic, vegan energy booster with guara
}
```
Is there any other way to map Moya response into Realm objects? 

Thank you very much for any input!

**Comment by evermeer** [comment]
Did you also add the Realm subspec to your pod file?
It includes an extension for Realm lists.

Actually this is the entire subspec. You could also just add it to your solution:

```
import Foundation
import RealmSwift

extension List : EVCustomReflectable {
    public func constructWith(value: Any?) {
        if let array = value as? [NSDictionary] {
            self.removeAll()
            for dict in array {
                if let element: T = EVReflection.fromDictionary(dict, anyobjectTypeString: _rlmArray.objectClassName) as? T {
                    self.append(element)
                }
            }
        }
    }
    public func toCodableValue() -> Any {
        var q = [NSDictionary]()
        for case let e as Any in self {
            q.append((e as? EVReflectable)?.toDictionary([.PropertyConverter, .KeyCleanup, .PropertyMapping, .DefaultSerialize]) ?? NSDictionary())
        }
        return q
 
        // Why do we need all this code? Should be the same as this. But this crashes.
        //return self.enumerated().map { ($0.element as? EVReflectable)?.toDictionary() ?? NSDictionary() }
    }
}
```

**Comment by AndrejJurkin** [comment]
Yes, `pod 'EVReflection/Realm'`, I've got this.

**Comment by evermeer** [comment]
OK, I will have a look at it to see if I can reproduce the issue.

Is it correct that you have a ProductLanguage in the Product itself? It looks like it's not an array of languages in your json

Do you have a sample of the json for me?

**Comment by AndrejJurkin** [comment]
I think this could be the source of the problem. Could this be possibly affecting the mapping into arrays? I've tried to get rid of the realm objects, I don't see the error anymore but productLanguages arrays remains empty.

```
extension RealmObject : EVReflectable {
    
    open override func setValue(_ value: Any?, forUndefinedKey key: String) {
        
    }
}
```

**Comment by AndrejJurkin** [comment]
Here's a sample JSON: https://pastebin.com/US8qNURr

**Comment by AndrejJurkin** [comment]
A little update. I've tried to put a breakpoint into the constructWith func, it's never called. I'll try to take a look into the RxSwift subspec.

**Comment by AndrejJurkin** [comment]
@evermeer i finally found the issue. All keys in response are in PascalCase and my naming is camelCase. This hasn't been an issue for me so far, but it does not work with Realm Lists for some reason. I changed the name to PascalCase and everything works as expected now. I'd like to keep my naming convention though. Do you have some generic idea how could I fix this on the level of Realm Lists? For now I just ended up implementing custom property mapping.

**Comment by evermeer** [comment]
I have done some refactoring on the (automatic) property mapping mechanism.
pascal to and from Camel case should work.
Please let me know if this solved your problem.

**Comment by AndrejJurkin** [comment]
@evermeer Solved my problem! Thanks

**Comment by evermeer** [comment]
Great!
