### ISSUE TITLE
App crashed if new parameter found in JSON

### ISSUE THREAD

**Issue by eastern-amol** [evermeer/EVReflection#218]
Hi,

I'm facing issue regarding parsing with EVReflection/RealM. 
While parsing, if we get a new member / parameter in the JSON object, then EVReflection is not taking care and simply crashed the app with error "This class is not key value coding-compliant for the key name". 

'media': {
                'id': '0d9095b0-5d6c-11e7-bca4-b9bc1a365po0',
                'filename': 'f359e900-5d6a-11e7-96fd-15913c389234.jpg',
                'filetype': 'profile',
                'user_id': 'd5535900-5811-11e7-acb1-256ff8fdab2e',
                'created_at': 1499260208,
                'updated_at': 1499260209
            }

Suppose, above all member present in "Media" class, and from server, developer added "name" new parameter and don't want name parameter in my application. 

In this case, EVReflection should take care to handle new parameters and it should not be crashed.

Please help on this asap, its bit urgent for me.

Thanks in advanced

**Comment by AndrejJurkin** [comment]
Just override` func setValue(_ value: Any?, forUndefinedKey key: String) { } `

To ignore undefined properties for realm object you can do something like this:

```
extension Object : EVReflectable {
    
    open override func setValue(_ value: Any?, forUndefinedKey key: String) {
        
    }
}
```

**Comment by eastern-amol** [comment]
Thank you for help @AndrejJurkin - It's working fine - Issue fixed
