### ISSUE TITLE
propertyMapping is not working for LIST 

### ISSUE THREAD

**Issue by eastern-amol** [evermeer/EVReflection#219]
Hi,

I'm facing issue about propertyMapping.

```
class Users: Object,EVReflectable {
    dynamic var id = ""
    dynamic var name = ""
    dynamic var email = ""
    var roles = List<UserRoles>()

}
class UserRoles: Object,EVReflectable {
    dynamic var id = ""
    dynamic var building_id:String?
    dynamic var role_id = ""
    dynamic var user_id:String?
    dynamic var role:Roles?
    dynamic var is_housekeeper = false


     //dynamic var user_id = ""
   
     func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
        return [
            (keyInObject: "isHousekeeper",keyInResource: "is_housekeeper")
        ]
    }
}
```

Response JSON
```
'data': {
          'users': [
              {
                  'id': '427caa90-617e-11e7-a00d-edb263eeecfa',
                  'name': 'Mr. Columbus Abbott V',
                  'email': 'muller.lina@example.com',
                  'facebook_id': null,
                  'is_active': 0,
'roles': [
                      {
                          'id': 'bfaf0560-6188-11e7-99fb-f1ca409d45d5',
                          'user_id': '427caa90-617e-11e7-a00d-edb263eeecfa',
                          'role_id': '42840640-617e-11e7-97dc-21a43b954d9e',
                          'building_id': '56482e40-6180-11e7-a6ce-1dcd684eab8f’,
                          'is_housekeeper': 1
                      }
                  ]
}
]
}
```

I followed all instruction which defines in documentation, but still is not working. 
To make it workable, I need use "is_housekeeper" instead of isHousekeeper. 

Can you please look into it? 
Please let me know if any more information is required. 

Thanks.

**Comment by evermeer** [comment]
Hi,

I see that you have set the keyInObject to "isHousekeeper" but you defined the property as "is_housekeeper". I think that you should remove the propertyMapping or change the property to "isHousekeeper". Now the property mapping will try to map it to isHousekeeper but that property is not there.

**Comment by eastern-amol** [comment]
Oops, my bad - copy paste issue. 
Actually, "isHousekeeper" was not working with property mapping, so thats why I used same which present in JSON "is_housekeeper".

Forgot to remove that before asking question. 

Please check my following implementation.

class UserRoles: Object, EVReflectable {
    dynamic var id = ""
    dynamic var building_id:String?
    dynamic var role_id = ""
    dynamic var user_id:String?
    dynamic var role:Roles?
    dynamic var isHousekeeper = false
   
     func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
        return [
            (keyInObject: "isHousekeeper",keyInResource: "is_housekeeper")
        ]
    }
}

This is correct one, can you please check now. 

Thanks

**Comment by evermeer** [comment]
Strange... That should work... 

And if you set a breakpoint inside the propertyMapping function, does it get called?

One other thing. EVReflection has automatic support for snake_case to camelCase to PascalCase conversion. So you should not be needing the propertyMapping function at all... But then... If you do have it, it should still work.

What is exactly the behaviour that you see? Is it that right after instantiating the object from a json string that the isHousekeeper field wil not be false even if it should be? By the way, a 1 is equal to true, so the field should remain true in your sample. Or do you get warning messages in the output log? If so which one do you get?

**Comment by eastern-amol** [comment]
"And if you set a breakpoint inside the propertyMapping function, does it get called?" 
- Yes, the function gets called, but the value is the remains same as the default one like "dynamic var isHousekeeper = false"
After parsing, "isHousekeeper = false" only, in case of "string" default value empty string which we set as default like "". 

It's not related to a specific type of object, its behave same for all. 
No any warning while parsing and not even other activity. 

If we use a similar object name which coming JSON then its works fine like "is_housekeeper". 

Please let me if any more information required from my side.

**Comment by evermeer** [comment]
I just pushed version 4.17.0 with a fix for your issue to GitHub.
You can find the unit test for this as RealmTestsIssue219
