### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by Diveafall** [evermeer/EVReflection#222]
I have this simple `List` object:
```
class List: CKDataObject {
    var title: String = "DEFAULT"
    var count: NSNumber = NSNumber(integerLiteral: 0)
    var isPublic: NSNumber = NSNumber(booleanLiteral: false)
}
```

When I run a simple query on it, I get the following warnings:
![screen shot 2017-08-06 at 1 41 00 pm](https://user-images.githubusercontent.com/6404971/29006535-21469324-7aaf-11e7-990d-e8d95b1e4ed1.png)

Also, the data I get back from the query uses the default value, even though in the database they have unique values. For example, a `List` with title "Jack" comes back as "DEFAULT".

What am I doing wrong here?

**Comment by evermeer** [comment]
Indeed that’s strange. Could it be that there is another object of type List? This should just work. Calling an object something generic as List might not be such a good idea.

**Comment by Diveafall** [comment]
![screen shot 2017-08-06 at 2 54 56 pm](https://user-images.githubusercontent.com/6404971/29006973-4866ef28-7ab7-11e7-9eb2-b54cda0ea055.png)

Could this be the problem?

**Comment by evermeer** [comment]
That could have been the problem. In the 4.17 release I did make a small adjustment tot the CloudKit cocoapod which could have caused this. Let me see if I can fix that.

**Comment by evermeer** [comment]
Could you please try version 4.17.2 to see if you still have this problem?

**Comment by Diveafall** [comment]
I can now successfully install [EVCloudKitDao](https://github.com/evermeer/EVCloudKitDao) via Cocoapods.

However, I still get those warnings regarding key value coding-compliance. Changing the name of the object did not help. Strangely, I started having these problems only recently after I installed  Xcode 9.0 beta 4, and created a new project. The same `List` object worked perfectly a week ago. I'm not doing anything extraordinary either. I just have this `List` object and I perform a simple query, therefore I assume this is a `EVReflection` problem.

Here's the code I use for querying:
```
enum Query {
    case all
    case predicate(NSPredicate)
    case token(tokens: String)
    case parent(field: String, parentName: String)
}

protocol QueryerDelegate {
    func queryCompleted()
    func queryCommenced()
}

protocol Queryer: class {
    associatedtype T: CKDataObject
    
    var results: [T] { get set }
    var filter: Filter { get }
    var type: Query { get }
    var delegate: QueryerDelegate? { get set }
}

extension Queryer {
    var orderBy: OrderBy { return self.filter.orderBy }
    var dao: EVCloudKitDao { return self.filter.dao }
    
    func errorHandler(_ error: Error, attempt: Double) {
        switch EVCloudKitDao.handleCloudKitErrorAs(error, retryAttempt: attempt) {
        case .retry(let seconds):
            Async.background(after: seconds) {
                self.query(attempt + 1)
            }
        case .fail:
            EVLog("Failed to perform query.")
        default: break
        }
    }
    
    func query(_ attempt: Double = 0) {
        Async.main { self.delegate?.queryCommenced() }
        let errorHandler: (Error) -> Void = { error in
            self.errorHandler(error, attempt: attempt)
        }
        let completionHandler: ([T], Bool) -> Bool = { results, isFinished in
            self.results = results
            Async.main { self.delegate?.queryCompleted() }
            return isFinished
        }
        
        switch self.type {
        case .all:
            self.dao.query(T(), orderBy: self.orderBy, completionHandler: completionHandler, errorHandler: errorHandler)
        case .predicate(let predicate):
            self.dao.query(T(), predicate: predicate, orderBy: self.orderBy, completionHandler: completionHandler, errorHandler: errorHandler)
        case .token(let tokens):
            self.dao.query(T(), tokens: tokens, orderBy: self.orderBy, completionHandler: completionHandler, errorHandler: errorHandler)
        case .parent(let field, let name):
            self.dao.query(T(), referenceRecordName: name, referenceField: field, orderBy: self.orderBy, completionHandler: completionHandler, errorHandler: errorHandler)
        }
    }
}
```

Do you have any ideas?

**Comment by evermeer** [comment]
Strange, I'm also using the beta 4 and I have no problems with your list object. I could just execute this line without any warnings:

        let list = List(json: "{\"title\":\"The title\",\"count\":2,\"isPublic\":true}")

The core of EVReflection is based on executing 1 line of code like this:

        list.setValue("The Title", forKey: "title")

That also should not trigger any warning / error. Just change the key from title into whatever and you will see your error...

**Comment by Diveafall** [comment]
I changed all mentions of `title` to `name` and I get the same results. I have a single record in the database with a specific name. When I query for all `Lists` I get the warnings and all fields have default values.

**Comment by Diveafall** [comment]
I literally just create a new project, create a `List` object, and call the `connect` function and get the same warnings. 

Strange thing is that I have an older project, with the same object that does not produce those warnings, and works perfectly. I even updated `EVCloudKitDao` to the latest version.

The problem occurs in the `setObjectValue` function. When it's working on my `title` the `typeInObject` is `NSString`, and so is the `type`. I believe `typeInObject` is supposed to be `String` right?

**Comment by evermeer** [comment]
Sorry for the late reply... I was on a holiday. 

The setValue for key should work no matter what type is set (but will probably crash later when it's wrong)

Is there an option where I could have a look at our newly created project that has this problem? That would help a lot pinpointing the problem.

**Comment by evermeer** [comment]
Is this still an issue?
