### ISSUE TITLE
decodePropertyValue and nillable properties

### ISSUE THREAD

**Issue by evermeer** [evermeer/EVReflection#223]
Reported by Roberto @neirar:
I think I found another bug. Steps to reproduce.
Create a class with a property like this var dateCreated: Date?
Implement propertyMapping to map from "created" in the resource to dateCreated in the object.
Implement decodePropertyValue to decode the date string into a Date value using a date formatter. Since you are getting a date from a string, the date formatter may return nil.
Use let userDict: NSDictionary = ["created": "adfdadadf"] and the method init(dictionary:) to create an instance of the class from Step 1. Having an invalid date is done on purpose.
Actual result: An NSInvalidArgumentException is thrown: -[NSNull timeIntervalSinceReferenceDate]: unrecognized selector sent to instance
Expected result: Since dateCreated is optional, it should be set with a null value.

**Comment by evermeer** [comment]
There are 2 issues with this.

1st. when executing a
`anyObject.setNilValueForKey(key)`
You will get the error:
`could not set nil as the value for the key dateCreated.`
So it looks like that you can't set a billable Date to nil using this. So the only thing that could be done is ignoring any nil values. This means that a non nil value will not be cleared.

2nd. when the decodePropertyValue returns a nil as an Any, then for some reason when I compare it to nil it returns false. If you return it as a NSNull, then I can test for that. So you will return it like this:
`return date ?? NSNull()`
maybe I can find a solution for this, but so far I was not successful.

See the unit test: https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionIssue223.swift#L50

**Comment by neirar** [comment]
@evermeer 
1. Even if `dateCreated` is an optional, you can't se it to `nil` using  `anyObject.setNilValueForKey("dateCreated")`?

2. I tried in a playground to return `nil` from a function that had a return type of `Any` and the compiler wouldn't let me, saying that they were incompatible. When I changed the return type to `Any?`, then it worked and I was able to compare it to a `nil` literal and got `true`. 

![screen shot 2017-09-04 at 6 01 30 pm](https://user-images.githubusercontent.com/542755/30033561-3a92e022-919c-11e7-8a2a-680303509270.png)


Currently, `decodePropertyValue` has a return type of `Any`. Maybe it needs to be changed to `Any?`. If the function returns nil (or I guess too NSNull), then it should set the value of the property only if it's an optional, and not touch it if the property is non-optional. Just a suggestion.

**Comment by evermeer** [comment]
decodePropertyValue can now return nil
