### ISSUE TITLE
Trying to understand weird behaviour: Unexpected type while converting value for JsonSerialization

### ISSUE THREAD

**Issue by peterdk** [evermeer/EVReflection#224]
I get errors in my console about ```ERROR: Unexpected type while converting value for JsonSerialization: ```
It mentions a CoreData class that I indeed assign as property to some of my EVObjects (after I parse those EVObjects from JSON).
I don't serialize anything, but still I get these warnings. And more importantly, the value of this property seems to turn nil suddenly. 

I have a hard time debugging this, and was wondering, is it possible that EVReflection somehow tries to serialize a property again and setting it to nil if it fails? 

And why am I getting warnings when I don't serialize anything?

**Comment by evermeer** [comment]
Sorry for the late response, I was on a holiday.

This probably comes from the .description or .debugDescription override in EVObject. These are changed to output the object in pretty printed json format. So when you have a print statement somewhere that outputs an object, then the object will be converted to json. 

Could you set a breakpoint at the line that prints this? it's one of the last lines of EVReflection. Could you then inspect the value and see what type it actually is? And if you step through and return to the calling function, do you see the key where it's for? What type is that property in your object?
