### ISSUE TITLE
propertyMapping doesn't seem to work

### ISSUE THREAD

**Issue by daerimin** [evermeer/EVReflection#226]
Hi, first off thank you very much for the library.  I have been away from my project for a while, and when I came back there were updates to lots of libraries I am using.  The biggest issue is with EVR - it seems that propertyMapping no longer works.  I have a PHP server that sends JSON objects to the app over HTTP, and some of the properties in the JSON I want to ignore.  I have been working on this project for over a year, and the code was working fine before the update - the properties were ignored, and all was well.  Now, I get "this class is not key value coding-compliant for the key [key name], which of course crashes my app.  It's difficult for me to understand why EVR doesn't simply ignore keys that aren't in the object - it means I can NEVER change my server-side code without wrecking my app.  Is there a way to solve this?

Thank you!

**Comment by daerimin** [comment]
Update:  I solved my issue by way of the setValue/forUndefinedKey override.  Sorry for the unnecessary issue.

**Comment by evermeer** [comment]
property mapping should still work. About 2 months ago the signature and working of the function was changed. You should now call it like this:

```
    override open func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
        return [(keyInObject: "ignoredProperty", keyInResource: nil),
                (keyInObject: nil, keyInResource: "ignoredProperty"),
                (keyInObject: "propertyInObject", keyInResource: "keyInJson")]
    }
```
