### ISSUE TITLE
master branch Swift Version

### ISSUE THREAD

**Issue by johnboker** [evermeer/EVReflection#229]
The ReadMe says the master branch is Swift 3.0.  This doesn't seem to be the case though, it looks like master is now Swift 4.0.

**Comment by evermeer** [comment]
Well, It's actually both. If you go to the unit test targets and put those and in 'Build Setting' set the 'language version' to Swift 3.2 then all unit test still succeed. So if you use the master branch in your project, then it should not matter if it's Swift 3.2 or 4 isn't it? Or am I missing something? But you are right... I should update the readme :-)

**Comment by johnboker** [comment]
Whenever I use the master branch I get the following error:

`Pods/EVReflection/Source/EVObject.swift:15:2: Unknown attribute 'objcMembers'`

I think my problem is I'm using Xcode 8.3.3, which doesn't seem to support Swift 3.2.

**Comment by evermeer** [comment]
I have Xcode 8.3.3 installed and it supports Swift 3.2. 

Ah... @objcMemebers was added to swift 4 as a requirement. In Swift 3.2 you will get an error for that. My bad. Then I have to create a separate branch for that. Can't do that before tomorrow. For now just remove the @objcMembers In Swift 3.2 and it will just work.

**Comment by johnboker** [comment]
Thanks for your help with this.  All these swift language version changes are slowing killing me.

Keep up the good work.

**Comment by evermeer** [comment]
I just mad a quick fix and created a Swift3.2 branch. So master wil stay Swift 4 since it will probably go out of beta soon.

**Comment by evermeer** [comment]
To prevent these confusions, for now I have moved back the master branch to Swift 3.2 and I created a separate Swift 4 branch
