### ISSUE TITLE
framework not found EVReflection

### ISSUE THREAD

**Issue by cafuni** [evermeer/EVReflection#23]
Mac OSX 10.11.1
Xcode 7.1

I installed the library following this steps:

Open Terminal and execute: $ sudo gem install cocoapods
Navigate to my Project folder (example /Users/myName/Documents/APP/APP.xcodeproj).
Setup Cocoapod: pod setup
Create the Podfile: touch Podfile
Open the Podfile: open -e Podfile
Insert code for Podfile: 
use_frameworks!
pod "EVReflection", '~> 2.6'
Finally install the Podfile pod install

when I run the app I receive this error:
ld: framework not found EVReflection
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by evermeer** [comment]
Do you have an iOS or an OS X target? I believe I added OS X support in a later version than 2.6. As you can see in the readme the 2.6 version is for Swift 1.2. If you use Swift 2.0 then you can just use the latest (currently 2.11) by removing the 2.6 specifier. So your pod file will just have this:

pod "EVReflection"

**Comment by cafuni** [comment]
i'm using iOS
I tried to install pod again with only "EVReflection" but the error is the same

**Comment by cafuni** [comment]
i tried also on a new project

**Comment by evermeer** [comment]
after doing a pod install you have to open the workspace and not the project. Did you do that? In your project navigator you should see your project plus a Pods project. And if you do a filter for EVReflection on the files it should find EVReflection.swift

**Comment by cafuni** [comment]
I create a new project test. I followed the steps.

I opened the folder of the project and I opened the test.xcworkspace
<img width="764" alt="screenshot 2015-11-06 09 29 50" src="https://cloud.githubusercontent.com/assets/15674190/10992788/cb393046-8469-11e5-9668-b3a0b89762ba.png">

after that i receive this message
<img width="736" alt="screenshot 2015-11-06 09 30 10" src="https://cloud.githubusercontent.com/assets/15674190/10992807/fab1c1e4-8469-11e5-833b-1e6c4625d907.png">

**Comment by cafuni** [comment]
in the project navigator I see this
<img width="443" alt="screenshot 2015-11-06 09 51 18" src="https://cloud.githubusercontent.com/assets/15674190/10993035/007ae0ae-846c-11e5-908a-6adb1310d7cd.png">

**Comment by evermeer** [comment]
I see that you have 2 workspaces. I assume that the pod install created the project.xcworkspace.
So you should use that one. As you can see in your project navigator of the test.xcworkspace you only have one project. You also should have the Pods project

**Comment by evermeer** [comment]
Here is for instance how it looks in my EVCloudKitDao demo app:

<img width="466" alt="screen shot 2015-11-06 at 9 54 07 am" src="https://cloud.githubusercontent.com/assets/130834/10993077/6108878c-846c-11e5-9d40-170107398eb2.png">

As you can see I am using 10 different frameworks. These are the folders in the Pods folder in the Pods project

**Comment by cafuni** [comment]
i record the steps that I did:

https://www.youtube.com/watch?v=R6YzT8IyGEA&feature=youtu.be

https://www.youtube.com/watch?v=wsaVHLt-b0s&feature=youtu.be

https://www.youtube.com/watch?v=XpmkcyP8Imc&feature=youtu.be

where I do mistakes?

thank you

**Comment by evermeer** [comment]
Ah, there is only 1 thing whats not standard. I think the chance is big that this is the problem.
You execute everything from within the .xcodeproj folder.
That's also why you had to add a reference to your project

**Comment by cafuni** [comment]
how do i fix it? thank you

**Comment by evermeer** [comment]
When you start from scratch with a new project, then assume you create that project in folder /xxx/yyy/newTestApp
then open a console window and do a cd to the folder /xxx/yyy/newTestApp
Do not do a cd to the .xcodeproj folder!
Then create the podfile there with the use frameworks and the pod 'EVReflection'
Then execute the 'pod install'
open the workspace

If you want to fix an existing project, then move the podfile out of the .xcodeproj folder into it's parent folder. 
Remove that fix for finding the project (it's in the same folder, so you don't need it)
Remove all the workspaces
run 'pod install'
open the new workspace

**Comment by cafuni** [comment]
thank you! I fixed it! just last thing: do i have to open workspace everytime? or i can open the project from xcodeproj ? thank you

**Comment by evermeer** [comment]
If you open the project, then you wont't have the pod framework. You need that. So you always have to open the workspace. This is default cocoapod behaviour. Once you get used to using libraries with cocoapods you never want to develop without them :)

**Comment by qvivr-cris** [comment]
I'm having the same error, ld: framework not found EVReflection

**Comment by qvivr-cris** [comment]
I seem to get framework not found or (library not found) for whatever cocoapod I install.   I'm thinking our project file has some non standard setup.  :-/

**Comment by evermeer** [comment]
@qvivr-cris If you go to your project settings, build phases and look at the link binary with libraries, Do you see a Pods_yourapp.framework there? (after doing a pod install)
