### ISSUE TITLE
UTC date deserialization

### ISSUE THREAD

**Issue by AndrejJurkin** [evermeer/EVReflection#230]
I am receiving a date in the following format: '2017-09-11T08:18:39Z', are there any steps I need to take in order to be able do deserialise it into a Date? 

For the moment it does not seem to work out of the box.

**Comment by evermeer** [comment]
The default date formatter used is:

        dateFormatter = DateFormatter()
        dateFormatter!.locale = Locale(identifier: "en_US_POSIX")
        dateFormatter!.timeZone = TimeZone(secondsFromGMT: 0)
        dateFormatter!.dateFormat = "yyyy'-'MM'-'dd' 'HH':'mm':'ssZ"

You can change the default date formatter using the EVReflection.setDateFormatter function.
I'm not sure why it dit not deserialised your date. Could it be the T between date and time?

**Comment by AndrejJurkin** [comment]
Thanks! Problem solved, after setting a date format manually :

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
        EVReflection.setDateFormatter(dateFormatter)
