### ISSUE TITLE
unknown attribute 'objcMembers' in EVObject.swift

### ISSUE THREAD

**Issue by ghost** [evermeer/EVReflection#231]
Updated to latest release 4.19.0 and started receiving the above error. Using Swift 3.1 and Xcode 8.3.3

**Comment by noobs2ninjas** [comment]
it actually should be @objc Members and actually that line shouldnt be there at all. Remove it and build. Worked just fine for me. And nothing else broke when I did. Hopefully they will push out an update soon to fix it.

**Comment by evermeer** [comment]
I might have moved the master branch to Swift 4 a bit too soon. @objcMembers is required in Swift 4 if you want to be able to write to properties. For Swift.3.2 there is now a separate branch.

**Comment by evermeer** [comment]
To prevent these confusions, for now I have moved back the master branch to Swift 3.2 and I created a separate Swift 4 branch
