### ISSUE TITLE
What is the timeframe to Swift 4 becoming master?

### ISSUE THREAD

**Issue by noobs2ninjas** [evermeer/EVReflection#232]
I was that you pushed swift 4 to its own branch. Im assuming that this means Swift 3.2 is being used on Master again? I wanted to find out a time frame for when 4 gets moved back to master again. We are still using 3.2 here at work and are just trying to find out when some of the frameworks we are using are looking to moving over so we should be moving over.  I assume others are probably wondering as well when they should be looking to convert their code. 

Also, I heard something about how you can use libraries with different versions of swift now? I heard you can have a library done in Swift 3.2 and be using 4. Did I imagine that or is that actually a thing?

**Comment by evermeer** [comment]
For EVReflection there is only 1 statement that has to be there in Swift 4 and is not supported in Swift 3.2. The EVObject has the attribute @objcMembers at the top. I tried to find out if I could do a conditional compile for it, but I could not. There is now both a Swift 3.2 and a Swift 4 branch. I'm not sure yet what the best moment is to switch master to Swift 4. When I did it earlier this week I got a lot of questions about it. I will probably switch **within 2 or 3 weeks.** If you intend to stay with Swift 3.2 then it would be **better to change to the 3.2 branch now** already.
