### ISSUE TITLE
Cannot call value of non-function type 'String' - Swift 4

### ISSUE THREAD

**Issue by krunalbhavsar** [evermeer/EVReflection#238]
Version: EVReflection (4.19.1)
Issue with Swift 4 update.

**FileName**: EVReflection.swift

**Function:**
`public static func setObjectValue<T>(_ anyObject: T, key: String, theValue: Any?, typeInObject: String? = nil, valid: Bool, conversionOptions: ConversionOptions = .DefaultDeserialize, parents: [NSObject] = []) where T: NSObject {`

**Line: 977**
```
{
                (anyObject as? EVReflectable)?.addStatusMessage(.InvalidValue, message: "Not a valid value for object `\(NSStringFromClass(type(of: (anyObject as AnyObject))))`, type `\(type)`, key  `\(key)`, value `\(value)`")
                evPrint(.InvalidValue, "INFO: Not a valid value for object `\(NSStringFromClass(type(of: (anyObject as AnyObject))))`, type `\(type)`, key  `\(key)`, value `\(value)`")
            }
```

> Error: Cannot call value of non-function type 'String' 

<img width="750" alt="screen shot 2017-09-27 at 10 51 39 pm" src="https://user-images.githubusercontent.com/16011224/30927566-79220754-a3d6-11e7-81dc-4b385520580b.png">

**Comment by krunalbhavsar** [comment]
Solved by using: https://github.com/evermeer/EVReflection/issues/236

Pod download/integrated `v 4.19.1` if I use pod 'EVReflection'

But when I tried following it integrated v 5.0.0
pod `EVReflection` from `https://github.com/evermeer/EVReflection.git`


Please look into this issue. (pod 'EVReflection' should download/integrate v5.0.0)

**Comment by evermeer** [comment]
@krunalbhavsar At the moment it's not possible to publish the 5.0.0 version to cocoapods because it requires a beta version of Moya (because of Swift 4 compatibility). The moment Moya 10 is released I will push it.
