### ISSUE TITLE
performKeyCleanup not working with class attributes of type EVObject

### ISSUE THREAD

**Issue by hugowschneider** [evermeer/EVReflection#24]
In this example:

``` swift
class User: EVObject {
    var id: Int = 0
    var name: String = ""
    var closeFriends: [User]? = []
}

var user = User()
...
var dic = user.toDictionary(true)
```

I got in the dictionary the key `"close_friends"`, but when I inspect the value of `dic["close_friends"][0]`, it has the key `"closeFriends"` and not `"close_friends"`

**Comment by evermeer** [comment]
I pushed this change to GitHub as version 2.11.2

The performKeyCleanup parameter had to be passed on to the reflectedSub so that it could be used when calling the toDictionairy there.
