### ISSUE TITLE
Redundant conformance of 'Realm' to protocol 'EVReflectable'

### ISSUE THREAD

**Issue by tonespy** [evermeer/EVReflection#240]
I am getting a conformation error when I implement the EVReflectable protocol.

<img width="919" alt="screen shot 2017-10-02 at 9 42 26 am" src="https://user-images.githubusercontent.com/3057485/31069852-10b04388-a756-11e7-817e-16c6c55574b6.png">

To my knowledge, if I'm getting that error, it means EVReflection already implements Realm. But, why? I've tried removing Realm to check. But, still didn't work.

**Comment by evermeer** [comment]
You don't have to add EVReflectable.
Object already conforms to EVReflectable.
So defining your class like this is enough:
`class RealmLocation: Object {`

**Comment by tonespy** [comment]
Yeah. Couldn't wait for your answer. So, I tried that. Thanks though.

**Comment by Alarson93** [comment]
If you only define your class using `class RealmLocation: Object`, how do you deserialize from JSON? For instance, without including EVReflectable, I cannot use:
`public init(json: String?, conversionOptions: ConversionOptions = .DefaultDeserialize, forKeyPath: String? = nil)`

The readme is probably out of date.
https://github.com/evermeer/EVReflection/tree/master/Source/Realm

**Comment by evermeer** [comment]
@Alarson93 The readme is still ok... You can then jus do something like:

```
let theJsonString = "{... some json string ...}"
let location = RealmLocation(json: theJsonString)
```
The conversionOptions and forKeyPath parameters are not required. In most case you also don't need these. To see it in action see the realm unit tests.

**Comment by Alarson93** [comment]
@evermeer Thank you for your prompt response.
It appears that my issue was with autocomplete (for some reason, it doesn't list json: as a valid initializer). When I enter the parameters manually, like in your example, the issue is resolved. Thank you!

**Comment by evermeer** [comment]
@Alarson93 Xcode Autocomplete could use some work... It's often 'sub optimal'
