### ISSUE TITLE
Class not key value coding compliant for key

### ISSUE THREAD

**Issue by myriaddevices** [evermeer/EVReflection#242]
I have create a very simple view controller in order to test EVReflection.

I receive the following message for (seemingly) every key in the JSON.

`🌀 
WARNING: The class 'User' is not key value coding-compliant for the key 'email'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information`

The following is my class (with some code copied from [here](https://github.com/evermeer/EVReflection/issues/114).

`class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let jsonDictOriginal = [
            "id": 24,
            "name": "John Appleseed",
            "email": "john@appleseed.com",
            "company": [
                "name": "Apple",
                "address": "1 Infinite Loop, Cupertino, CA"
            ],
            "friends": [
                ["id": 27, "name": "Bob Jefferson"],
                ["id": 29, "name": "Jen Jackson"]
            ]
            ] as NSDictionary
        
        print("Initial dictionary:\n\(jsonDictOriginal)\n\n")
        
        let userOriginal = User(dictionary: jsonDictOriginal)
        
        let jsonString = userOriginal.toJsonString()
        print("JSON string from dictionary: \n\(jsonString)\n\n")
    }
}

class User: EVObject {
    var id: Int = 0
    var name: String = ""
    var email: String?
    var company: Company?
    var friends: [User] = []
}

class Company: EVObject {
    var name: String = ""
    var address: String?
}`

I am very confused as to why I get these errors. I clearly have the complimentary properties on my objects. My issue also doesn't seem to have anything to do with optionals as, for example, the non-optional property "name" doesn't work either.

Result:
`(lldb) po print(userOriginal)
User = {
  "email" : null,
  "id" : 0,
  "friends" : [

  ],
  "company" : null,
  "name" : ""
}`

Edit: I have no idea why my code styling is breaking.

**Comment by myriaddevices** [comment]
Found the issue. My podfile was pointing to:
`pod 'EVReflection/Alamofire'`

I overlooked the need to point to the EVReflection repo. The issue was resolved by instead point to:
`pod 'EVReflection/Alamofire', :git => 'https://github.com/evermeer/EVReflection.git'`

**Comment by evermeer** [comment]
I switched master to Swift 4

Unfortunately I'm not allowed to push a new version for this to cocoapods because there now is a dependency to Moya 10.0 which is still in beta. 

In order to use this using cocoapods you have to specify the git pad so that it will use master
`pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git'`

If you also use Moya, then you also have to add this:
`pod 'Moya', :git => 'https://github.com/Moya/Moya.git', :branch => '10.0.0-dev'`
