### ISSUE TITLE
Module file's minimum deployment target is ios9.0

### ISSUE THREAD

**Issue by lexrus** [evermeer/EVReflection#246]
After the latest release 5.1.0, I failed to build my project since it targets iOS 8.

**Comment by evermeer** [comment]
Ah, my bad, I was trying to fix the publication to cocoapods. I still have an issue with that. I just did pushed version 5.1.1 to GitHub where the iOS version is back to 8 again.

**Comment by lexrus** [comment]
Nice. Thank you.

**Comment by lexrus** [comment]
Just faced the same issue in 5.1.5. 😭

**Comment by evermeer** [comment]
@lexrus  Are you sure? Because the podspec still says:
`s.ios.deployment_target = '8.0'`
So if you do a `pod update` It fails to get the 5.1.5 version?

**Comment by lexrus** [comment]
Here it is.
<img width="477" alt="screen shot 2017-10-29 at 5 17 07 pm" src="https://user-images.githubusercontent.com/219689/32142205-14ed9464-bccd-11e7-8103-4b4e4034eab3.png">

I'm using Carthage instead.

**Comment by evermeer** [comment]
Ah, Carthage, Yes, those where not set correctly... Now it should be OK again...

**Comment by evermeer** [comment]
Just let me kno if it's still an issue
