### ISSUE TITLE
Compatibility with Realm 3?

### ISSUE THREAD

**Issue by lexrus** [evermeer/EVReflection#247]
Upgraded to realm-cocoa 3. There're some errors in RealmListEVCustomReflectable.swift:

<img width="875" alt="screen shot 2017-10-18 at 11 23 57 am" src="https://user-images.githubusercontent.com/219689/31699707-f86aa4d2-b3f6-11e7-9792-b049fff198ab.png">
<img width="855" alt="screen shot 2017-10-18 at 11 24 11 am" src="https://user-images.githubusercontent.com/219689/31699709-f89d61a6-b3f6-11e7-8be1-69983df5d44c.png">

**Comment by evermeer** [comment]
Thanks for reporting there is a new version that has a problem. I will investigate this issue now

**Comment by evermeer** [comment]
I just pushed version 5.1.2 to GitHub with a fix for Realm 3
