### ISSUE TITLE
Noob question about Swift version

### ISSUE THREAD

**Issue by superarts** [evermeer/EVReflection#248]
Sorry to put the issue here, I don't think it's an EVReflection issue, but so far I'm only getting this issue from EVReflection. Anyway, I updated from Xcode 8 to Xcode 9 today, and after `pod update`, EVReflection (5.1.5) couldn't be built anymore. The fix is simple, I just need to manually change Swift Language Version to `4.0`; but how is it possible? I noticed the `.swift-version` file as well as `s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.0' }` in `podspec`, but why my cocoapod (1.3.1) still sets Swift Language Version of the Pod to `3.2`?

My Podfile is like:

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'
use_frameworks!

target 'MyClient' do
...
end

(I tried to add a line `swift_version = '4.0'` in Podfile but apparently it didn't do anything.)

**Comment by evermeer** [comment]
It should be picked up as 4.0. Could it be that your main app is in Swift 3.2?

If this happens after every 'pod update' then you could add the following to your podfile to force EVReflection to 4.0

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['EVReflection'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Comment by superarts** [comment]
Thanks!
