### ISSUE TITLE
Method range:at was renamed to rangeAt in swift 4

### ISSUE THREAD

**Issue by ekubyshin** [evermeer/EVReflection#249]
https://github.com/evermeer/EVReflection/blob/b4f02f30a085f8003cf30221ed106831eae381fd/Source/EVReflection.swift#L1580

**Comment by evermeer** [comment]
Yes, that's indeed a TODO...

**Comment by evermeer** [comment]
This issue is duplicated by https://github.com/evermeer/EVReflection/issues/254

According to the documentation it should be `range(at:)`
Or am I missing something?
