### ISSUE TITLE
Incorrect Arguments Label in Call

### ISSUE THREAD

**Issue by pizzimathy** [evermeer/EVReflection#251]
I have an issue with the `EVReflection/XML` extension. Using this in conjunction with `Alamofire`, I have this code:

```
import Alamofire
import EVReflection
...
class Laundry: EVObject {
    var school_name: String?
    var laundry_rooms: [Room] = [];
}
...
class http {
    class func get(view: DataViewController) {
        if view.isXML {
            Alamofire.request(view.uri).responseData{ response in
                if let data = response.data, let xml = String(data: data, encoding: .utf8) {
                    let laundry = Laundry(xml: xml);
                }
            }
        ...
    }
}
```

Xcode throws an error when it tries to compile `Laundry(xml: xml)`, as in the example on `evermeer/EVReflection`, saying that I have an incorrect argument label `xml:` and that `coder:` is expected.

I have installed `EVReflection/XML` by including `pod EVReflection/XML` in my podfile and have gone through the resolution steps outlined in other peoples' issues. Any help is greatly appreciated.

**Comment by evermeer** [comment]
Some time ago the init signature changed a little. You should now call it like this:
`let laundry = Laundry(xmlString: xml)`
This was indeed wrong in the documentation. It's now updated.
