### ISSUE TITLE
RealmOptional setValueForKey

### ISSUE THREAD

**Issue by Alarson93** [evermeer/EVReflection#252]
I was working with Realm last week and came across a bug that EVR seems to introduce. I should note that I am up to date with both EVR and Realm.

Basically, I want to set a RealmOptional by using it's property name. Here is an example:

`class MyObject: Object {
    let myRealmOptional = RealmOptional<Int>()
}`

`let myObject = MyObject()
myObject.setValue(5, forKey: "myRealmOptional")`

But, after running this, the value is nil. I suspect that for the RealmOptional supported I requested earlier (thank you again btw) you had to override setValueForKey - if so, perhaps you still need to call the super in some context?

Any info you could provide would be wonderful!

Also, if you are curious about the context around what why I am doing this, you can check this thread (notable the reference to issue 5433):
https://github.com/realm/realm-cocoa/issues/5469

**Comment by evermeer** [comment]
Hmm... I'm only overriding the
`open override func setValue(_ value: Any!, forUndefinedKey key: String)`
It could be that the `setValue forKey` calls that function.
It would be easy to change that function so that it would call it's super.
Maybe you could first do a test. Just add the following line in the object extension
`super.setValue(value, forUndefinedKey: key)`
I'm currently not sure when I will be able to do this test (very busy)

**Comment by Alarson93** [comment]
```
open override func setValue(_ value: Any!, forUndefinedKey key: String) {
        if let kvc = self as? EVGenericsKVC {
            kvc.setGenericValue(value as AnyObject!, forUndefinedKey: key)
        } else {
            super.setValue(value, forUndefinedKey: key)
            (self as? EVReflectable)?.addStatusMessage(.IncorrectKey, message: "The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'")
            evPrint(.IncorrectKey, "WARNING: The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'\n❓ This could be a strange Realm List issue where the key is reported undefined but it's still set.\n")
        }
    }
```

As you can see, I added the super line in the else. This seems to have resolved the issue, however I'm only working with the narrow test case outlined above. So while I cannot speak for the safety of this approach, it does some to solve my immediate problem.

As a bonus, this allows me to set Lists as well (which is clearly dangerous in certain contexts). Settings Lists fixed a major bug in my detachability logic as seen on this thread:
https://github.com/realm/realm-cocoa/issues/5433

**Comment by evermeer** [comment]
Thanks for the test! This weekend I wil also do some tests and if all is OK I will publish a new version.

**Comment by evermeer** [comment]
@Alarson93 The addition of the super.setValue is now published in release 5.2.0

I only just found out that it will crash if you set an optional from json. I will try to find out if I have to clean up the value before I pass it on.

**Comment by evermeer** [comment]
I just published release 5.2.1 that will also do some value cleanup.

**Comment by Alarson93** [comment]
Awesome! I'll do some testing this week and let you know if I have any problems.

**Comment by Alarson93** [comment]
I updated to 5.2.1 in my test project. Prepare for a long post :)

## Highlights:
1. 5.2.0+ crashes when a key exists in the JSON but there is no complimentary property. I believe the issue is that we are attempting to setValueForKey/setValueForUndefinedKey when there is no property.
2. Having an optional number, such as RealmOptional<Int>, crashes when the JSON key has a value of null. It appears that we are trying to assign an NSNull to an NSNumber.


### 1:

I have the following object (from a SWAPI response):
```
class PersonRealm: Object, EVReflectable {
    @objc dynamic var name: String?
    @objc dynamic var height: String?
    @objc dynamic var mass: String?
    @objc dynamic var hair_color: String?
    @objc dynamic var skin_color: String?
    @objc dynamic var eye_color: String?
    @objc dynamic var birth_year: String?
    @objc dynamic var gender: String?
    @objc dynamic var homeworld: String?
    @objc dynamic var created: String?
    @objc dynamic var edited: String?
    @objc dynamic var url: String?
//    let films = List<String>()
    let species = List<String>()
    let vehicles = List<String>()
    let starships = List<String>()
}
```

As you can see, I have commented out the films array. On EVR 5.1.5 I would get messages in the dialogue that the keys are not implemented (well, technically anything that is a `let` would output the message). This would be a graceful warning that causes no crash.

On EVR 5.2.1 I get a crash. The crash is consequence of RLMObjectBase.mm:
```
- (id)valueForUndefinedKey:(NSString *)key {
    if (Ivar ivar = _objectSchema[key].swiftIvar) {
        return RLMCoerceToNil(object_getIvar(self, ivar));
    }
    return [super valueForUndefinedKey:key];
}
```

I believe that your changes in 5.2.1 introduced this. Also, it seems 5.2.0 cannot handle this case either. The crash comes from RLMObjectBase.mm as well, but on method below.
`- (void)setValue:(id)value forUndefinedKey:(NSString *)key`

**Edit:** Actually, I believe I introduced the bug by not checking to see if the property exists. Below is a possible fix. I have added a check to see if the property exists.
```
    open override func setValue(_ value: Any!, forUndefinedKey key: String) {
        if let kvc = self as? EVGenericsKVC {
            kvc.setGenericValue(value as AnyObject!, forUndefinedKey: key)
        } else if objectSchema.properties.first(where: { $0.name == key }) != nil {
            super.setValue(value, forUndefinedKey: key)
        } else {
            (self as? EVReflectable)?.addStatusMessage(.IncorrectKey, message: "The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'")
            evPrint(.IncorrectKey, "WARNING: The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'\n❓ This could be a strange Realm List issue where the key is reported undefined but it's still set.\n")
        }
    }
```

Or including the value cleanup:
```
    open override func setValue(_ value: Any!, forUndefinedKey key: String) {
        if let kvc = self as? EVGenericsKVC {
            kvc.setGenericValue(value as AnyObject!, forUndefinedKey: key)
        } else if objectSchema.properties.first(where: { $0.name == key }) != nil {
            if let current = super.value(forKey: key) {
                if current is NSNumber, value is NSString {
                    //If we do have key and the types are different, then this is called from EVReflection
                    let num = NSNumber(value: Int("\(value as! NSString)") ?? 0)
                    super.setValue(num, forUndefinedKey: key)
                } else if type(of: current) == type(of: value)
                    || (String(describing: type(of: current)).hasPrefix("List<") && value! is NSArray) {
                    super.setValue(value, forUndefinedKey: key)
                } else {
                    (self as? EVReflectable)?.addStatusMessage(.InvalidType, message: "Invalid type for the key '\(key)' in the class '\(EVReflection.swiftStringFromClass(self))'")
                    evPrint(.IncorrectKey, "WARNING: the type (\(type(of: current)) of the The key '\(key)' in class '\(EVReflection.swiftStringFromClass(self))' does not corresponds to the type (\(type(of: value!)) in the json or Realm database.\n")
                }
            }
        } else {
            (self as? EVReflectable)?.addStatusMessage(.IncorrectKey, message: "The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'")
            evPrint(.IncorrectKey, "WARNING: The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'\n❓ This could be a strange Realm List issue where the key is reported undefined but it's still set.\n")
        }
    }
```
### 2:
Additionally, it seems that nulls also cause issues. For instance, if I have an optional number (RealmOptional<Int>) and its complimentary value in the JSON is null, I get a crash on `setPropertiesfromDictionary`. Specifically, the `custom.constructWith(value: value)`.
There resulting error is:
Could not cast value of type 'NSNull' (0x10a795520) to 'NSNumber' (0x10c827600).

This based on _minimal_ testing, this appears to resolve the problem. However, I'm not particularly sure what the purpose of constructWith is...thus I cannot speak for the safety of this approach.
```
                if let value: Any = valid ? dictValue : (v as Any) {
                    if let custom = original as? EVCustomReflectable {
                        if let null = value as? NSNull {
                            custom.constructWith(value: nil)
                        } else {
                            custom.constructWith(value: value)
                        }
                    }
                    setObjectValue(anyObject, key: keyInObject!, theValue: value, typeInObject: types[keyInObject!] as? String, valid: valid, conversionOptions: conversionOptions)
                }
```

**Comment by evermeer** [comment]
First a reaction for your number 1 issue:
Thanks for reporting in such detail!
I do think your final proposal needs a small change.
You first check for:
`if objectSchema.properties.first(where: { $0.name == key }) != nil {`
and then for the:
`if let current = super.value(forKey: key) {`

I think that structure should be changed a little.
If you have a json with 10 fields and only want 5 of these to store in realm, then I do think that you should be able to store the other values in your object. If you first check the objectSchema, then these would be skipped.

If you are able to get the `.value(forKey: key)` then you also will be able to set the value for that key. I think you only need to check the objectSchema in the else. 

I will now do some tests with that. The function will look like this:

```
    open override func setValue(_ value: Any!, forUndefinedKey key: String) {
        if let kvc = self as? EVGenericsKVC {
            kvc.setGenericValue(value as AnyObject!, forUndefinedKey: key)
        } else if let current = super.value(forKey: key) {
            if current is NSNumber, value is NSString {
                //If we do have key and the types are different, then this is called from EVReflection
                let num = NSNumber(value: Int("\(value as! NSString)") ?? 0)
                super.setValue(num, forUndefinedKey: key)
            } else if type(of: current) == type(of: value)
                || (String(describing: type(of: current)).hasPrefix("List<") && value! is NSArray) {
                super.setValue(value, forUndefinedKey: key)
            } else {
                (self as? EVReflectable)?.addStatusMessage(.InvalidType, message: "Invalid type for the key '\(key)' in the class '\(EVReflection.swiftStringFromClass(self))'")
                evPrint(.IncorrectKey, "WARNING: the type (\(type(of: current)) of the The key '\(key)' in class '\(EVReflection.swiftStringFromClass(self))' does not corresponds to the type (\(type(of: value!)) in the json or Realm database.\n")
            }
        } else if objectSchema.properties.first(where: { $0.name == key }) != nil {
            super.setValue(value, forUndefinedKey: key)
        } else {
            (self as? EVReflectable)?.addStatusMessage(.IncorrectKey, message: "The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'")
            evPrint(.IncorrectKey, "WARNING: The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'\n❓ This could be a strange Realm List issue where the key is reported undefined but it's still set.\n")
        }
    }
```

**Comment by evermeer** [comment]
As for your 2nd issue, I would like to handle that in the constructwith function that is implemented in the RealmOptional. Then when EVCustomReflectable is used somewhere else that would require a NSNull then it could still use it. 

So my new code would look like this:

```
extension RealmOptional : EVCustomReflectable {
    /**
     If you have a custom type that requires special conversion, then you can extend it with the EVCustomReflectable protocol.
     
     - parameter value: The dictionary that will be converted to an object
     */
    public func constructWith(value: Any?) {
        if value is NSNull {
            self.value = nil
        } else {
            self.value = value.map(dynamicBridgeCast)
        }
    }
```

**Comment by evermeer** [comment]
The 2 issues above have now been published as version 5.4.0

**Comment by Alarson93** [comment]
Thank you for making the changes (and fixing my proposals)!

I will update later today and let you know if I run into any other issues.

**Comment by evermeer** [comment]
just let me know if you have any other issues (or still an issue with this :) )

**Comment by Alarson93** [comment]
Hello again! It would seem I had a minor problem in my proposed fix.

In the `open override func setValue(_ value: Any!, forUndefinedKey key: String)` we have `else if type(of: current) == type(of: value)`.
The `type(of: value)` returns `Swift.Optional<Any>`. If we force value using `type(of: value!)`, we get `RealmSwift.List<Swift.String>` as expected. Forcing isn't dangerous in this case because the function already forces the value parameter.

The function, as a whole, including the force unwrap of optional I mentioned would like so:

```
    open override func setValue(_ value: Any!, forUndefinedKey key: String) {
        if let kvc = self as? EVGenericsKVC {
            kvc.setGenericValue(value as AnyObject!, forUndefinedKey: key)
        } else if let current = super.value(forKey: key) {
            if current is NSNumber, value is NSString {
                //If we do have key and the types are different, then this is called from EVReflection
                let num = NSNumber(value: Int("\(value as! NSString)") ?? 0)
                super.setValue(num, forUndefinedKey: key)
            } else if type(of: current) == type(of: value!)
                || (String(describing: type(of: current)).hasPrefix("List<") && value! is NSArray) {
                super.setValue(value, forUndefinedKey: key)
            } else {
                (self as? EVReflectable)?.addStatusMessage(.InvalidType, message: "Invalid type for the key '\(key)' in the class '\(EVReflection.swiftStringFromClass(self))'")
                evPrint(.IncorrectKey, "WARNING: the type (\(type(of: current)) of the The key '\(key)' in class '\(EVReflection.swiftStringFromClass(self))' does not corresponds to the type (\(type(of: value!)) in the json or Realm database.\n")
            }
        } else if objectSchema.properties.first(where: { $0.name == key }) != nil {
            super.setValue(value, forUndefinedKey: key)
        } else {
            (self as? EVReflectable)?.addStatusMessage(.IncorrectKey, message: "The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'")
            evPrint(.IncorrectKey, "WARNING: The class '\(EVReflection.swiftStringFromClass(self))' is not key value coding-compliant for the key '\(key)'\n❓ This could be a strange Realm List issue where the key is reported undefined but it's still set.\n")
        }
    }
```

Tested and working.
