### ISSUE TITLE
Is it possible to merge two EVObjects ?

### ISSUE THREAD

**Issue by DubonYaar** [evermeer/EVReflection#253]
Is it possible to merge data of two EVObjects ?

**Comment by evermeer** [comment]
I'm not exactly sure what you mean, but if it's that you would like to map 2 different json responses into  one EVObject, then the answer is yes. Just create one object that contains the properties for both and initiate the 2 objects with the json.  Then use EVReflection.setPropertiesfromDictionary to move the data from the 2nd object to the first object.

You could use code like this:

```
class ObjectOneAndTwo: EVObject {
   fieldFromOne: String?
   fieldFromTwo: String?
}

let jsonOne = "{\"fieldFromOne\":\"is one\"}"
let jsonTwo = "{\"fieldFromTwo\":\"is two\"}"

let mergedObject = ObjectOneAndTwo(json: jsonOne)
let objTwo = ObjectOneAndTwo(json: jsonTwo)

EVReflection.setPropertiesfromDictionary(objTwo.toDictionary(), anyObject: mergedObject)
```

**Comment by evermeer** [comment]
Just let me know if you have more questions
