### ISSUE TITLE
Characters is Deprecated 

### ISSUE THREAD

**Issue by Mahan3340** [evermeer/EVReflection#255]
HI, please replace Characters.split / Characters.count  / Characters.index / Characters.first 
. . . its deprecated now since xcode 9.1

**Comment by MortenGregersen** [comment]
I've created a pull request for this #259

**Comment by evermeer** [comment]
I will have a look at that PR later today.

**Comment by Mahan3340** [comment]
@evermeer  thx 👍

**Comment by evermeer** [comment]
The pull request has been merged and published as version 5.4.1
