### ISSUE TITLE
Mapping names from snake case JSON to camel case Object

### ISSUE THREAD

**Issue by hugowschneider** [evermeer/EVReflection#26]
Hi again,

I am working with a json in snake case and classes in camel case. I found that some atributes in my class were not set.

To correct this I changed the line 60 of file EVReflection.swift

from:

``` swift
if let dictValue = dictionaryAndArrayConversion(types[k as! String], original: original, dictValue: v) {
```

to:

``` swift
if let dictValue = dictionaryAndArrayConversion(types[mapping ?? k as! String], original: original, dictValue: v) {
```

It solved my problem.

Hope it helps

**Comment by evermeer** [comment]
Great! I will have a look at this tonight.

**Comment by evermeer** [comment]
I pushed this change to GitHub as version 2.11.2

**Comment by hugowschneider** [comment]
Thanks!
