### ISSUE TITLE
pod "EVReflection/CoreData" problem

### ISSUE THREAD

**Issue by treaptech** [evermeer/EVReflection#263]
Hi,

when i want to install "EVReflection/CoreData" module, i have a following problem. How can i fix it ? 
thanks..

[!] CocoaPods could not find compatible versions for pod "EVReflection/CoreData":
  In Podfile:
    EVReflection/CoreData

None of your spec sources contain a spec satisfying the dependency: `EVReflection/CoreData`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by evermeer** [comment]
Strange...     pod 'EVReflection/CoreData' should work
What Xcode and Swift version are you using? I think you should use Xcode 8 or later with Swift 4
If you just add pod 'EVReflection' does it install that? If so, what version will be installed?

**Comment by evermeer** [comment]
Just let me know If you still have issues with this
