### ISSUE TITLE
Array of an dictionary(In dictionary again there is a dictionary) evreflection?

### ISSUE THREAD

**Issue by saikishoreagrapalem** [evermeer/EVReflection#265]
[

        {

        address =         {

            city = Boston;

            "created_at" = "2017-08-16T21:53:21.928-04:00";

            "cross_street" = "";

            "full_address" = "145 Brighton Avenue, , Boston , MA 02134";

            id = 63104;

            latitude = "42.3531365";

            longitude = "-71.1316891";

            "short_address" = "145 Brighton Avenue, Boston, 02134";

            "short_state_name" = MA;

            state = MA;

            "street_name" = "145 Brighton Avenue";

            "sub_number" = "";

            town = "";

            "updated_at" = "2017-08-22T23:07:52.389-04:00";

            url = "http://api.deliberr.co/addresses/63104.json";

            "zip_code" = 02134;

        };

        "amount_entered" = "0.0";

        "created_at" = "2017-10-09T22:30:01.052-04:00";

        "created_by" = 2;

        customer =         {

            addresses =             [

                                {

                    city = "San Francisco";

                    "created_at" = "2017-10-24T02:16:39.481-04:00";

                    "cross_street" = "";

                    "full_address" = "150 Post Street, Financial District, San Francisco , California 94108";

                    id = 63124;

                    latitude = "37.7889912";

                    longitude = "-122.4046004";

                    "short_address" = "150 Post Street, Financial District, 94108";

                    "short_state_name" = CA;

                    state = California;

                    "street_name" = "150 Post Street";

                    "sub_number" = "";

                    town = "Financial District";

                    "updated_at" = "2017-10-24T02:16:39.481-04:00";

                    url = "http://api.deliberr.co/addresses/63124.json";

                    "zip_code" = 94108;

                },

                                {

                    city = Boston;

                    "created_at" = "2017-08-16T21:53:21.928-04:00";

                    "cross_street" = "";

                    "full_address" = "145 Brighton Avenue, , Boston , MA 02134";

                    id = 63104;

                    latitude = "42.3531365";

                    longitude = "-71.1316891";

                    "short_address" = "145 Brighton Avenue, Boston, 02134";

                    "short_state_name" = MA;

                    state = MA;

                    "street_name" = "145 Brighton Avenue";

                    "sub_number" = "";

                    town = "";

                    "updated_at" = "2017-08-22T23:07:52.389-04:00";

                    url = "http://api.deliberr.co/addresses/63104.json";

                    "zip_code" = 02134;

                }

            ];

            "created_at" = "2017-08-16T21:53:21.920-04:00";

            id = 57042;

            "last_name" = "<null>";

            name = "";

            phone = 2222222222;

            "phone_extention" = "";

            "updated_at" = "2017-09-08T16:29:32.792-04:00";

            url = "http://api.deliberr.co/customers/57042.json";

        };

        "customer_id" = 57042;

        "customer_signature_url" = "<null>";

        "delivery_charge" = "8.0";

        "delivery_time" = "<null>";

        "driver_delivery_fee" = "9.5";

        "driver_id" = 4;

        "driver_total_amount" = "9.5";

        "expected_pickup_time" = "2017-10-09T22:45:01.305-04:00";

        id = 118;

        "is_future_order" = 0;

        "order_number" = 452911;

        "payment_type_id" = 3;

        "payment_type_label_name" = Cash;

        "payment_type_name" = cash;

        "pickup_time" = "2018-01-31T00:10:50.842-05:00";

        "preparing_minutes" = 15;

        "remaining_time_now" = 167445;

        restaurant =         {

            address =             {

                city = Boston;

                "created_at" = "2017-10-09T22:28:50.606-04:00";

                "cross_street" = "<null>";

                "full_address" = "100 Foster Street, Brighton, Boston , Massachusetts 02135";

                id = 63116;

                latitude = "42.3474175";

                longitude = "-71.157617";

                "short_address" = "100 Foster Street, Brighton, 02135";

                "short_state_name" = MA;

                state = Massachusetts;

                "street_name" = "100 Foster Street";

                "sub_number" = "<null>";

                town = Brighton;

                "updated_at" = "2017-10-09T22:28:50.606-04:00";

                url = "http://api.deliberr.co/addresses/63116.json";

                "zip_code" = 02135;

            };

            "address_id" = 63116;

            "base_commission_per_order" = "2.5";

            "contact_information_id" = 15;

            "created_at" = "2017-10-09T22:28:50.646-04:00";

            id = 5;

            "legal_information_id" = 15;

            name = "Galaxy Manti";

            "phone_number" = 3123123121;

            "updated_at" = "2017-10-09T22:29:13.573-04:00";

            url = "http://api.deliberr.co/restaurants/5.json";

            "user_id" = 19;

        };

        "restaurant_id" = 5;

        "restaurant_name" = "Galaxy Manti";

        "restaurant_receipt_url" = "http://s3.amazonaws.com/deliberrstorage/pictures/photos/000/000/370/original/data?1517375447";

        state = "out_of_delivery";

        "tip_amount" = "0.0";

        "total_amount" = "8.0";

        "updated_at" = "2018-01-31T00:10:50.872-05:00";

        url = "http://api.deliberr.co/orders/118.json";

        "week_day" = 1;

    }

]

**Comment by saikishoreagrapalem** [comment]
how to split this kind of response by using evreflection code?

**Comment by evermeer** [comment]
Since it's not a true dictionary or json, I assume that you have formatted your output yourself. Therefore I cannot turn it into a fully worked out example. But I will try to explain.
Your top level is an array, so you will end up with an array of objects. It looks like the objects are something like transactions so lets assume that you make an object named Transaction. This transaction has a sub dictionary / object named Address. So you will also create an object like that.

```
public class Transaction: BaseObject {
    var address: Adres?
    var amountEntered: NSNumber?
    var createdBy: NSNumber?
   var customer: Client?
}

public class Address: BaseObject {
    var city: String?
    var crossStreet: String?
    var fullAddress: String?
    // continue with the other Address fields
}

public class Client: BaseObject {
    var addresses: [Address]?
    var addressId: NSNumber?
    var baseCommisionPerOrder: NSNumber?
    var contactInformationId: NSNumber?
    // continue with the other Client fields
}

public class BaseObject: EVReflectable {
    createdAt: NSDate?
    var id: NSNumber? 
}

```

And you can then probably initiate it with something like:

```
let myData = [Transaction](dictionary: theDictionaryData)
```

**Comment by saikishoreagrapalem** [comment]
I'm really excited to getting the response from you thank you for
responding. Now, i am working i got the issue when im getting this whole
response in array so that how can i change that array reponse to the
dicitonary and then how to pass the dictionary data to the
(yourDictionaryData) i.e., let myData = [Transaction](dictionary:
yourDictionaryData)

 (let myData = [Transaction](dictionary: response) : Argument labels
'(dictionary:)' do not match any available overloads).


Thanks

**Comment by saikishoreagrapalem** [comment]
dicitonary can't accepting the array response so based on evreflection how
can i use to turn the response to dictionary and pass the dictionary data!!

**Comment by evermeer** [comment]
I'm not exactly sure if I understand you correctly. Do you mean that you don't have the data in a dictionary yet? Is it a json response? If so then you can just initiate the objects with something like:

`let myData = [Transaction](json: myJson)`

But then, The output you have in the first response at the top, that is not json. Is that what you have in a string? If so, then you could try to clean it up so that it becomes valid json. Or if you get it from an external system maybe you could ask if they also support outputting valid json.

So what is your current situation? Do you have a String with the above exact content? Or do you already have a dictionary that conatains that data? Maybe you could show me a couple of lines of code that shows your starting position.

**Comment by saikishoreagrapalem** [comment]
Yes ill explain you clearly with the lines of code

 func webServiceGETCall(url : String, paramValues : NSDictionary
,completionBlock : @escaping RTWebserviceStatusCompletionBlock) {





       let headers = ["X-User-Email":RTUserDefaults.sharedInstances().
setEmailID(),"X-User-Token":RTUserDefaults.sharedInstances().getAccessToken
()]



        debugPrint("DEBUG: \(paramValues)")



        request = Alamofire .request(url, method: .get, parameters:
paramValues as? Parameters, encoding: URLEncoding.default, headers:
headers) .responseJSON { response in



            debugPrint(response)



            switch response.result {

            case .success(let responseArr):

                completionBlock( nil, responseArr as! NSMutableArray)

//so here what i have to use nsmutable array or string any i used string
any also but after in view controller im not getting the array response if
i use nsmutable array im getting the array response

            case .failure(let error):

                completionBlock(error as NSError?, NSMutableArray())

            }

        }

    }

I'm getting the whole response as array in success block

by using this below code im getting the array respinse  and now stuced in
to the split the array of the dictionary

               ( let myData = [Transaction](dictionary: response) : if i
used this line of code im getting the error label as Argument labels
'(dictionary:)' do not match any available overloads)


        RTWebService.sharedInstance.getAcceptedHomeOrders(loginDict:
queryParams as NSDictionary, completionBlock:

            {

                (error , response ) -> Void in



                print(response)



 });

 }


think so clear now ??

**Comment by saikishoreagrapalem** [comment]
func webServiceInitialPOSTCall(url : String, paramValues : NSDictionary
,completionBlock : @escaping RTWebserviceStatusCompletionPostBlock) {



        debugPrint("DEBUG: \(paramValues)")



        Alamofire .request(url, method: .post, parameters: paramValues as?
Parameters, encoding: URLEncoding.default, headers: nil) .responseJSON {
response in



            debugPrint(response)



            switch response.result {

            case .success(let responseDict):

                completionBlock( nil, responseDict as? [String : AnyObject])

// here this worked fine because im getting response as dictionary and this
block worked fine and navigate to another view controller

            case .failure(let error):

                completionBlock(error as NSError?,nil)

            }

        }

    }


RTWebService.sharedInstance.postLoginControl(loginDict: queryParams as
NSDictionary, completionBlock:

            {

                (error , response ) -> Void in



                if let responseObj = response

                {

                    print(response)



                    if (responseObj["error"] == nil) {


// this is the way i set in to the dictionary response to evobject and
getting and the values use that commonobjects.



                    let model = CommonObjects(dictionary: responseObj as
NSDictionary) as CommonObjects




RTUserDefaults.sharedInstances().setAccessToken(accessToken:
String(model.auth_token))

                    RTUserDefaults.sharedInstances().setEmailID(userID:
String(model.email))




                    let nextVC:HomeViewController =
self.storyboard?.instantiateViewController(withIdentifier:
"HomeViewController") as! HomeViewController

                    self.navigationController?.pushViewController(nextVC,
animated: false)



                    }



                    else {



                        let errorMsg = responseObj["error"] as! String


                        if(String.NonNilString(str:
errorMsg).characters.count > 0)

                        {

                            let alert = UIAlertController(title: "",
message: errorMsg, preferredStyle: UIAlertControllerStyle.alert)

                            alert.addAction(UIAlertAction(title: "Ok",
style: UIAlertActionStyle.default, handler: nil))

                            self.present(alert, animated: true, completion:
nil)

                        }


                   }



                }

                else

                {

                    if error != nil {

                        if !(error?.localizedDescription.isEqual("cancelled"
))!

                        {

                            //ProgressHUD .shared() .hide()

                            print("Error :\((error?.localizedDescription)!)"
)





                        }

                    }

                }

        })


                    let model = CommonObjects(dictionary: responseObj as
NSDictionary) as CommonObjects
// that line worked fine becuse im getting the reponse as dictionary.

// this is the way i set in to the dictionary response to evobject and
getting and the values use that commonobjects.

but only if i get array response without key or string means how to handle
that array of a dictionary response ?


please suggest me clearly about array of a dictionary?

**Comment by evermeer** [comment]
Ai, my bad, for an array the parameter is not dictionary but dictionaryArray. So it has to be:
`let myData = [Transaction](dictionaryArray: responseArr)
`

**Comment by saikishoreagrapalem** [comment]
OMG! yes i tried 2 days back with dictionaryArray but i always suggesting
me to change the format like "coder" instead of "dictionaryArray" because i
created wrong format i think so.
But now its worked finally
This is what i expected and now i got finally thank you so much.

*[Transaction = {*

*  "amountEntered" : 0,*

*  "id" : 118,*

*  "customer" : {*

*    "contactInformationId" : null,*

*    "id" : 57042,*

*    "addressId" : null,*

*    "addresses" : [*

*      {*

*        "fullAddress" : "150 Post Street, Financial District, San
Francisco , California 94108",*

*        "id" : 63124,*

*        "city" : "San Francisco",*

*        "crossStreet" : "",*

*        "createdAt" : null*

*      },*

*      {*

*        "fullAddress" : "145 Brighton Avenue, , Boston , MA 02134",*

*        "id" : 63104,*

*        "city" : "Boston",*

*        "crossStreet" : "",*

*        "createdAt" : null*

*      }*

*    ],*

*    "createdAt" : null,*

*    "baseCommisionPerOrder" : null*

*  },*

*  "createdAt" : null,*

*  "createdBy" : 2,*

*  "address" : {*

*    "fullAddress" : "145 Brighton Avenue, , Boston , MA 02134",*

*    "id" : 63104,*

*    "city" : "Boston",*

*    "crossStreet" : "",*

*    "createdAt" : null*

*  }*

*}]*

**Comment by evermeer** [comment]
Just let me know If you still have issues with this
