### ISSUE TITLE
Not Mapping Int and Bool Values

### ISSUE THREAD

**Issue by kaleemasadmughal** [evermeer/EVReflection#268]
i was trying to map a json but Int and Bool Values Were failed to Map

**Comment by evermeer** [comment]
Could it be that you are using an optional int or optional bool?
There are a couple of situations where Swift is not able to assign a value dynamically.
You can find the complete list here:
https://github.com/evermeer/EVReflection#known-issues

For the optional int you can do 3 things:
- Make the int non optional and assign a default value
- Change it to an optional NSNumber
- implement the setValue forUndefinedKey function and handle the optional there (see the unit tests for an implementation)

**Comment by evermeer** [comment]
Just let me know If you still have issues with this
