### ISSUE TITLE
init() issue

### ISSUE THREAD

**Issue by cafuni** [evermeer/EVReflection#27]
hi I have a question:

i have this class:

```
public class ResponseLogin: Response {
    var token:String
    var sessionId:String
    var codFiscale:String

    var nome:String
    var cognome:String


    init(token: String, sessionId: String, codFiscale: String, nome: String, cognome : String, statusCode: String, elencoMessaggi: [Messaggio]) {

        self.token = token
        self.sessionId = sessionId
        self.codFiscale = codFiscale
        self.nome = nome
        self.cognome = cognome

        super.init(statusCode: statusCode, elencoMessaggi: elencoMessaggi)
    }
}
```

when i call the class 

```
  let responseObj:ResponseLogin = ResponseLogin(json: data)
```

it required me all the parameters and  json:data it considered an extra.

what is the best practise?

**Comment by evermeer** [comment]
I assume the base class of Response is NSObject or EVObject?

What ResponseLogin(json: data) does is creating a new ResponeLogin object using the default constructor and then setting all properties from the json. If you have extra fields that you also want to set, then you could create a constructor that accepts all variables but also the json. then you could call the super.init(json: data) at the last line within that constructor. I think in your case you should do that from your Response class

One other way is by just using the init you defined yourself to create a new object and then set all the properties from the json. Then the code will look like this:
        var responseObj:ResponseLogin = ResponseLogin(token:"asd", sessionId: "jkl", ...
        let jsonDict = EVReflection.dictionaryFromJson(data)
        EVReflection.setPropertiesfromDictionary(jsonDict, anyObject: responseObj)

**Comment by cafuni** [comment]
response is:

```
public class Response: NSObject {
    var statusCode:String
    var elencoMessaggi:[Messaggio]

    init(statusCode: String, elencoMessaggi: [Messaggio]){


    self.statusCode = statusCode
        self.elencoMessaggi = elencoMessaggi
    }
}
```

**Comment by cafuni** [comment]
i didn't  understand your first solution

**Comment by evermeer** [comment]
This should work:

```
public class ResponseLogin: Response {
    var token:String
    var sessionId:String
    var codFiscale:String
    var nome:String
    var cognome:String


    init(token: String, sessionId: String, codFiscale: String, nome: String, cognome : String, statusCode: String, elencoMessaggi: [Messaggio], data: String) {

        self.token = token
        self.sessionId = sessionId
        self.codFiscale = codFiscale
        self.nome = nome
        self.cognome = cognome

        super.init(statusCode: statusCode, elencoMessaggi: elencoMessaggi, data)
    }
}

public class Response: NSObject {
    var statusCode:String
    var elencoMessaggi:[Messaggio]

    init(statusCode: String, elencoMessaggi: [Messaggio], data: String){
        self.statusCode = statusCode
        self.elencoMessaggi = elencoMessaggi
        super.init(json:data)
    }
}
```

You do have to be aware that setting the fields from the json is executed at the end. If one of your fields is inside the json, then the value will be overwritten. If you don't want that, then move both super.init calls to the first line of the constructor.

**Comment by cafuni** [comment]
it doesn't work

**Comment by cafuni** [comment]
should i use a call like this? 

```
  let responseObj:ResponseLogin = ResponseLogin(token: "", sessionId: "", codFiscale: "", nome: "", cognome: "", statusCode: "", elencoMessaggi: [], data: data)
```

**Comment by evermeer** [comment]
Yes, that's how you should call it.

What is the problem? Do you have a compile time error, run time error, or a data error? Do you get an error message?

**Comment by cafuni** [comment]
![ccccc](https://cloud.githubusercontent.com/assets/15674190/11239626/730a4a44-8ded-11e5-9315-79276f46db14.png)

**Comment by evermeer** [comment]
Ah, that's right, you can't call an extension initializer like that.
There are 2 ways to fix this.
1. instead of NSObject as the base class you could use EVObject as it's base class
2. Call the methods that are in the initializer yourself by replacing  the super.init(json: data) line with:

```
        let jsonDict = EVReflection.dictionaryFromJson(data)
        EVReflection.setPropertiesfromDictionary(jsonDict, anyObject: self)
```

p.s. Do you have an `import EVReflection` at the top?

**Comment by cafuni** [comment]
i solved using object without init().

I have another issue. The library cannot be able to convert .toJsonString() object with another object as attribute (nested objects)

**Comment by evermeer** [comment]
If you run the unit test testJsonObject, then you will see at line 137 that it's doing a .toJsonString() The result of that is:

```
{
  "email" : "john@appleseed.com",
  "id" : 24,
  "closeFriends" : [
    {
      "email" : null,
      "id" : 27,
      "closeFriends" : [

      ],
      "company" : null,
      "name" : "Bob Jefferson",
      "birthDate" : null
    },
    {
      "email" : null,
      "id" : 29,
      "closeFriends" : [

      ],
      "company" : null,
      "name" : "Jen Jackson",
      "birthDate" : null
    }
  ],
  "company" : {
    "name" : "Apple",
    "address" : "1 Infinite Loop, Cupertino, CA"
  },
  "name" : "John Appleseed",
  "birthDate" : "11\/18\/15, 7:31:28 PM GMT+1"
}
```

As you can see there is a sub object company and an array of users in the friends property.
You do have to make sure that all objects have NSObject as it's base object  (or EVObject)

**Comment by cafuni** [comment]
i confirm that using EVObject in the class with "import EVReflection" it works fine! with NSObject it doesn't work

**Comment by evermeer** [comment]
Thanks, I will have a look at that this evening. I think I added a check for EVObject because there are lot of NSObject classes like NSDate where you do not want the properties for. Maybe there is a way to do it with NSObject by testing for a couple of types.

**Comment by evermeer** [comment]
I just pushed a new version 2.12.1 that allows nested objects of type NSObject instead of EVObject.
