### ISSUE TITLE
strange stuff while unit testing

### ISSUE THREAD

**Issue by bj97301** [evermeer/EVReflection#276]
I have the following test and user class:
```
class UserTest {
    func testDoesNotConvertPasswordsNStuff() {
        let user = User()
        user.password = "ohNoz"
        _ = user.toDictionary()
    }
}
```
```
import EVReflection
import Foundation
class User: EVObject {
    var walletId: String?
    var modifiedBy: String?
    var emailAddress: String?
    var id: String?
    var active: String?
    var created: String?
    var lastModified: String?
    var fullName: String?
    var phoneNumber: String?
    // swiftlint:disable:next identifier_name
    var _description: String?
    var password: String?

//    override public func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
//        return [(keyInObject: "password",keyInResource: nil)]
//    }
}
```
when I include the last line then build I get the following errors:
![screen shot 2018-03-28 at wednesday march 28 2018 11 53 am](https://user-images.githubusercontent.com/1450431/38050070-b8e33ec6-327e-11e8-8323-ddd397bc3ca8.png)

```
 "__T012EVReflection13EVReflectablePAAE12toDictionarySo12NSDictionaryCAA17ConversionOptionsVFfA_", referenced from:
  "__T012EVReflection8EVObjectCAA13EVReflectableAAWP", referenced from:

  "__T012EVReflection13EVReflectablePAAE12toDictionarySo12NSDictionaryCAA17ConversionOptionsVF", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I remove `_ = user.toDictionary()` the errors go away.  Seems strange.  Any idea whats going on?  Ive done a clean/rebuild and restarted xcode.

**Comment by evermeer** [comment]
Strange indeed. There is nothing wrong with your code.

What version of Xcode and EVReflection are you using?

I have added it as a unit test to EVReflection. 
You can find it here: https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionIssue276.swift#L51
If you download EVReflection and run all the tests, do you get the same error?

**Comment by bj97301** [comment]
Your unit test is coo but mine is still fucked.  Probably something stupid I am doing.  Will double check my project and see whats up.  Thank you for the quick reply and help.
