### ISSUE TITLE
Nested Array parsing is Printable but Unreachable

### ISSUE THREAD

**Issue by turushan** [evermeer/EVReflection#278]
If I print the root object, it shows nested array objects as well, but when I try to reach them error happens. 

1) when it parses, it gives also this warning: 
Have to convert here... NSArray to Swift.Array<Swift.Array<XXXXITEM>>

2) I can call obj.nestedarray.capacity or some other built-in functions, I can print "obj" but I can't print obj.nestedarray or obj.nestedarray[x] etc.
Fatal error: NSArray element failed to match the Swift Array Element type

I saw similar issues opened and closed before but issue still alive is there any workaround?

**Comment by evermeer** [comment]
Yes, Nested arrays are still an issue with an available workaround. see https://github.com/evermeer/EVReflection/issues/212

In short: You have to create a propertyConverter for that property. the decodeConverter will be called with an [[NSDictionary]]. You could use a nested .map to make it a [[YourObject]]. The code will look something like this:

```
class A81b: EVObject {
    var array: [[A81]] = [[]]
    
    // Now only working using this workaround
    // Failure should be fixed for https://github.com/evermeer/EVReflection/issues/212
    override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [(key: "array",
                 decodeConverter: {
                    self.array = (($0 as? NSArray)?.map { (($0 as? NSArray)?.map { A81(dictionary: ($0 as? NSDictionary ?? NSDictionary()))}) ?? [] }) ?? [[]]
        }, encodeConverter: { return self.array })]
    }
}

class A81: EVObject {
    var openId: String = ""
}
```

**Comment by turushan** [comment]
<img width="1365" alt="screen shot 2018-04-05 at 10 40 19" src="https://user-images.githubusercontent.com/4019257/38353064-f966c874-38bd-11e8-8d34-0ad5ac8ff9f7.png">

Now I have a syntax error any idea? If I change it via "coder", it just gives another error @evermeer

**Comment by evermeer** [comment]
you also need a:
`import EVReflection`
Otherwise it can't find the convenience initializer for your object

**Comment by turushan** [comment]
This is also my BaseItem 
```
import Foundation
import EVReflection

class BaseItem: EVObject {
    
}
``` 

and this is ProductItem (normally I just import evreflection on BaseItem but added everywhere after your suggestion)

``` 
import Foundation
import EVReflection

class ProductItem: BaseItem {
  var id = ""
  var image = ""
  var featureImage = ""
  var title = ""
  var subTitle = ""
  var type = 0
  var detail = ""
  var price = 0
  var expirationDate = ""
  var stock = 0
  var isFeatured = false
}
``` 

but still I have problem after added your suggested import, and cleaned project then built, doesn't help :( @evermeer 

![screen shot 2018-04-05 at 13 27 51](https://user-images.githubusercontent.com/4019257/38361264-856b701a-38d5-11e8-81f0-5ad902b57cd1.png)

**Comment by evermeer** [comment]
I should have use the sample code from the unit test. You need to add quite some nil handling.
For the unit test see https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/TestObjects.swift#L274

You have to create a propertyConverter for that property. the decodeConverter will be called with an [[NSDictionary]]. In version 5.6.0 I added helper functions to convert it to [[YourObject]]. The code (from the unit tests) will look something like this:

```
class A81b: EVObject {
    var array: [[A81]] = [[]]
    
    // Now only working using this workaround
    // Failure should be fixed for https://github.com/evermeer/EVReflection/issues/212
    override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [(key: "array",
            decodeConverter: {
                self.array = ($0 as? NSArray)?.nestedArrayMap { A81(dictionary: $0) } ?? [[]]
        }, encodeConverter: { return self.array })]
    }
}

class A81c: EVObject {
    var array: [[[A81]]] = [[[]]]

    // Now only working using this workaround
    // Failure should be fixed for https://github.com/evermeer/EVReflection/issues/212
    override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [(key: "array",
                 decodeConverter: {
                    self.array = ($0 as? NSArray)?.doubleNestedArrayMap { A81(dictionary: $0) } ?? [[]]
        }, encodeConverter: { return self.array })]
    }
}

class A81d: EVObject {
    // Skipping the triple, quadruple, quintuple nestedArrayMap and go strait to the sextuple
    // You should not want something like this
    var array: [[[[[[[A81]]]]]]] = [[[[[[[]]]]]]]
    
    // Now only working using this workaround
    // Failure should be fixed for https://github.com/evermeer/EVReflection/issues/212
    override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [(key: "array",
                 decodeConverter: {
                    self.array = ($0 as? NSArray)?.sextupleNestedArrayMap { A81(dictionary: $0) } ?? [[[[[[]]]]]]
        }, encodeConverter: { return self.array })]
    }
}

class A81: EVObject {
    var openId: String = ""
}
```
