### ISSUE TITLE
Just noticed some warnings

### ISSUE THREAD

**Issue by Sydney-o9** [evermeer/EVReflection#280]
![image](https://user-images.githubusercontent.com/1480617/38788276-2912b45a-4176-11e8-9a21-7ef4725885c1.png)

Do you have these and if yes, do you guys want a PR to fix them?

**Comment by evermeer** [comment]
Those where easy to fix. I just pushed version 5.6.1 with these changes to GitHub. It will be available as a cocoapods version in about an hour. Thanks for reporting this.
