### ISSUE TITLE
Print in lib

### ISSUE THREAD

**Issue by Dbigshooter** [evermeer/EVReflection#283]
Hi there,
I've stumbled over a print(" have to convert here... NSArray...") in the code, line 1195 in EVReflection.swift. Is that supposed to be there, or something that just got left out?

**Comment by evermeer** [comment]
That's for an issue that I'm struggling with: https://github.com/evermeer/EVReflection/issues/212

Here you can find the workaround for nested arrays
https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionTests.swift#L496

**Comment by Dbigshooter** [comment]
Oh okay, I'm not experiencing any troubles, it's just spamming my console.

**Comment by evermeer** [comment]
You can silence the print output of EVReflection using:
`PrintOptions.Active = .None`
Or you could specify the array of message types that you want to print (see readme)

But... This print was not using the options. Should have been... 
I just pushed a fix for that to GitHub. It will be part of the next Cocoapods release.
