### ISSUE TITLE
Memory Leak on init of EVObject

### ISSUE THREAD

**Issue by srikanthsuryawanshi** [evermeer/EVReflection#288]
Hello EVReflection Team,

when used instruments for our project I saw there are almost around 15k memory leaks accounting for 600 KiB from EVReflection as a source of the leak.

we use 4.19.1 as the base but when I had used sample app and performance test app bundled with EVReflection even then I could see there were leaks.

func testIssue213() {
...
        let data = ResultArrayWrapper<Spot>(json: content)
}

when I debugged with various scenarios and use cases I found on every EVObject Init there is a leak and this leak gets bigger when the object has lots of properties.

**Comment by evermeer** [comment]
See:
https://github.com/evermeer/EVReflection/issues/272#issuecomment-395968149

A fix has just been published to GitHub. the Cocoapod publish will be ready in about ½ an hour

**Comment by evermeer** [comment]
As reported in #272 this is indeed fixed
