### ISSUE TITLE
Suggestion on use of reserved words handling

### ISSUE THREAD

**Issue by garethcurtis** [evermeer/EVReflection#29]
Hi there,

Firstly, your code has been a great help in the project I'm working on and has saved me a lot of typing! So thank you for that :)

Just a suggestion to improve things the handling of reserved words - I've just had a put in a bit of a hack to handle the conversion back of _as and _is. Shouldn't the underscore be removed when converting an NSObject back into a JSON string. The API I'm using makes use of as and is as keys (don't ask!) and they map happily to _as and _is on the JSON->object but not going back the other way.

Thanks again.

Best wishes,

Gareth.

**Comment by evermeer** [comment]
You are right, they should have been written to json like _is to is and _as to as. If it does not, then it's a bug. I can have a look at it later this evening (7 hours from now)

**Comment by evermeer** [comment]
In my case it does work. Did you call the toJsonString with the performKeyCleanup set to true?
You need to call it like this:
yourObject.toJsonString(true)

**Comment by evermeer** [comment]
You can see it functioning in a unit test here:
https://github.com/evermeer/EVReflection/blob/master/EVReflection/EVReflectionTests/EVReflectionTests.swift#L86

**Comment by garethcurtis** [comment]
Hi. thanks. I did try the cleanup flag but unfortunately that also amends the casing used as well and therefore doesn't work for me in this instance. See below - Count is renamed to count. And Imei is renamed to imei. Obviously it's a bad/inconsistent API that's been provided and nothing to do with your function. So looks like I'll need to stick with my string replace hack. Sorry to waste your time!

{
  "_as" : "a-a",
  "uid" : "GMT_DEV2-11365",
  "_is" : "44-35",
  "Count" : "2"
}
{
  "as" : "a-a",
  "uid" : "GMT_DEV2-11365",
  "count" : "2",
  "is" : "44-35"
}

{
  "ftl" : "Y",
  "uid" : "GMT_DEV2-11365",
  "apk" : "9.2",
  "pwd" : "b1cb755085776cbc75a4425ce11cf3d68433ac5642c1c60ffcef6970df8612e6",
  "Imei" : "344F5D25-1046-4DC6-B9C2-C7E1AAC437B7"
}
{
  "ftl" : "Y",
  "uid" : "GMT_DEV2-11365",
  "apk" : "9.2",
  "pwd" : "b1cb755085776cbc75a4425ce11cf3d68433ac5642c1c60ffcef6970df8612e6",
  "imei" : "344F5D25-1046-4DC6-B9C2-C7E1AAC437B7"
}

**Comment by evermeer** [comment]
Then you could use the toJsonString without automatic key cleanup and create a custom property mapping. Just add this to your object:

```
    override public func propertyMapping() -> [(String?, String?)] {
        return [("_as","as"),("_is","is")]
    }
```
