### ISSUE TITLE
"Invalid json! The data couldn't be read ... "

### ISSUE THREAD

**Issue by daerimin** [evermeer/EVReflection#290]
Hello again!  I wanted to see if it was somehow possible to run down what is causing a stream of these errors in my code.  Everything SEEMS to work as expected, but upon most transactions with my server, I am seeing a long stream of these errors in the console.  I have looked at the incoming JSON and I don't see anything wrong with it.  Would it be possible to output a File & line number in the error message, or perhaps an option to cause this to throw an exception so I could see where the errors are coming from?

Thanks!

**Comment by evermeer** [comment]
In EVReflection this error can come from 3 places dictionaryFromJson, dictionaryArrayFromJson or arrayFromData. If you search for the text 'invalid json' you will find these and you could set a breakpoint on those.

It's strange that you say that everything seems to work. It should return no data if that error happened.

**Comment by daerimin** [comment]
Well, I don't get any exceptions - but I will definitely do what you suggest here.

**Comment by evermeer** [comment]
Is this still an issue?

**Comment by daerimin** [comment]
My apologies for failing to close this issue.  I found that the library has changed a bit from when I first implemented these things a year ago, and I had to re-write portions of my code to make it work.  Thank you again for your help!!
