### ISSUE TITLE
"WARNING:  Did not expect an array for [property].  Will use the first item instead."

### ISSUE THREAD

**Issue by daerimin** [evermeer/EVReflection#291]
This is happening on every instance of `List<String>` in my code.  Please advise.

**Comment by evermeer** [comment]
Is that for classes that have the Realm Object as its base class and the EVReflectable protocol added?
Please make sure that you are using the latest version of EVReflection which is 5.6.1
If you search your solution for 'extension List : EVCustomReflectable' do you find that extension?

**Comment by daerimin** [comment]
Yes, that's correct.

I am using the latest version, as I have it through Pods (I verified it's 5.6.1) but I do not see the extension you mentioned anywhere.

**Comment by evermeer** [comment]
Ah, 
Could it be that you are using:
`pod 'EVReflection'`
Without the Realm aditions like the one for List? You should use
`pod 'EVReflection/Realm'`
Then you should have that List extension

**Comment by evermeer** [comment]
just let me know if this is still a problem
