### ISSUE TITLE
ERROR: Could not create an instance for type Swift.Dictionary<Swift.String, Swift.Array<MyObject>>

### ISSUE THREAD

**Issue by jayfray12** [evermeer/EVReflection#293]
One JSON response that I have should be parsed as type Dictionary&lt;String,Array&lt;MyObject&gt;&gt;. I have successfully parsed this by overriding the setValue method like this:

`override func setValue(_ value: Any!, forUndefinedKey key: String) {
    switch key {
    case "response":
        if let dict = value as? NSDictionary {
            response = Dictionary<String,Array<MyObject>>();
            for (key, value) in dict {
                var listValues = Array<MyObject>();
                if let array = value as? NSArray {
                    for vd in array {
                        listValues.append(MyObject(dictionary: vd as! NSDictionary));
                    }
                }
                response![key as? String ?? ""] = listValues;
            }
        }
        break;
    }
}` 

However, I still get the Error message in the title.  Is there a different way I should be doing this? How do I get the error to go away?

**Comment by evermeer** [comment]
The setValue forUndefinedKey is a fallback solution for handeling issues that can not be handled otherwise. I think that in your case it would be better to use a property converter. Below you can see a sample. It's not for a dictionary, but I think you can easily convert your code to this.

```swift
public class TestObject6: EVObject {
    var isGreat: Bool = false

    override func propertyConverters() -> [(key: String, decodeConverter: ((Any?) -> ()), encodeConverter: (() -> Any?))] {
        return [
            ( // We want a custom converter for the field isGreat
              key: "isGreat"
              // isGreat will be true if the json says 'Sure'
              , decodeConverter: { self.isGreat = ($0 as? String == "Sure") }
              // The json will say 'Sure  if isGreat is true, otherwise it will say 'Nah'
              , encodeConverter: { return self.isGreat ? "Sure": "Nah"})
        ]
    }
}

**Comment by jayfray12** [comment]
Thanks that did the trick!
