### ISSUE TITLE
Install framework using Carthage not working

### ISSUE THREAD

**Issue by waelsaad** [evermeer/EVReflection#298]
Hi, 

I am trying to install the framework using Carthage by adding:-

github "EVReflection/EVReflection" ~> 5.8.0

I am getting this error: 

A shell task (/usr/bin/env git clone --bare --quiet https://github.com/EVReflection/EVReflection.git /Users/X/Library/Caches/org.carthage.CarthageKit/dependencies/EVReflection) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

Any ideas please? Thanks

**Comment by evermeer** [comment]
The path should be  https://github.com/evermeer/EVReflection.git

**Comment by waelsaad** [comment]
Yes thank you very much, it is fixed, I know it was a dumb thing from my part but also it would be nice to have a simple one line instructions with a heading on the front readme for others to clearly see the install path for Carthage. Cheers.

**Comment by evermeer** [comment]
I will have a look at the readme
