### ISSUE TITLE
Unable to determine Swift version for the following pods when 

### ISSUE THREAD

**Issue by DubonYaar** [evermeer/EVReflection#302]
Hi. After updating to Cocopods version 1.6.1, When trying to install EReflection pod, i get following  error :

[!] Unable to determine Swift version for the following pods:
- `EVReflection` does not specify a Swift version and none of the targets (`Example`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
my pod file looks lie this

i also tried installing older versions of EVRefelction and get the same error message.

my pod file looks like that:
platform :ios, '10.0'
target 'Example' do
  use_frameworks!
  pod 'EVReflection'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if ['EVReflection'].include? target.name
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
end

**Comment by evermeer** [comment]
Hello,

I did not specify a swift version for EVReflection because it's compatible with 4.0, 4.2 and 5.0 (beta)
I think it should be solved when you set the swift version on your example project.
(select the Example target, go to build settings. filter on 'swift lang' and set the version.

Regards,
Edwin Vermeer

**Comment by DubonYaar** [comment]
the Example its an Objective-C project, there's no swift section in the build settings
note that i didn't get that error beofre updating Cocoapods to the latest version.

**Comment by DubonYaar** [comment]
I've just fixed it by adding a Swift class file to the Objective-c project. It added the Swift section in the target's build settings. and it now works! 
Thanks
