### ISSUE TITLE
Moya map doesn’t work 

### ISSUE THREAD

**Issue by AdieOlami** [evermeer/EVReflection#304]
I’m trying out with rx but there seems to be nothing like .map(toArray:....)

```
func getNutritionHistoryData(date: Date) -> Observable<[[NutritionHistory]]> {
    
    return self.provider.request(.nutritionHistory(date: Date))
        .map(toArray: [NutritionHistory]) 
}

```
What could be the issue please

**Comment by evermeer** [comment]
Did you add the pod spec
`pod 'EVReflection/MoyaRxSwift'`
And did you add
`import EVReflection`
at the top of that file?

**Comment by AdieOlami** [comment]
Yes I did. I only say Rmap

**Comment by evermeer** [comment]
Ah, true, there were conflicts when using the same .map function between reactive and not. Therefore I had to rename the reactive map to Rmap. Please have a look at the MoyaRxSwiftTests unit test file to see it in action. In your case you should use

```
        provider.request(.nutritionHistory(date: Date)) { (result) in
            switch result {
            case .success(let response):
                do {
                    let parsed = try response.RmapArray(to: NutritionHistory.self)
```

**Comment by evermeer** [comment]
Just reopen this if it's still an issue
