### ISSUE TITLE
EV doesn't parse subtypes if bundle name is changed manually

### ISSUE THREAD

**Issue by yummish** [evermeer/EVReflection#31]
In a project, I set the Bundle name manually to sth else, such as "firstresponder" instead of $(PRODUCT_NAME). I also have the following two classes:
Foo {
var f1: String
var boo: Boo
}

Boo {
var ***
}

When i parse a json to Foo with : Foo(json: data), the Foo.boo is always empty. So I stepped through the json function and then found out that the "NSClassFromString(classStringName)" is always nil because it canno't find class firstresponder.Boo. After I changed the bundle name back to $(PRODUCT_NAME), it works!

I didn't read through the getCleanAppName and I'm new to iOS, but I'm just wondering if it should read the project target instead of the bundle name because I think project target is where you can reference the classes.

Thanks and Cheers!

**Comment by evermeer** [comment]
You could force to use fts by calling EVReflection.setBundleIdentifier(Foo)
I will investigate your suggestion tomorrow.

**Comment by evermeer** [comment]
I have changed it to use the bundle name instead of the identifier In version 2.14.1. Could you please test  if it now works for you?

**Comment by evermeer** [comment]
if you still have a problem with this, then let me know
