### ISSUE TITLE
Can’t install pod 

### ISSUE THREAD

**Issue by icodeuridevice** [evermeer/EVReflection#312]

**Comment by evermeer** [comment]
There are various solutions for this. If you already have the json as a string then you could use something like:

var myArray = [Comic](json: yourJson)

but when you are using Alomofire, have a look at .ResponeArray
or when using Moya have a look at .mapArray
and Moya with RxSwift or ReactiveSwift then look at .map(toArray:

**Comment by manan6166** [comment]
@evermeer Sir ,
Thanks for your important reply

Can you just make me a sample demo using EVReflection/Alamofire to handle this type of API with MVC? 
i am using Alamofire in my project.
API_URL = [https://www.simplifiedcoding.net/demos/marvel/](url) (Sample API)

Thanks And Regards

**Comment by evermeer** [comment]
There are multiple test samples at https://github.com/evermeer/EVReflection/tree/master/UnitTests/AlamofireTests

See for instance https://github.com/evermeer/EVReflection/blob/master/UnitTests/AlamofireTests/AlamofireExternalTests.swift

**Comment by icodeuridevice** [comment]
@evermeer Sir,
its Working now after some changes in my code, thanks
you can delete this issue its not an issue 
This is one of the best library for Swift
