### ISSUE TITLE
Override Hashable.

### ISSUE THREAD

**Issue by VladasZ** [evermeer/EVReflection#319]
Is it possible to implement custom hash from EVObject child? Currently i have following error:
 
![image](https://user-images.githubusercontent.com/10122409/95136972-cbfc3580-076f-11eb-9577-fbf7d9fb1286.png)

**Comment by evermeer** [comment]
The easiest way would be to fork EVReflection, changing the hash function in EVReflectable and use that fork in your project.

What might work is that you create your own extension with the has function and add that to your class definition.
You could get a compile error or it could still get the wrong hash function

```
class Test : EVObject, MyOwnEVReflectable {
}

extension MyOwnEVReflectable where Self: EVObject {
public var hashValue: Int {
        get {
            return Int(EVReflection.hashValue(self))
        }
    }
    
    /**
     Function for returning the hash for the NSObject based functionality
     
     - returns: The hashvalue of this object
     */
    public var hash: Int {
        get {
            return self.hashValue
        }
    }   
}
```
