### ISSUE TITLE
EVReflection does ignoring too late (and goes into an infinite loop)

### ISSUE THREAD

**Issue by vronin** [evermeer/EVReflection#32]
Objects may have circular references:

class Foo : EVObject {
   var bars : Bar[]
}

class Bar : EVObject {
  var foo : Foo

   // Let's ignore foo
    override func propertyMapping() -> [(String?, String?)] {
        return [("foo",nil)]
    }
}

If we will attempt to serialize this to json, it will get into an infinite recursion loop while consruction a dictionary.

PropertyMapping is done later in the game (when the  dictionary is constructed) and won't prevent this infinite loop.

**Comment by evermeer** [comment]
True, there is no support for circular references (yet). I do think it's a good idea to add support for it. reacting on the propertyMapping in an earlier stage could be a way to do this. But I think a better way would be if i detect if the object is already processed. I will add this to my todo list.

**Comment by vronin** [comment]
Thank you. 
The real world case scenario where I hit this is observable/observer. Foo needed to observe Bar's

**Comment by evermeer** [comment]
After some investigation I found out that indeed the propertyMapping is executed too late in more scenario's I just changed that and pushed a new version 2.15.0 to GitHub where that is fixed. You could solve your circular reference issue with this. I also added a unit test that shows how that should work. I added the following 2 test objects:

```
public class Circular1: EVObject {
    var normalProperty: String? = ""
    var startCircle: Circular2?
}

public class Circular2: EVObject {
    var anotherNormalProperty: String? = ""
    var createCircle: Circular1?

    override public func propertyMapping() -> [(String?, String?)] {
        return [("createCircle", nil)]
    }
}
```

Plus the following test:

```
    func testCircular() {
        let circle:Circular1 = Circular1()
        circle.startCircle = Circular2()
        circle.startCircle!.createCircle = circle
        let json = circle.toJsonString()
        print("json = \(json)")
    }
```

Because of this the automatic detection of a circular reference has a lower priority, but it's still on my todo list.

**Comment by vronin** [comment]
Thank you.

**Comment by evermeer** [comment]
I just pushed version 2.31.0 to GitHub and CocoaPods which has support for automatic circular reference detection.

In case of a circular reference you will see json like:

```
json = {
  "normalProperty" : "",
  "startCircle" : {
    "anotherNormalProperty" : "",
    "createCircle" : {
      "_EVReflection_parent_" : "1"
    }
  }
```

The _EVReflection_parent_ key will indicate a circular reference where the 1 indicates that it's the direct parent. If it was the parent of the parent, then you will get a 2... etc...

So from now on there is no need to add a property mapping to manually exclude a possible circular reference.

**Comment by vronin** [comment]
@evermeer Thank you
