### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by Shakihassan** [evermeer/EVReflection#320]
On line 420 of EVReflectable.swift, the method saveToTemp:_:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

On line 438 of EVReflectable.swift, the method saveToDocuments:_:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

Reported by Fortify on Demand Team

**Comment by evermeer** [comment]
If you want encryption, then you could just get the json and store it yourself using the encryption of your choice. If you think there should be an encryption option available, then please create PR that implements that.
