### ISSUE TITLE
Is it possible to work with URL session ?

### ISSUE THREAD

**Issue by maulikshah09** [evermeer/EVReflection#321]
my client project is on url session and used encodable and decodable. Now I want to use your framework with url session.  i used previously your framework and i love your framework for easy to create model.

**Comment by evermeer** [comment]
EVReflection is independent of any network layer and can be user anywhere where you would like to create an object from Json or Json from an object. There are convenience sub libraries for Alamofire and Moya, but it also can work with any other networking library (including anything from Apple. Just define your objects using EVObject as it's base and you can create the objects with the json.
