### ISSUE TITLE
Use NSUTF8StringEncoding in toJSONString

### ISSUE THREAD

**Issue by idelgado** [evermeer/EVReflection#4]
Converting a string with foreign characters to a JSON string and then using that JSON string to construct the object back fails.

EVReflection.toJsonString should use NSUTF8StringEncoding instead of NSASCIIStringEncoding

```
    public class func toJsonString(theObject: NSObject) -> String {
        var toNSDict = EVReflection.toNSDictionary(theObject)
        var error:NSError? = nil
        if var jsonData = NSJSONSerialization.dataWithJSONObject(toNSDict , options: .PrettyPrinted, error: &error) {
            if var jsonString = NSString(data:jsonData, encoding:NSASCIIStringEncoding) {
                return jsonString as String
            }
        }
        return ""
    }
```

**Comment by evermeer** [comment]
You are completely right. I will fix this in a moment. Thanks for reporting this.

**Comment by evermeer** [comment]
The change is pushed to github, I will create a new version with some other fixes tomorrow. If you want to use this version by using cocoapods, then just put this in your podfile:
pod 'EVReflection' , :head

**Comment by idelgado** [comment]
Awesome. Thanks!
