### ISSUE TITLE
toJsonString() for Array

### ISSUE THREAD

**Issue by rafcabezas** [evermeer/EVReflection#40]
I need to convert an object array to JSON to save to a cache file.
Is there any way to do this with EVReflection?
I ended up adding this extension, which works. Just curious if it's necessary, or I'm missing something. Or if you'd like to add to EVReflection:

``` swift
public extension Array {

    ///Convert this array to a json string
    public func toJsonString(performKeyCleanup:Bool = false) -> String {
        var jsonString = "[\n"
        for (index, item) in self.enumerate() {
            if let item = item as? NSObject {
                jsonString += EVReflection.toJsonString(item, performKeyCleanup: performKeyCleanup)
                if index < (self.count - 1) {
                    jsonString += ", \n"
                }
            }
        }
        jsonString += "\n]"

        return jsonString
    }
}
```

**Comment by evermeer** [comment]
Ah, I missed that one, Thanks!

Could you add it to the current Array extension in EVExtensions.swift and do a pull request? I could also do it myself if you like?

Instead of writing json to a file, you could have used NSCoding for this. 
The syntax for that is:
NSKeyedArchiver.archiveRootObject(array, toFile: filePath)
And you can restore it with:
array = NSKeyedUnarchiver.unarchiveObjectWithFile(filePath)

**Comment by evermeer** [comment]
This could also work (Untested):

```
public func toJsonString(performKeyCleanup:Bool = false) -> String {
     return  "[\n" + self.enumerate().map({($0.1 as! NSObject).toJsonString(performKeyCleanup)}) .joinWithSeparator(", \n") + "\n]"
}
```

**Comment by rafcabezas** [comment]
You beat me to it, I was working on something akin your latter solution :P 
Tested and it works for me. Thanks, Edwin!
(the reason it needs to be written to disk as json is because I'm writing unittests for code that actually get the json from the cloud)

**Comment by rafcabezas** [comment]
Slightly shorter:

```
public func toJsonString(performKeyCleanup:Bool = false) -> String {
        return "[\n" + self.map({($0 as! NSObject).toJsonString(performKeyCleanup)}).joinWithSeparator(", \n") + "\n]"
}
```

**Comment by evermeer** [comment]
New version is pushed to GitHub.
