### ISSUE TITLE
Won't compile with Xcode 7.3 beta 2 / Swift 2.2

### ISSUE THREAD

**Issue by rshev** [evermeer/EVReflection#42]
Not a deal breaker, just a

```
Redundant conformance of 'EVObject' to protocol 'CustomDebugStringConvertible'
```

**Comment by evermeer** [comment]
Thanks! Will download the beta this evening and fix this issue.

**Comment by evermeer** [comment]
I just pushed version 2.17.0 to GitHub which is compatible with Xcode 7.3 beta 3

The mentioned compile error was not the only change. There was also a unit test failing because of changed functionality.
