### ISSUE TITLE
Avoid unused properties from JSON without warning

### ISSUE THREAD

**Issue by nonameplum** [evermeer/EVReflection#43]
For now EVReflection is trying to convert every property from json object to swift class. If some property isn't defined in swift class that exist in json then EVReflection prints warning 

> The class 'ClassName' is not key value coding-compliant for the key 'PropertyName'
> There is no support for optional type, array of optionals or enum properties.
> As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more 

It would be nice if we have some solution for this problem more comfortable than `override func setValue(value: AnyObject!, forUndefinedKey key: String)` where we have to define all properties that we want to avoid. In case when there is a lot of them it is not comfortable.

I suggest to add method like:
`func avoidMappingUndefinedProperties -> Bool`
Default it could return `false` but we can have ability to override this method.

**Comment by evermeer** [comment]
I already have the following function that will do this:

```
override public func propertyMapping() -> [(String?, String?)] {
        return [("ignoredProperty",nil), ("propertyInObject","keyInJson")]
    }
```

This function can be used to ignore a property or to map a key to a property with a different name. See the readme for more information

You could also leave the `override func setValue(value: AnyObject!, forUndefinedKey key: String)` empty. You don't have to handle all keys

**Comment by nonameplum** [comment]
Yes, but if I understand this correctly we still have to define all properties that we want to avoid, if I want to avoid 30 properties from json and use only 3 I have a lot work to do. So if I define class with 3 properties that I'm interested in and overriding method like I suggested that `return true` I will have much less work to do.

**Comment by evermeer** [comment]
So you mean that adding a `override func setValue(value: AnyObject!, forUndefinedKey key: String)`without any code in it would not be sufficient?

Would it be OK if I add a general debug log level property? Something Like: None, Errors, Warnings. You could set it to Errors and then you won't see any log messages about not existing keys. Because you don't have to handle them at all. they just output annoying log messages. Or would that be too generic? I can think of a situation where you don't want to see all warnings for one class, but if there are warnings for an other class you do want to see them...

**Comment by nonameplum** [comment]
Oo I see know, I did't understand `override func setValue(value: AnyObject!, forUndefinedKey key: String)`. I was thinking that I have to declare all undefined properties to avoid warning, I didn't test that out. It is ok to me. Warning can stay because it gives the value of information especially when json from API was changed.

**Comment by evermeer** [comment]
OK, then I will close this issue. If you have any questions, then just ask...
