### ISSUE TITLE
fatal error: Array index out of range

### ISSUE THREAD

**Issue by pedrovalentini** [evermeer/EVReflection#44]
Hello,
I'm using EVReflection (2.13.2) in xcode 7.2 and getting this error.

The error occurs when I'm have 2 objects with 
var rows: [Row] = []
But this objects have an number different of itens in this array.

Works
`{"containers": [{
                "rows": [{"kind": "main"}, {"kind": "main"}]
                },
                {
                "rows": [{"kind": "main"}, {"kind": "main"}]
                }]
}`

Crash:
`{"containers": [{
                "rows": [{"kind": "main"}, {"kind": "main"}]
                },
                {
                "rows": [{"kind": "main"}, {"kind": "main"}, {"kind": "main"}]
                }]
}`

![screen shot 2016-02-18 at 14 43 28](https://cloud.githubusercontent.com/assets/103668/13150695/05e53790-d64e-11e5-928d-abea1b78f07c.png)

**Comment by evermeer** [comment]
I will investigate this issue tomorow.

**Comment by evermeer** [comment]
Hi, A little later than expected...

I just added the following unit test and it succeeds without errors.

```
class EVReflectionWorkaroundsTests: XCTestCase {
    override func setUp() {
        super.setUp()
        EVReflection.setBundleIdentifier(TestObject)
    }

    func testCustomDictionary2() {
        let json: String = "{\"containers\": [{ \"rows\": [{\"kind\": \"main\"}, {\"kind\": \"main2\"}] }, {\"rows\": [{\"kind\": \"main3\"}, {\"kind\": \"main4\"}, {\"kind\": \"main5\"}] }] }"
        let c = TestObject8(json: json)
        XCTAssertEqual(c.containers.count, 2, "There should be 1 container")
        if(c.containers.count == 2) {
            XCTAssertEqual(c.containers[0].rows.count, 2, "Container 0 should have 2 rows")
            if(c.containers[0].rows.count == 2) {
                XCTAssertEqual(c.containers[0].rows[0].kind, "main", "Row 0 of container 0 should contain main" )
                XCTAssertEqual(c.containers[0].rows[1].kind, "main2", "Row 1 of container 0 should contain main2" )
            }
            if(c.containers[1].rows.count == 3) {
                XCTAssertEqual(c.containers[1].rows[0].kind, "main3", "Row 0 of container 1 should contain main3" )
                XCTAssertEqual(c.containers[1].rows[1].kind, "main4", "Row 1 of container 1 should contain main4" )
                XCTAssertEqual(c.containers[1].rows[2].kind, "main5", "Row 2 of container 1 should contain main5" )
            }
            XCTAssertEqual(c.containers[1].rows.count, 3, "Container 1 should have 3 rows")
        }
    }
}

class TestObject8: EVObject {
    var containers: [TestObject8Container] = []

}

class TestObject8Container: EVObject {
    var rows: [TestObject8Row] = []
}

class TestObject8Row: EVObject {
    var kind: String?
}

```

Using similar code with this json also works:
`let json = "{\"containers\": [{ \"rows\": [{\"kind\": \"main\"}, {\"kind\": \"main2\"}] }, { \"rows\": [{\"kind\": \"main3\"}, {\"kind\": \"main4\"}] }] }"
`

Could you tell me the difference with your code? Maybe it's something that's fixed in the current version?

**Comment by evermeer** [comment]
Just reopen this issue if you still have a problem with this.
