### ISSUE TITLE
Sub-object properties

### ISSUE THREAD

**Issue by feda12** [evermeer/EVReflection#45]
Hi, 

I am having a little issue. I have a JSON file like this:

`
{
 "Data": {
   "Name": "1",
   "ID": 2
  }
  "Meta": "A class"
}
`

I then have a class:

`public class Foo {
  var Name: String
  var ID: Int
  var Meta: String
 }
`

How do I match Name to `Data.Name`?

I have tried the followings and can't make it work:

`public class Foo {
  public class Data {
    var Name: String
    var ID: Int
  }
  var Meta: String
 }
`

and 

`
override public func propertyMapping() -> [(String?, String?)] {
        return [("Name","Data.Name")]
    }
`

**Comment by evermeer** [comment]
In your case Data is a sub object of Foo. 
So the fields are name and ID are not part of foo like your first sample.
In your 2nd sample you define an inner class. You should define a second class and a property to that.
So In your case your class definition should be:

```
public class Foo { var Data: Bar var Meta: String }
public class Bar { var Name: String var ID: Int }
```

Actually there is a possibility to make it work with your first definition. You then have to override the set value forUndefinedKey and when the key is Data then you should call the setValuesFromDictionary. But still my solution above is better. The object structure would be same as the structure in the json.

**Comment by evermeer** [comment]
I assume it's clear. If you have any questions, then just ask.

**Comment by feda12** [comment]
I did figure it out. Thanks!
