### ISSUE TITLE
Optional Int does not get set from dictionary or json string

### ISSUE THREAD

**Issue by ssttuu** [evermeer/EVReflection#47]
Hi,

Optional Integers are not being set when initializing from `dictionary` or `json` string.  I'm using EVReflection v2.18.0.

Here's an example:

```
class MyUser: EVObject {
    var id: Int?
    var firstName: String?
    var lastName: String?
}
```

```
var userDict = [
    "id": 1,
    "firstName": "First",
    "lastName": "Last"
]
var mu = MyUser(dictionary: userDict)
XCTAssertEqual(mu.toDictionary(), userDict)
```

outputs:

```
[... testCreatesUserFromDictionary] : XCTAssertEqual failed: ("Optional({
    id = "<null>";
    firstName = First;
    lastName = Last;
})") is not equal to ("Optional({
    id = 1;
    firstName = First;
    lastName = Last;
})") - 
```

And same goes for `MyUser(json: "{\"id\":1,\"firstName\":\"First\",\"lastName\":\"Last\"}")`

This is unexpected behavior, right?

It does work when I setup my class like the example:

```
class MyUser: EVObject {
    var id: Int = 0
    var firstName: String?
    var lastName: String?
}
```

Thanks

**Comment by evermeer** [comment]
Actually (and unfortunately) its expected behaviour. See the 'known issues' section in the readme.

**Comment by ssttuu** [comment]
Ah, somehow missed that.  Thanks!
