### ISSUE TITLE
Support custom Dictionary 

### ISSUE THREAD

**Issue by Dimillian** [evermeer/EVReflection#50]
I have some classes which look like this

``` swift
class Document {
   var resources: [String: Resource]
}

class Resource {
 var id: String?
}
```

Is it natively supported by EVReflection ? Or should I implement a custom setValue ?

**Comment by Dimillian** [comment]
It works with that

``` swift
public class Document: BaseModel {

    var resources: Ressources?

}

public class Resource: BaseModel {
    var firstSentence: NSNumber?
}

public class Ressources: BaseModel {
    private var values: Dictionary<String, Resource> = [:]

    subscript(key: String) -> Resource? {
        get {
            return self.values[key]
        }
        set(newValue) {
            self.values[key] = newValue
        }
    }

    override public fund setValue(value: AnyObject!, forUndefinedKey key: String) {
        self[key] = Resource(dictionary: value as! NSDictionary)
    }
}
```

**Comment by evermeer** [comment]
Custom dictionaries should be supported. Also using base classes as your second sample should not be a problem. I will add a unit test for this tomorrow evening. 

I'm not sure about your subscript solution. I think the setValue forUndefinedKey will always set the values["values"] key with the complete dictionary. isn't the value already a complete dictionary with Resource objects?

**Comment by Dimillian** [comment]
I should have put more sample, BaseModel is just

``` swift
public class BaseModel: EVObject {

    var id: String?

}
```

So my code (second sample) is just a workaround, because in the first sample what I got for resources, is nil. 
The JSON is like 

``` json
{
"firstKey" : {"firstSentence": 5},
"secondeKey": {"firstSentence": 35}
}
```

I don't get what you said for my solution, it's just a bit manual and transform the resource dic into a Resource object.

**Comment by evermeer** [comment]
Thanks for explaining this. It should have worked. I will have a look at this as soon as possible.

**Comment by Dimillian** [comment]
Thanks a lot :)

**Comment by evermeer** [comment]
This one is a little harder than expected. A custom dictionary is not based on a NSDictionary. It's a Struct and not an object. Because of this it's not possible to set the value using reflection. Swift has no support to use 'setValue forKey' for structs. So basically it comes down that custom dictionaries can only be supported using a workaround. I made some progress, but it's still not finished.

I have added a unit test for this. It's still commented out because it will crash. I will try to find a solution for this.
https://github.com/evermeer/EVReflection/blob/a942631fe423568c3292eb5b86a0844918e96ba9/EVReflection/EVReflectionTests/EVReflectionWorkaroundsTests.swift#L61-L61

**Comment by Dimillian** [comment]
Hmm you could also provide a specific class with a generic type maybe ? 
I'm thinking something along those line: 

``` swift
public class Subtype<T: EVObject> {
    private var values: Dictionary<String, T> = [:]

    required public init() {

    }

    subscript(key: String) -> T? {
        get {
            return self.values[key]
        }
        set(newValue) {
            self.values[key] = newValue
        }
    }

    override public fund setValue(value: AnyObject!, forUndefinedKey key: String) {
        self[key] = T(dictionary: value as! NSDictionary)
    }
}
```

**Comment by evermeer** [comment]
For a generic type you need a workaround. See https://github.com/evermeer/EVReflection/blob/7b4b3b31f3f9a5a3166cc32acc5501d4bd3ae2c9/EVReflection/EVReflectionTests/EVReflectionWorkaroundSwiftGenericsTests.swift#L97-L97

**Comment by evermeer** [comment]
Support for custom dictionaries is now working (with a workaround)
This has been released as version 2.22.0

For more info see https://github.com/evermeer/EVReflection/blob/289fdbb3a72953d43c506f3b8a762bd193b9b93b/EVReflection/EVReflectionTests/EVReflectionWorkaroundsTests.swift#L62-L62

**Comment by Dimillian** [comment]
@evermeer  It seems to be broken now, and I think it was broken by the memory leak fix.

**Comment by evermeer** [comment]
@Dimillian The unit test mentioned above still succeeds. Do you have any more information about what goes wrong?
