### ISSUE TITLE
Swift ambiguity - JSONModel toDictionary vs EVReflection toDictionary 

### ISSUE THREAD

**Issue by Carpemeid** [evermeer/EVReflection#51]
Thank you for investing a lot of time and effort, taking care and brining object mapping without head aches to Swift but...

So I have an old project in which I'm using models from Obj-C which of course inherit from JSONModel and because now I'm trying to slowly migrate everything to Swift, I'm trying EVReflection, but.......

As you already probably guessed, EVReflection is using the commodity of extending a base class which messes everything up. Instead of providing functionality only through its EVObject it extends directly the most core object Cocoa had from the Obj C times - NSObject. More specifically it has provided the "toDictionary" method in the extension to NSObject, which clearly conflicts with objects which inherited "toDictionary" method from JSONModel. [For testing: 1) make an obj c JSONModel subclass 2) in a Swift project where you're already using EVReflection try to use this JSONModel subclass instance\s method "toDictionary"]

And I do not import EVReflection in the file where I need the JSONModel functionality, but the compiler really doesn't care about this aspect.

I did some dirty fixes, like making a category in obj c which provides a wrapper method for the JSONModel toDictionary... but I suppose a lot of more hidden stones may appear in the future. 

Can you please rethink your decision to extend NSObject and make everything available only through EVObject? or maybe provide a nice solution for not creating this kind of ugly intersections which may appear in the future also against other frameworks?

**Comment by evermeer** [comment]
Thanks for reporting this. My initial intent was to have as much functionality as possible available without the need to extend an object from EVObject. But since in Swift NSObject is also not the default, maybe indeed it's a good idea to move all functionality away from NSObject to EVObject. I will do some tests. I think I have to update some documentation and unit tests. I will keep you posted.

**Comment by Carpemeid** [comment]
You are right and especially because of the fact that we can now observe a big Swift expansion in all directions and on multiple platforms. So it's more guaranteed that somebody developing a Swift backend may need to play with jsons to models conversion and vice versa. 

Or many more others who are playing with other technologies and need a "JSON based" communication.

**Comment by evermeer** [comment]
This has now been pushed to GitHub and cocoapods as version 2.19.0
