### ISSUE TITLE
got "fatal error: NSArray element failed to match the Swift Array Element type"

### ISSUE THREAD

**Issue by lauthu** [evermeer/EVReflection#53]
I really love EVReflection.  It reminds me of the happy time with C#.

But I found under below circumstance, EVReflection will got error ""fatal error: NSArray element failed to match the Swift Array Element type".

Class definition(put them in a different file from ut!):

```
public class A : EVObject{
    public var bs : [B] = []
}

public class B : EVObject{
    public var val : Int = 0
}

```

ut:

```
    func testJSONArray(){
        let a = A()
        let b = B()
        b.val = 1
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        let str = a.toJsonString()
        print(str)
        let a2 = A(json: str)
        print(a2.toJsonString())
    }
```

If I put the class definition in ut file, it works fine.But if I put the class definition in another file of the app target, it just went wrong.

**Comment by evermeer** [comment]
I just copied your test and it works. Also when I put the class definitions in another file. I think this could be a bundle issue. At this moment EVReflection can only be used when all classes are in the same bundle. For a unit test project by default it tries to access the objects from your main bundle. In the unit tests in the EVReflection this is solved by setting the bundle using:
`
        EVReflection.setBundleIdentifier(A)
`
Could you try moving your objects again to that other class and then call the line above at the beginning of your test?

**Comment by lauthu** [comment]
Thank you. I changed to ut code to:

```
func testJSONArray(){
         EVReflection.setBundleIdentifier(A) 
        let a = A()
        let b = B()
        b.val = 1
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        a.bs.append(b)
        let str = a.toJsonString()
        print(str)
        let a2 = A(json: str)
        print(a2.toJsonString())
    }
```

and the error still exist.  You are right, if I put this logic in main bundle, it works fine.~

**Comment by evermeer** [comment]
Solving the multi bundle / framework issue is already recorded as an improvement issue here: https://github.com/evermeer/EVReflection/issues/25
If you think this is not the same issue, then just let me know.
