### ISSUE TITLE
Ignore properties with `nil` values on export only

### ISSUE THREAD

**Issue by JRG-Developer** [evermeer/EVReflection#54]
We're trying to ignore all properties that have `nil` values on _export only_. However, we've found this isn't currently possible to do:

`EVReflection` currently offers two methods you can override to custom serialization/deserialization behavior:  `propertyMapping` and `propertyConverters`.

By overriding `propertyMapping`, you can ignore a property by returning a tuple with a `nil` value (e.g. `("name", nil)`), but AFAIK, it's not possible to do this only for _export_. That is, there's no indicator when this method is called (parameter or otherwise) that an export/import is happening.

By overriding `propertyConverters`, you can return a custom deserializer that returns `nil`, but this doesn't have the desired effect either:  instead of ignoring the key/value in the JSON, the key is set as `null`.

We're happy to contribute a PR that will make it possible to ignore `nil` values on export/import only, but we wanted to make sure we ran this by you first to determine the desired way to do this.

Here are the options we've come up with:

1) Allow `nil` serializer and deserializer returned from `propertyConverters`. If a `nil` serializer/deserializer is received, assume this means the property serialization/deserialization should be skipped.

This is our recommendation.

2) Remove `final` from `toDictionary` and `toJsonString` on `EVObject`.

This is likely the easiest way forward, as we'd then have free control to override these and sanitize as we'd like. However, this feels like a "brute-force" way to do this.

3)  Change `propertyMapping` signature to provide an `importing` boolean or possibly `enum` to indicate whether importing/exporting is happening.

This was our first idea, but unfortunately, this method is used often throughout `EVReflection`, so the change (if possible) may be invasive. Also, we're not sure how to do this in a backwards-compatible manner yet.

Regardless of which route you'd like, we're happy to implement it and add unit tests. We just want to make sure we can get it into master.

@evermeer Which would you like to do?

**Comment by evermeer** [comment]
Great! I see you already have a pull request with a working solution... Let me do some tests before I accept it...

**Comment by JRG-Developer** [comment]
:+1:

**Comment by evermeer** [comment]
The pull request has been merged and is now version 2.20.0
Thanks for the update!

**Comment by JRG-Developer** [comment]
Awesome, thanks!
