### ISSUE TITLE
Issue with using Array<CustomClass> in Custom Class

### ISSUE THREAD

**Issue by rpgmaker** [evermeer/EVReflection#56]
The following does not work properly

class MyOtherClass {
      var id: Int = 0
}

class MyClass {
      var id: Int = 0
      var list = Array<MyOtherClass>()
}

json = {"id": 10, "list": [{"id": 10}]} 
MyClass(json: json) -> Return MyClass with only id and list is an empty array. 

In looking at the code, it seem the issue is with this method implementation: dictionaryAndArrayConversion in EVReflection.swift

Thanks,

**Comment by evermeer** [comment]
You have to make the list array specific so that the type can be inferred. Try this:

Var list: [MyOtherClass] = []

**Comment by rpgmaker** [comment]
That did not fix it. It still return an empty list. I believe something is wrong with this method after debugging it.

```
 private static func dictionaryAndArrayConversion(fieldType:String?, original:NSObject?, var dictValue: AnyObject?) -> AnyObject? {
        if let type = fieldType {
            if type.hasPrefix("Array<") && dictValue as? NSDictionary != nil {
                if (dictValue as! NSDictionary).count == 1 {
                    // XMLDictionary fix
                    if let i = (dictValue as! NSDictionary).generate().next()!.value as? NSArray {
                        dictValue = i
                        dictValue = dictArrayToObjectArray(type, array: dictValue as! [NSDictionary]) as [NSObject]
                    }
                } else {
                    // Single object array fix
                    var array:[NSDictionary] = [NSDictionary]()
                    array.append(dictValue as! NSDictionary)
                    dictValue = array
                }
            } else if type != "NSDictionary" && dictValue as? NSDictionary != nil {
                // Sub object
                dictValue = dictToObject(type, original:original ,dict: dictValue as! NSDictionary)
            } else if type.rangeOfString("<NSDictionary>") == nil && dictValue as? [NSDictionary] != nil {
                // Array of objects
                dictValue = dictArrayToObjectArray(type, array: dictValue as! [NSDictionary]) as [NSObject]
            }
        }
        return dictValue
    }

```

It seem the method is assuming array of data is same as a regular dictionary and because of that it doesn't read the json value properly therefore skipping retrieving the items in the first place.

Thanks,

**Comment by evermeer** [comment]
Thanks for the info... I will have a look at it later this evening...

It's strange that you have a problem with arrays. Here is a unit test using an array of sub objects that does work:
https://github.com/evermeer/EVReflection/blob/b6731d8bfb1af3c126e2cb8f5ff436043836b30a/EVReflection/EVReflectionTests/EVReflectionJsonTests.swift#L63-L63

**Comment by rpgmaker** [comment]
You can close the issue, i believe i made a mistake in my code that made it look like it was not working properly. Thanks for the help

**Comment by evermeer** [comment]
Thanks, no problem, happy coding!
