### ISSUE TITLE
Parsing XML with optional attributes causes crash

### ISSUE THREAD

**Issue by christophercotton** [evermeer/EVReflection#58]
I have an XML document which contains an array of File objects where the format may or may not have the fps attribute.

``` xml
    <file>
       <name>test.mp4</name>
       <format>MP4</format>
    </file>
    <file>
       <name>test.mp4</name>
       <format fps="30">MP4</format>
    </file>
```

The sample classes are:

``` swift
class FormatTest : EVObject {
    var _fps = ""
    var __text = ""
}

class FileTest : EVObject {
    var name = ""
    var format = FormatTest()
}
```

When this gets converted to the FileTest object, it puts a String where the format object is, and causes a crash when you access the object.

From `lldb`:

```
(lldb) po obj.format
MP4

(lldb) po obj.format.dynamicType
__NSCFString

(lldb) po obj.format.__text
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x0).
The process has been returned to the state before expression evaluation.
```

I think the problem is with EVReflection, and it should check the type of the property before storing it. If the property is a string and the property is an `EVObject` it should create that object and pass the string in as the `__text` attribute.

I'll fix the issue if you haven't gotten to it, or don't know about this one.

**Comment by christophercotton** [comment]
My current fix is to add the following lines at the end of `dictionaryAndArrayConversion`

``` swift
            } else if (original is EVObject && dictValue is String) {
                // fixing the conversion from XML without properties
                dictValue = dictToObject(type, original:original, dict:  ["__text": dictValue as! String])
            }
```

**Comment by evermeer** [comment]
Thanks!
I will do some tests with this.

**Comment by evermeer** [comment]
I added this fix and pushed it to GitHub and cocoapods as version 2.20.1

**Comment by christophercotton** [comment]
@evermeer great!
