### ISSUE TITLE
Very Slow Performance Parsing Json

### ISSUE THREAD

**Issue by pedrovalentini** [evermeer/EVReflection#62]
Hello,
I'm testing speed of json libraries and have big problems with EVReflection.

The EVReflection parse is taking **42 SECONDS** to parse this model and this json with recursive objects in lists. Running in the simulator. In the device it crash, out of memory!

Do you think we can change this or it is a real problem of evereflection and we need to migrate to faster libs? I can help to fix if you have some tips about where can be the problem.

Thank you

Model:
`import UIKit
import EVReflection

class SpeedReflection: EVObject {
    var name: String? = nil
    var list: [SpeedReflection]? = nil
}`

JSON:
`{
    "name": "String Long Name",
    "list": [{
             "name": "String Long Name",
             "list": [{
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }]
             }, {
             "name": "String Long Name",
             "list": [{
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }]
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": [{
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }]
             }, {
             "name": "String Long Name",
             "list": [{
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": [{
                               "name": "String Long Name",
                               "list": [{
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }]
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": [{
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": [{
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": [{
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": [{
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }, {
                                                                   "name": "String Long Name",
                                                                   "list": []
                                                                   }]
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }, {
                                                          "name": "String Long Name",
                                                          "list": []
                                                          }]
                                                 }, {
                                                 "name": "String Long Name",
                                                 "list": []
                                                 }]
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }, {
                                        "name": "String Long Name",
                                        "list": []
                                        }]
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }, {
                               "name": "String Long Name",
                               "list": []
                               }]
                      }]
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": []
             }, {
             "name": "String Long Name",
             "list": [{
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }, {
                      "name": "String Long Name",
                      "list": []
                      }]
             }]
}`

**Comment by pedrovalentini** [comment]
Here is a project to test this and others libraries:
https://github.com/pedrovalentini/json-swift-parse-speed-performace

**Comment by evermeer** [comment]
Cool that you are testing this. Of course this is a structure that you will probably never have in real life (I hope 😀). EVReflection will create a Mirror object for every nesting level you have. I would expect it's not fast, but 45 seconds is much more that I would expect. I will do some tests later to see if i'm using some code for this that is not optimal.

EVReflection is not created for optimal speed. It's created to give the developers the easiest possible way to parse from and to an object. Using reflection will always be slower than other solutions. But usually mapping the response from a service will take much less than 0.1 seconds. Compared to the time the network request itself is taken this is not much.

Nice project you have for testing the libraries. Maybe you could also give a short introduction about the different kind of libraries. I think you currently can group all json libraries in these categories:
- object mapping method (with helper functions to quickly access the data)
- reflection based (like EVReflection)
- code generation
  Besides that almost any library I know  is using NSJSONSerialization for the true parsing from and to json. Currently I think there is only one that does the parsing itself.

If you are looking for more json libraries. There are quite some mentioned on the swift-awesome project page.

**Comment by pedrovalentini** [comment]
Thank you for your answer!!
I found the problem in my real life project because I have a JSON bigger than this one =(
I choose to use EVReflection because it is very full of resources like JSONModel for Objective-C, but I get this speed problem. I think that the problem is because we create a log of small objects and EVReflection make a lot of checks and loops to create this objects and properties. 
I can help to improve the lib if you have some tip about where is the speed problem, and I will not need to change the lib of my project to some lib like ObjectMapper (this one take 0.29 seconds to the same model and json parse). After solve this for this project I will publish the result of this research and compare the speed of the swift json model libs.

**Comment by PaulIPS** [comment]
@evermeer I wonder if this might be realted to the memory issue I noticed. I first noticed the JSON parsing being slow, so I profiled the code, and noticed how much memory it was using. 

@pedrovalentini Did you happen to check your memory usage while parsing this JSON?

**Comment by evermeer** [comment]
I have done some initial testing. I think it has to do with the way I pass on data between functions. Currently I use a lot of arrays and dictionaries. In Swift these are structs and passed on by value and not by reference. This means that it will keep on copying data with every function call. If this is indeed the performance issue, then I should convert these to NSArray and NSDictionary. I will try to investigate this.

**Comment by pedrovalentini** [comment]
Yes this make sense, in swift arrays, dictionaries and structs are by default value types, that make copies in memory, this post was very helpful for me: https://developer.apple.com/swift/blog/?id=10
You can check memoize function too.

**Comment by PaulIPS** [comment]
I wonder whats better using  NSArray and NSDictionary instead of Array and Dictionary or placing them inside a class?

**Comment by evermeer** [comment]
Wrapping them in a class might be easier since there are difrencess between the NS\* and Swift. versions. Good tip.

**Comment by evermeer** [comment]
In the latest version all Swift dictionaries and arrays where converted to NSDictionary and NSArray. This resulted in a performance improvement of about 15% but then I also added an autoreleaspool block on 2 crucial locations. That one had a negative impact of about 15% but the memory leak was less than half. I will do some tests using instruments (with and without the autoreleasepool's) this weekend to see if I can find the leak. In my test case I could serialize and deserialize an object with 10000 sub object within 7 seconds. It's not very fast, but it's not 42

**Comment by PaulIPS** [comment]
Nice sounds like it's going in the right direction! 

When I ran into the memory issues, what lead me to even profiling was the time it was taking to go from json to object and object to json. I got okay performance on the simulator, and then when I deployed it to a 6s my times increased by basically double. I figured it had something to do with the memory issues, so I stopped there and . So I would definitely recommend testing on a phone, if you're mostly testing on the simulator.

**Comment by evermeer** [comment]
I added a test app so that the instruments app can be used to track memory usage and leaks. 
I have not used Instruments often. I do see memory leeks, but I don't know how I can track where these come from. Does anyone else know how I can find the source of the leak?

**Comment by rafcabezas** [comment]
Some preliminary profiling in instruments points to cleanupKey as a big offender. I reduced the time it takes to process a big json from 10s to 4s by making it a noop:

``` swift
    private class func cleanupKey(anyObject: NSObject, key: String, tryMatch: NSDictionary?) -> String? {
        return key
    }
```

(this is not a solution -- just reporting my findings)

Update: Maybe for JSONs like mine, we can improve cleanupKey's performance by caching the results. Since the JSON is a big array with the same keys. Let me test this idea.

**Comment by rafcabezas** [comment]
OK, the caching reduced the time from 10s to 6.8s, so while it helped, there's still some problem. I'll keep investigating.

**Comment by rafcabezas** [comment]
I need to go home. but seems the culprit continues to be cleanupKey, specifically the part where stringByReplacingOccurrencesOfString() is used. Seems this is slow, and it's called a lot. 
Need to check my caching, but Xcode keeps crashing, so I'll try again later.

![screen shot 2016-04-29 at 3 36 05 pm](https://cloud.githubusercontent.com/assets/1199743/14927475/2de494b6-0e20-11e6-9327-dde0ff79cda9.png)

**Comment by evermeer** [comment]
Apparently Swift Strings are slow. For a nice article about that see:
http://jakubturek.pl/blog/2015/06/27/using-swifts-string-type-with-care/
It looks like using NSString instead of String or enforcing UTF16 might solve the problem.

**Comment by rafcabezas** [comment]
Cool. I'll check that out. Results of some improvements: (pull request coming)
BASE = Baseline
MAX cleanup = if cleanup is removed (the goal with cleanupKey improvements is to get as close to this as possible)

![screen shot 2016-04-30 at 4 30 57 pm](https://cloud.githubusercontent.com/assets/1199743/14938430/0b7e1dda-0ef1-11e6-8f79-1e892ff8f2af.png)

**Comment by rafcabezas** [comment]
@pedrovalentini Please see if https://github.com/evermeer/EVReflection/issues/79 helped with your issue. I see a 50% improvement on my end.

**Comment by evermeer** [comment]
I just added a caching mechanism in the toDictionary function and pushed that to GitHub and CocoaPods as version 2.29.0. In the test app this improved the performance by about 30%. The memory leak is now also much lower.

**Comment by evermeer** [comment]
OK @pedrovalentini , I think I can close this issue. The testcode that you created (with a slight modification, see PR https://github.com/pedrovalentini/json-swift-parse-speed-performace/pull/1) now runs very vast. When I run your testcode I get the following output when using the EVReflection 2.29.0 version on an iPhone 6S is:

readFile
Tailor: START PARSE
CRASH!?
readFile
Tailor: START PARSE
CRASH!?
readFile
UNBOX: START PARSE
Optional("String Long Name") Optional("String Long Name")
UNBOX: FINISH PARSE IN SECONDS 0.00763100385665894
readFile
UNBOX: START PARSE
Optional("String Long Name") Optional("String Long Name")
UNBOX: FINISH PARSE IN SECONDS 0.00822603702545166
readFile
OBJECTMAPPER2: START PARSE
Optional("String Long Name") Optional("String Long Name")
OBJECTMAPPER2: FINISH PARSE IN SECONDS 0.00934898853302002
readFile
OBJECTMAPPER2: START PARSE
Optional("String Long Name") Optional("String Long Name")
OBJECTMAPPER2: FINISH PARSE IN SECONDS 0.0093960165977478
readFile
SpeedArgo: START PARSE
String Long Name String Long Name
SpeedArgo: FINISH PARSE IN SECONDS 0.0174559950828552
readFile
SpeedArgo: START PARSE
String Long Name String Long Name
SpeedArgo: FINISH PARSE IN SECONDS 0.016789972782135
readFile
EVREFLECTION: START PARSE
Optional("String Long Name") Optional("String Long Name")
EVREFLECTION: FINISH PARSE IN SECONDS 0.0772730112075806
readFile
EVREFLECTION: START PARSE
Optional("String Long Name") Optional("String Long Name")
EVREFLECTION: FINISH PARSE IN SECONDS 0.0772199630737305

**Comment by axialraf** [comment]
Awesome! I'll have to check this out!

**Comment by PaulIPS** [comment]
Nice! Looking forwards to giving this new build a try.
