### ISSUE TITLE
Update EVReflection to XCode 7.3

### ISSUE THREAD

**Issue by vronin** [evermeer/EVReflection#63]
XCode 7.3 complains that EVObject doesn't need to have CustomDebugStringConvertible in the declaration.

**Comment by evermeer** [comment]
I think you are testing with an old version. I changed this some time ago.

See it's now commented out in: https://github.com/evermeer/EVReflection/blob/master/EVReflection/pod/EVObject.swift#L13

**Comment by vronin** [comment]
Sorry. You right. I used old one.
