### ISSUE TITLE
I Got AN ERROR  WITH  this JSON String!Help!!

### ISSUE THREAD

**Issue by hhyymm** [evermeer/EVReflection#64]
{
  "status" : 0,
  "data" : [
    {
      "PriceCount" : "8.50",
      "Remark" : "",
      "OrderId" : "",
      "GoodsList" : [
        {
          "Unit" : "斤",
          "BuyCount" : 1,
          "GoodsPic" : "",
          "GoodsName" : "",
          "BuyPrice" : 8.5,
          "GoodsDetail" : "口感",
          "GoodsId" : "6a4ee4ae-c1f3-4ba2-a267-04f5e193dd85",
          "OriginalPrice" : 9,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "8.50",
      "Remark" : "",
      "OrderId" : "20160330112023670746",
      "GoodsList" : [
        {
          "Unit" : "斤",
          "BuyCount" : 1,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160310103712.png",
          "GoodsName" : "黄金帅苹果",
          "BuyPrice" : 8.5,
          "GoodsDetail" : "口感新鲜",
          "GoodsId" : "6a4ee4ae-c1f3-4ba2-a267-04f5e193dd85",
          "OriginalPrice" : 9,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "8.50",
      "Remark" : "",
      "OrderId" : "20160329175029050163",
      "GoodsList" : [
        {
          "Unit" : "斤",
          "BuyCount" : 1,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160310103712.png",
          "GoodsName" : "黄金帅苹果",
          "BuyPrice" : 8.5,
          "GoodsDetail" : "口感新鲜",
          "GoodsId" : "6a4ee4ae-c1f3-4ba2-a267-04f5e193dd85",
          "OriginalPrice" : 9,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "8.50",
      "Remark" : "",
      "OrderId" : "20160329112553781815",
      "GoodsList" : [
        {
          "Unit" : "斤",
          "BuyCount" : 1,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160310103712.png",
          "GoodsName" : "黄金帅苹果",
          "BuyPrice" : 8.5,
          "GoodsDetail" : "口感新鲜",
          "GoodsId" : "6a4ee4ae-c1f3-4ba2-a267-04f5e193dd85",
          "OriginalPrice" : 9,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "8.50",
      "Remark" : "",
      "OrderId" : "20160328160717612823",
      "GoodsList" : [
        {
          "Unit" : "斤",
          "BuyCount" : 1,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160310103712.png",
          "GoodsName" : "黄金帅苹果",
          "BuyPrice" : 8.5,
          "GoodsDetail" : "口感新鲜",
          "GoodsId" : "6a4ee4ae-c1f3-4ba2-a267-04f5e193dd85",
          "OriginalPrice" : 9,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "28.80",
      "Remark" : "",
      "OrderId" : "20160328152442225583",
      "GoodsList" : [
        {
          "Unit" : "份",
          "BuyCount" : 1,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160315041215.png",
          "GoodsName" : "新鲜鸡蛋（散装）30枚 约2kg\/份",
          "BuyPrice" : 28.8,
          "GoodsDetail" : "新鲜健康",
          "GoodsId" : "3c0bc1a1-86e9-46d5-a379-d3e225148fc4",
          "OriginalPrice" : 29,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "4560.00",
      "Remark" : "",
      "OrderId" : "20160328101203382586",
      "GoodsList" : [
        {
          "Unit" : "瓶",
          "BuyCount" : 38,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160315040019.png",
          "GoodsName" : "金龙鱼花生油5L",
          "BuyPrice" : 120,
          "GoodsDetail" : "健康油，喝好油",
          "GoodsId" : "b062cd0d-dca2-4bf0-bae9-4352071e39f6",
          "OriginalPrice" : 125,
          "Describe" : "非转基因;5S压榨"
        }
      ]
    },
    {
      "PriceCount" : "17.00",
      "Remark" : "",
      "OrderId" : "20160328101157282871",
      "GoodsList" : [
        {
          "Unit" : "斤",
          "BuyCount" : 2,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160310103712.png",
          "GoodsName" : "黄金帅苹果",
          "BuyPrice" : 8.5,
          "GoodsDetail" : "口感新鲜",
          "GoodsId" : "6a4ee4ae-c1f3-4ba2-a267-04f5e193dd85",
          "OriginalPrice" : 9,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "5012.00",
      "Remark" : "",
      "OrderId" : "20160328101150569734",
      "GoodsList" : [
        {
          "Unit" : "斤",
          "BuyCount" : 179,
          "GoodsPic" : "http:\/\/103.21.118.204:8070\/\/UploadFiles\/GoodsImage\/20160310103913.png",
          "GoodsName" : "新疆阿克苏冰糖心苹果",
          "BuyPrice" : 28,
          "GoodsDetail" : "产自新疆，味道可口",
          "GoodsId" : "01e65a03-2115-4852-9f1f-363b7dcf06b6",
          "OriginalPrice" : 30,
          "Describe" : "新鲜"
        }
      ]
    },
    {
      "PriceCount" : "45.60",
      "Remark" : "",
      "OrderId" : "20160325115107019274",
      "GoodsList" : [

```
  ]
}
```

  ],
  "msg" : "获取成功",
  "total" : 12
}

fatal error: NSArray element failed to match the Swift Array Element type
Printing description of mi.displayStyle:
▿ Optional<DisplayStyle>
- Some : Swift.Mirror.DisplayStyle.Optional

The third EVObject Get ThisError

**Comment by hhyymm** [comment]
EVReflection.swift inLine 530 if mi.displayStyle == .Optional ...

**Comment by evermeer** [comment]
Could you show me your class definitions?

**Comment by evermeer** [comment]
I did not test it, but I think jour object model should be something like:

```
class Result: EVObject {
    var status: NSNumber?
    var data: [Data]?
    var msg: String?
    var total: NSNumber?
}

class Data: EVObject {
    var PriceCount: NSNumber?
    var Remark: String?
    var OrderId: String?
    var GoodsList: [Good]?
}

class Good: EVObject {
    var Unit: String?
    var BuyCount: NSNumber?
    var GoodsPic: String?
    var GoodsName: String?
    var BuyPrice: NSNumber?
    var GoodsDetail: String?
    var GoodsId: String?
    var OriginalPrice: NSNumber?
    var Describe: String?
}

```

**Comment by evermeer** [comment]
Just let me know if you still have problems with this.
