### ISSUE TITLE
JSON Serialization: ignore default values

### ISSUE THREAD

**Issue by realenginerd** [evermeer/EVReflection#66]
We want to be able to generate JSON strings that do not contain certain values like `nil`, `""`, and `false` when an object is serialized. For example, given the following class

```
class Foo: EVObject {
    private let statement = "Lorem Ipsum"
    var truth = false

    func bar() -> Foo {
        truth = true
        return self
    }
}
```

`Foo().getJsonObject()` would return

```
{
    "statement": "Lorem Ipsum"
}
```

and `Foo().bar().getJsonObject()` would return

```
{
    "statement": "Lorem Ipsum",
    "truth": true
}
```

Is there a way to do this in EVReflection?

**Comment by evermeer** [comment]
You could use the propertyMapping function for that. A simple implementation would be:

```
    override public func propertyMapping() -> [(String?, String?)] {
        return [("truth", nil)]
    }

```

But then the truth property will always be ignored. In your case you want to make that conditional depending on the value

```
    override public func propertyMapping() -> [(String?, String?)] {
        var r = [(String?, String?)]()
        if !truth {
             r.add(("truth", nil))
        }
        return r
    }
```

You could then do the same with the other properties.

**Comment by realenginerd** [comment]
Very good; this accomplishes our need for now.
