### ISSUE TITLE
EVObject is unavailable, cannot find swift declaration for this class

### ISSUE THREAD

**Issue by jovirus** [evermeer/EVReflection#67]
I just include this framework file into my project.

I can deploy to the phone, but not I can not build it on generic iOS device.

This issue is called "EVObject is unavailable, cannot find swift declaration for this class"

**Comment by evermeer** [comment]
At the top of your class you need to add the line:

```
import EVReflection
```

**Comment by jovirus** [comment]
hi～
i have added those lines.
i managed to make it work on iphone, but when i want to build for simulatior/generic devices, it fails, the errors states as the title. I guess it might comes problem with xcode. -the link layer is not working properly. 

/Jiajun

**Comment by evermeer** [comment]
That's strange... If it compiles for your iPhone, then it should also work in the simulator... 
Could you show me the complete build output? Maybe there is more information about your problem there.

**Comment by evermeer** [comment]
If you still have this error, then please let me know.

**Comment by ttsik** [comment]
Hi guys, I having a similar issue when building for release. when I build for debug everything works as expected.

I am using Xcode 8.3.

The exact error I am getting is 
'EVObject' is unavailable: cannot find Swift declaration for this class
'EVObject' has been explicitly marked unavailable here

Thanks a lot in advance for the help
