### ISSUE TITLE
EVReflection will crash on iOS7, with xcode 7.3, swift 2.2.

### ISSUE THREAD

**Issue by neil-wu** [evermeer/EVReflection#69]
I create a small demo to show this crash on iOS7 device.

[open the demo page](https://github.com/neil-wu/testEVReflection)

**Comment by evermeer** [comment]
As you can see the first non EVReflection line is ast frame #18 where a Mirror of the object is created. The crash is within the code that is creating the Mirror. This looks like a Swift bug.
I found this issue reported at: https://bugs.swift.org/browse/SR-1036

**Comment by neil-wu** [comment]
Yep, seems like a Swift bug. :)

**Comment by evermeer** [comment]
Tanks for closing this issue. But  Sice its à bug that prevents EVReflection to work on iOS7, i would like to keep it open so that i can track any change to the situation.

**Comment by neil-wu** [comment]
:+1:  Waiting for Apple fix this bug as soon as possible. I will also keep my eye on it.

**Comment by neil-wu** [comment]
Good news. Apple Developer has fix this bug, hope the fix will ship in Xcode as soon as possible
[SR-1096](https://bugs.swift.org/browse/SR-1096)

**Comment by neil-wu** [comment]
In the latest xcode 7.3.1(7D1014), this bug is fixed. Just update your xcode from Mac App Store.
