### ISSUE TITLE
Why the boolean value can not be reflected?

### ISSUE THREAD

**Issue by abellee** [evermeer/EVReflection#72]
serverside response a boolean value, true or false,
but seem like can not reflect to Bool, but String or NSNumber.

and another question is, number only can reflect to NSNumber?
if I set the value type of model to Int, that will be nil, but String or NSNumber

**Comment by evermeer** [comment]
You can use a bool. See:
https://github.com/evermeer/EVReflection/blob/master/EVReflection/EVReflectionTests/EVReflectionJsonTests.swift#L181

No, you can also use Int, but if you want to use a nullable int (Int?) then you need to implement a workaround that you can find in the workaroundtest class
