### ISSUE TITLE
Cannot find interface declaration for 'EVObject'

### ISSUE THREAD

**Issue by realenginerd** [evermeer/EVReflection#75]
I have a linking issue with one of my projects. When I build my project, the linker says it cannot find EVObject in the generated `-Swift.h` file:

![screen shot 2016-04-25 at 9 06 24 am](https://cloud.githubusercontent.com/assets/3527178/14786530/fb5f440e-0ac4-11e6-9099-5f38b52913e1.png)

I have written `import EVReflection` in the .swift file for `DSIBaseEvent`, and I have EVReflection iOS as one of my dependencies in the Build Phases tab. What can I be missing? Please advise. Thanks in advance!

**Comment by evermeer** [comment]
Did you add EVReflection using cocoapods? Then a dependency to the pod library (which will be added when doing a pod install) plus the `import EVReflection` would already be sufficient. 

could you try doing a full clean with:  `shift option command K`

**Comment by realenginerd** [comment]
No, I added it as a submodule. That was why I had to manually configure the dependency. 

I tried rebuilding after a full clean. Still received the same errors :(

**Comment by realenginerd** [comment]
I found a way around this! It turns out that I was importing my `-Swift.h` file into a `.mm` file. Once I refactored my code so that the `-Swift.h` file was no longer referenced in the `.mm` file, this issue went away, and I was able to build successfully.

**Comment by evermeer** [comment]
Great to hear it's solved!
