### ISSUE TITLE
Convert multiple json properties to another class

### ISSUE THREAD

**Issue by maarek** [evermeer/EVReflection#76]
Is it possible to take in multiple properties and convert them to a new type

{ "a"="foo", "b"="bar", "c"="baz"}

class MyClass: EVObject {
    var ab: ABClass
    var c: String
   // Convert "a" and "b" into object ABClass even though json is not defined as such
}

class ABClass:EVObject {
    var a: String
    var b: String
}

**Comment by evermeer** [comment]
When you do this, then the setValue forUndefinedKey will be caled on the MyClass object for the key's a and b. You could handle those and put them in a sub object. The code will look like this (untested, out of my head)

```
class MyClass: EVObject {
   var ab: ABClass = ABClass() // Make sure there is an instance or you have to add code for checking that in the setValue forUndefinedKey
   var c: String

    override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        switch key {
        case "a":
            ab.a = value as! String
        case "b":
            ab.b = value as! String
        default:
            NSLog("WARNING: setValue for key '\(key)' should be handled.")
        }
    }
}
```
