### ISSUE TITLE
required initializer must be accessible as its enclosing type error

### ISSUE THREAD

**Issue by kerem1905** [evermeer/EVReflection#82]
EVReflection (2.32.0) gives "required initializer must be accessible as its enclosing type error" with code below

```
public class ResponseModel<T where T:NSObject> : BaseModel,EVGenericsKVC {

    var status:StatusModel?
    var content: T = T()
    var array: [T] = [T]()

    public override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        switch key {
        case "data":
            content = value as! T
        case "array":
            array = value as! [T]
        default:
            print("---> setValue '\(value)' for key '\(key)' should be handled.")
        }
    }
}



public class BaseModel : EVObject {

}
```

**Comment by evermeer** [comment]
When using generict the init should be required. Usually having NSObject (which is the base of EVObject) as a base class already ensures that the init is required but when using generics this is not the case. You have to add this to your ResponseModel class:

```
    required public init() {
        super.init()
    }
```

**Comment by kerem1905** [comment]
Thank you, you may add consttructor to test class

**Comment by evermeer** [comment]
@kerem1905 What do you mean? it's already in the test class. See [testclass on github](https://github.com/evermeer/EVReflection/blob/9fdb8a8f4c6bf97af309209c0100fab15f616dfd/EVReflection/EVReflectionTests/EVReflectionWorkaroundSwiftGenericsTests.swift#L101-L101)
