### ISSUE TITLE
archivedDataWithRootObject ignores the property mapping

### ISSUE THREAD

**Issue by mitkodev** [evermeer/EVReflection#83]
Hey,

i've recently upgraded from 2.30.0 to 2.33 and 

```
let tokenData:NSData = NSKeyedArchiver.archivedDataWithRootObject(token)
```

stopped working, because the conversation options by default in encodeWithCoder function are set to .None and i receive an error when trying to archive my custom objects
<img width="739" alt="screen shot 2016-05-21 at 7 04 23 pm" src="https://cloud.githubusercontent.com/assets/4931013/15449486/cd45efb4-1f87-11e6-9a67-06fc83355263.png">

i have defined propertyMapping for the properties that are throwing error that set the to 

EDIT: the screenshot may be misleading, the error is logged right after the archiveDataWithRootObject line, the debug information is easy to be found in your source :)

**Comment by evermeer** [comment]
Ah... I assumed there would never be a reason to do any sort of conversion when encoding and decoding an object. I have now changed the `.None` into `.DefaultNSCoding` This .`DefaultNSCoding` is by default set to .None but you can change that using a statement like this:
`ConversionOptions.DefaultNSCoding = [.PropertyMapping]`
I think this will solve your issue.

**Comment by mitkodev** [comment]
great, works as usual now, thank you for the quick response
