### ISSUE TITLE
EVReflection performance for deep trees

### ISSUE THREAD

**Issue by vronin** [evermeer/EVReflection#85]
I use EVReflection pretty much for all data within the app.

EVReflection version is 2.24.0

I have one big tree with bunch of objects in it which I serialize and deserialize in  multiple places.

The performance for a small tree is great. If I have just a dozen of objects in it then it's not visible at all. However, I am noticing a lag as soon as number of objects starts to grow, 

I wrote follow code to measure how does it work (sorry, I just slapped it together, so code isn't clean).
This code creates either wide tree (one node which has  N subnodes) or a tall tree (each node has just one next node which in it's turn will have one next node).

```
class Tree : EVObject {
    var someValue: Int = 5
    var tallBranch: Tree?
    var wideBranches: [Tree] = []
}

 func buildDeepTree(i: Int) -> Tree {
        var treeBranch = Tree()
        let treeTop = treeBranch
        for _ in 0..<i {
            treeBranch.tallBranch = Tree()
            treeBranch = treeBranch.tallBranch!
        }
        return treeTop
    }

    func buildWideTree(i: Int) -> Tree {
        let treeTop = Tree()
        for _ in 0..<i {
            treeTop.wideBranches.append(Tree())
        }
        return treeTop
    }

    func measureDepth() {
        var startTime: Double
        var endTime: Double
        for i in 1..<10 { // Gradually increase number of objects
            let tree = buildDeepTree(i)

            startTime = CACurrentMediaTime()
            let json = tree.toJsonString()
            endTime = CACurrentMediaTime()
            print("Iterations:\(i), Type: Width, Action:   ToJson, Time (per leaf) \((endTime-startTime)/Double(i))")

            startTime = CACurrentMediaTime()
            _ = Tree(json: json)
            endTime = CACurrentMediaTime()
            print("Iterations:\(i), Type: Width, Action: FromJson, Time (per leaf) \((endTime-startTime)/Double(i))")

        }
    }

    func measureWidth() {
        var startTime: Double
        var endTime: Double
        for i in 1..<10 { // Gradually increase number of objects
            let tree = buildWideTree(i)

            startTime = CACurrentMediaTime()
            let json = tree.toJsonString()
            endTime = CACurrentMediaTime()
            print("Iterations:\(i), Type: Depth, Action:   ToJson, Time (per leaf) \((endTime-startTime)/Double(i))")

            startTime = CACurrentMediaTime()
            _ = Tree(json: json)
            endTime = CACurrentMediaTime()
            print("Iterations:\(i), Type: Depth, Action: FromJson, Time (per leaf)  \((endTime-startTime)/Double(i))")
        }

    }

```

Below are results which I got. 

Please notice that for wide tree  per node time (to serialize and deserialize) doesn't change. I ran it up to 100 and it's pretty much 0.0005 seconds/per node to serialize and 0.003 seconds/per node to deserialize. As result a total time (for serialization/deserialization) is a linear function of number of nodes.

However, as soon as I ran it for a deep tree I noticed that per node time goes up. It looks like the time per node triples each time when you add one more node. As result total time goes up exponentially for a tall tree.

My project doesn't have that tall tree. I believe right now it's something like 4-5 tall. However, it's enough to start noticing lag.

Iterations:1, Type: Width, Action:   ToJson, Time (per leaf) 0.00305679166740447
Iterations:1, Type: Width, Action: FromJson, Time (per leaf)  0.00833558333397377
Iterations:2, Type: Width, Action:   ToJson, Time (per leaf) 0.00151637499948265
Iterations:2, Type: Width, Action: FromJson, Time (per leaf)  0.00643897916688729
Iterations:3, Type: Width, Action:   ToJson, Time (per leaf) 0.0011751527775535
Iterations:3, Type: Width, Action: FromJson, Time (per leaf)  0.00477194444404934
Iterations:4, Type: Width, Action:   ToJson, Time (per leaf) 0.000808937500096363
Iterations:4, Type: Width, Action: FromJson, Time (per leaf)  0.00454497916643959
Iterations:5, Type: Width, Action:   ToJson, Time (per leaf) 0.000783341666465276
Iterations:5, Type: Width, Action: FromJson, Time (per leaf)  0.00436518333335698
Iterations:6, Type: Width, Action:   ToJson, Time (per leaf) 0.000768590277706001
Iterations:6, Type: Width, Action: FromJson, Time (per leaf)  0.00413909027762808
Iterations:7, Type: Width, Action:   ToJson, Time (per leaf) 0.000817339285796541
Iterations:7, Type: Width, Action: FromJson, Time (per leaf)  0.00417254166677594
Iterations:8, Type: Width, Action:   ToJson, Time (per leaf) 0.000705229166669596
Iterations:8, Type: Width, Action: FromJson, Time (per leaf)  0.00408499479158309
Iterations:9, Type: Width, Action:   ToJson, Time (per leaf) 0.000717125000139478
Iterations:9, Type: Width, Action: FromJson, Time (per leaf)  0.00412606944438368
Iterations:1, Type: Depth, Action:   ToJson, Time (per leaf) 0.0031807083341846
Iterations:1, Type: Depth, Action: FromJson, Time (per leaf) 0.00653487500130723
Iterations:2, Type: Depth, Action:   ToJson, Time (per leaf) 0.00490287499997066
Iterations:2, Type: Depth, Action: FromJson, Time (per leaf) 0.00717837499996676
Iterations:3, Type: Depth, Action:   ToJson, Time (per leaf) 0.00964609722238189
Iterations:3, Type: Depth, Action: FromJson, Time (per leaf) 0.0123681666664197
Iterations:4, Type: Depth, Action:   ToJson, Time (per leaf) 0.0216332916666033
Iterations:4, Type: Depth, Action: FromJson, Time (per leaf) 0.0239672604166117
Iterations:5, Type: Depth, Action:   ToJson, Time (per leaf) 0.0516643333332468
Iterations:5, Type: Depth, Action: FromJson, Time (per leaf) 0.0550548750001326
Iterations:6, Type: Depth, Action:   ToJson, Time (per leaf) 0.130059333333217
Iterations:6, Type: Depth, Action: FromJson, Time (per leaf) 0.13164445833354
Iterations:7, Type: Depth, Action:   ToJson, Time (per leaf) 0.336460023809455
Iterations:7, Type: Depth, Action: FromJson, Time (per leaf) 0.339349833333472
Iterations:8, Type: Depth, Action:   ToJson, Time (per leaf) 0.879812671875015
Iterations:8, Type: Depth, Action: FromJson, Time (per leaf) 0.885514380208178
Iterations:9, Type: Depth, Action:   ToJson, Time (per leaf) 2.34448092129646
Iterations:9, Type: Depth, Action: FromJson, Time (per leaf) 2.3386666759258

**Comment by vronin** [comment]
I just upgraded to the latest version. Apparently this issue is fixed already and overall performance is improved.

Thank a lot ;)

**Comment by evermeer** [comment]
Great to hear it's ok now. Indeed i have done some performance improvements in the last month.
