### ISSUE TITLE
Modification to XMLDictionary fix of func dictionaryAndArrayConversion

### ISSUE THREAD

**Issue by slcott** [evermeer/EVReflection#88]
There was a bug with https://github.com/evermeer/EVReflection/issues/84

for this dataset

```
    func testXmlNoteString() {
        let xmlString = xmlNoteString()
//      let dictionary = NSDictionary(XMLString: xmlString)
        let dictionary = [
            "notations" :     [
                "tied" :         [
                    [
                        "_type" : "stop",
                    ],
                    [
                        "_orientation" : "over",
                        "_type" : "start",
                    ],
                ],
            ]
        ]
//      print(dictionary)
        let obj = Note(dictionary: dictionary)
        let str = EVReflection.description(obj)
        print(EVReflection.description(obj))
    }
```

```
class Note: EVObject {
   var notations: [Notations]?
}

class Notations: EVObject {
   var tied: [Tied]?
}

class Tied: EVObject {
    var _type: StartStopContinueEnum = .none
    var _orientation: OrientationEnum?
}
```

I made the following changes to `private static func dictionaryAndArrayConversion` and it fixed the issue on my end.

```
                    // XMLDictionary fix
                    if let i = (dictValue as? NSDictionary)?.generate().next()?.value as? NSArray {
//                        dictValue = i
                        var array: [NSDictionary] = [NSDictionary]()
                        for (k,v) in  (dictValue as? NSDictionary)! {
                            array.append(dictValue as? NSDictionary ?? NSDictionary())
                        }
//                        dictValue = dictArrayToObjectArray(type, array: (dictValue as? [NSDictionary]) ?? [NSDictionary](), conversionOptions: conversionOptions) as NSArray
                        dictValue = dictArrayToObjectArray(type, array: array, conversionOptions: conversionOptions) as NSArray
                    } else {
```

**Comment by evermeer** [comment]
Hi, I'm trying to find out what's to do with your test. That XMLDictionary fix was there so that you did not need an extra object level when deserializing xml with XMLDictionary.

Was your original XML something like this?

```
<notations>
  <tied>...</tied>
  <tied>...</tied>
</notations>
```

When I change your Note class to this it works as expected:

```
class Note: EVObject {
    var notations: [Tied]?
}
```

When parsing XML you often get an extra dictionary with only 1 element which is the array that you actually want. My original code made the (less than optimal) assumption that when there was only 1 element with an array that this was indeed the case. Also when removing the entire `if let i = ...` and only performing the else your code will also work. I think I have to add some additional checks to see if there is a key match and only then do the additional XMLDictionary fix. I will play around with this to find a better solution.

**Comment by evermeer** [comment]
OK,  I think I have it working in the most optimal way. Now your code will work with both object declarations.

```
class Note: EVObject {
    var notations: [Notations]?
}
```

and

```
class Note: EVObject {
    var notations: [Tied]?
}
```

So from now on it's up to the developer to decide if an extra object level is indeed what you want.

I will first do some additional tests before pushing this to GitHub...

**Comment by evermeer** [comment]
I pushed this fix to GitHub and CocoaPods as version 2.33.4

You can see the unit test that tests both situations at:
https://github.com/evermeer/EVReflection/blob/0c3240a064ced53a8d601e9106cd270e95b8254c/EVReflection/EVReflectionTests/EVReflectionIssue88.swift#L42

**Comment by slcott** [comment]
You are correct, the xml causing the issues is:

```
 <note default-x="10">
        <pitch>
          <step>C</step>
          <alter>1</alter>
          <octave>5</octave>
        </pitch>
        <duration>8</duration>
        <tie type="stop"/>
        <tie type="start"/>
        <voice>1</voice>
        <type>quarter</type>
        <stem default-y="18">up</stem>
        <staff>1</staff>
        <notations>
          <tied type="stop"/>
          <tied orientation="over" type="start"/>
        </notations>
      </note>
```

I tested with the latest push and all my tests pass (~250,000 lines of xml)
Thanks.

**Comment by evermeer** [comment]
Wow 250.00 lines of xml is huge! How's the performance of that?

**Comment by slcott** [comment]
It's 250k lines total, actually split into about 10 files. It takes about a minute total, about five seconds for each, and memory usage peaks at about 130 mb. 

This is for an iOS app and I wanted to test the library out against a large dataset to verify correctness and performance before proceeding further with other tasks. I

t works well and I hope my bug reports have made it more robust for other users.
