### ISSUE TITLE
How to compare class & AnyObject?

### ISSUE THREAD

**Issue by classified** [evermeer/EVReflection#89]
Let's say , i have 3 EVObject class. `class a{} , class b{} , class c{}`. Now I have added these 3 classes to an Array type of AnyObject. now i need to get which type of object this is to populate data in tableview. i need to check that  `object == class a() OR object == class b() OR object == class c()`. What should i need to do to make this work?

**Comment by evermeer** [comment]
in the cellForRowAtIndexPath you will get the data item from your array with something like:
`let myData: AnyObject = myDataArray[indexPath.row]`
Then you can check the actual type using something like:

```
if myData is a { 
...
} else if myData is b { 
 ...
}
```

Or if the cell differences are big: You could also get the myData.dynamicType as a string and then use that in the identifier to dynamically load the correct tableCel definition from the storyboard or XIB.

**Comment by evermeer** [comment]
Just let me know if you have any more questions.
