### ISSUE TITLE
Not Support the array optional

### ISSUE THREAD

**Issue by jtianling** [evermeer/EVReflection#9]
which mean, support code here:

``` swift
class User: EVObject {
    var id: Int = 0
    var name: String = ""
    var email: String?
    var company: Company?
    var friends: [User] = []
}

class Company: EVObject {
    var name: String = ""
    var address: String?
}
```

not support code here

``` swift
class User: EVObject {
    var id: Int = 0
    var name: String = ""
    var email: String?
    var company: Company?
    var friends: [User]? = []
}

class Company: EVObject {
    var name: String = ""
    var address: String?
}
```

**Comment by jtianling** [comment]
find a way to fix it , but don't know is it right:

`````` swift
  private class func dictArrayToObjectArray(type:String, array:[NSDictionary]) -> [NSObject] {
      // remove the Optional
      let optionalPrefix = "Swift.Optional<"
      var typeWithoutOptional: String = type

      if type.hasPrefix(optionalPrefix) {
        typeWithoutOptional = type.substringWithRange(Range<String.Index>(start: advance(type.startIndex, optionalPrefix.characters.count), end: advance(type.endIndex, -1)))
      }

        let subtype = (split(typeWithoutOptional.characters) {$0 == "<"}.map { String($0) } [1]).stringByReplacingOccurrencesOfString(">", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
```swift
``````

**Comment by evermeer** [comment]
Thanks! 

2 days ago I also pushed version 2.3.1 with a fix for the optional array problem to Github. I changed similar code in the valueForAny function. I now see that this solved the optional array problem. So you can use [Users]? But it still does not solve the optional array of optional objects like [Users?]? It looks like your solution will help solving this. I will do some more tests and push a new version to GitHub later toady.

It's great to see that you are also getting into the code!

**Comment by jtianling** [comment]
I used the swift-2.0 version code, maybe I miss the version 2.3.1. I'm glad that the problem is fixed. In most situation, we don't need [Users?]?, but need [Users]?.
The other big problem is that the custom defined enum type support, it's a common need.

By the way, more test is necessary, so that more people will choose to use it, and in a library so low-level and base, it need be strong without any crash, even the attribute can't find or type don't meet, it could set the value nil or default value, but not crash.

**Comment by evermeer** [comment]
Ah, you are right... I fixed it in the master and not the 2.0. I will do that later today. 
You are right that something like the [Users?]? probably will never be used but I still would like to prevent the code from crashing. I'm close... The only problem I now have is that Array<NSObject?> can not be cast to AnyObject

I will have a look at the enum support later...

**Comment by evermeer** [comment]
the fix is now pushed to master... I will now have a look at the 2.0 branch.

**Comment by jtianling** [comment]
Thanks a lot, the lib helps me a lot and I'm glad that you go on maintain it.

**Comment by jtianling** [comment]
Found another crash situation, when define the attribute as `var user: [Users]?`, but in json the data is `{
"user": { }
}`

**Comment by evermeer** [comment]
I upgraded to Xcode 7 beta 4. A lot has changed concerning reflection. This will take some time to fix.

**Comment by evermeer** [comment]
The swift 2 branch now also has the fix for the "user": { } } issue
If you find any other issues, then please let me know.

**Comment by evermeer** [comment]
The "user": { } } issue now also works in master

**Comment by jtianling** [comment]
bravo
