### ISSUE TITLE
propertyMapping()not parse Array, not take effect

### ISSUE THREAD

**Issue by Monkshae** [evermeer/EVReflection#91]
original data like this 

"provinces": [{
                "name": "\u5168\u90e8\u5730\u533a",
                "id": "worldwide"
            }, {
                "name": "\u5b89\u5fbd",
                "id": 262
            }, {
                "name": "\u5317\u4eac",
                "id": 264
            } ...]

if i override   the fuction like

```
override func propertyMapping() -> [(String?, String?)] {
    return [("provinces", "subTagArray")]
}
```

final ,the result is like     

subTagArray =         (
        );

the dataModel like 

class TagObject: BaseObject {

```
var subTagArray = [SimpleObject]()

override func propertyMapping() -> [(String?, String?)] {
    return [("provinces", "subTagArray")]
}
```

}

the data don't parse,I  confused.

**Comment by evermeer** [comment]
Hi,

You have the mapping in the wrong order. The first string is the propertyname in the object and the second string is the propertyname in the json (or dictionary). so you should return [("subTagArray", "provinces")]

I added your issue as a unit test. You can find it here:
https://github.com/evermeer/EVReflection/blob/348ea0cc0443032749ed7965740aed04abb210d8/EVReflection/EVReflectionTests/EVReflectionIssue91.swift#L28-L28

I did found one bug that has to do with propertyMapping and arrays. You should use version 2.33.5

**Comment by Monkshae** [comment]
OK , I notice the error . then  use version 2.33.5 ,  it works.  thanks.

but , I have a guess.  if I want  map like this

override func propertyMapping() -> [(String?, String?)] {
        return [("subTagArray", "provinces")]
    }

I can map  "provinces" to  "subTagArray" success. 
Now, I want  map  "subTags" to  "subTagArray，map  "provinces" to  "subTagArray，map  "subTagArray" to  "subTagArray.

subTags、 provinces、 values  is the json key and keys  corresponding to the value is the same type.  Every Key in one DataModel  appears only once. for exmple . if  subTags exists ，The remaining two Key（provinces，values）will not exist.

override func propertyMapping() -> [(String?, String?)] {
        return [("subTagArray", "subTags"),("subTagArray", "provinces"),("subTagArray", "values")]
    }

it does't work.

**Comment by Monkshae** [comment]
I find the propertyConverters. I wiil try

**Comment by evermeer** [comment]
With property mapping there is no support for multiple mappings for the same property. You could solve this issue by overriding the setValue forUndefinedKey like this:

```
override func setValue(value: AnyObject!, forUndefinedKey key: String) {
    guard let dict = value as? [NSDictionary] else { return }
    switch key {
    case "provinces", "values", "subTags":
        subTagArray = [SimpleObject](dictionaryArray: dict)
    default:
        NSLog("WARNING: setValue for key '\(key)' should be handled.")
    }
}
```

P.S. Initially you had to call the dictArrayToObjectArray function. I just pushed version 2.34.0 That adds an initializer to an array so that you can create an array directly from an array of dictionaries. So you have to get the latest version again 

I have updated the unit test with this new scenario. You can find it at:
https://github.com/evermeer/EVReflection/blob/f9aa07c469573a9da705816638515341144c56e3/EVReflection/EVReflectionTests/EVReflectionIssue91.swift#L28-L28

**Comment by Monkshae** [comment]
OK. thanks。

**Comment by Monkshae** [comment]
If you have time, you should update  wiki ~
