### ISSUE TITLE
Class won't be found if BUNDLE_NAME different than PRODUCT_MODULE_NAME

### ISSUE THREAD

**Issue by quentinfasquel** [evermeer/EVReflection#92]
As for now, setBundleIdentifier was the workaround to use EVReflection along with classes from another bundle. However, in Swift, class naming is not based on the bundle identifier but on a module name.

How I found out this issueL
For some reason, I today had to change my PRODUCT_NAME but I didn't want to go over all my storyboards to fix the references to classes by changing the module name, therefore I chose to change the product name but keep the PRODUCT_MODULE_NAME to my old one. This put me in a case where BUNDLE_NAME, based on PRODUCT_NAME was different than the module name.

(I haven't tested with the very last version yet)

**Comment by evermeer** [comment]
Indeed the bundle name and module name are often the same and I should use the module name. 
But I'm not sure if there is a good way to get the module name.
Currently I use: NSBundle.mainBundle().infoDictionary?["CFBundleName"]
I do see posts about using the CFBundleDisplayName instead. But I don't think thats right too. 
I'm not sure what would work best.I will try to investigate this

**Comment by evermeer** [comment]
I have now rewritten this code a little and it comes down to this function:

```
    private static func nameForBundle(bundle: NSBundle) -> String {
        // get the bundle name from what is set in the infoDictionary
        var appName = bundle.infoDictionary?[kCFBundleNameKey as String] as? String ?? ""
        if appName == "" {
            appName = bundle.bundleIdentifier ?? ""
        }
        appName = appName.characters.split(isSeparator: {$0 == "."}).map({ String($0) }).last ?? ""

        // Clean up special characters
        return appName.componentsSeparatedByCharactersInSet(illegalCharacterSet).joinWithSeparator("_")
    }
```

I have pushed this to GitHub (but did not made a new version for it)
I'm still not sure what the correct order should be.
I will now take the bundleName if it was set and if it was not set I take the bundle identifier.
Or should it be the other way around?

So the question is... should i use the kCFBundleIdentifierKey or the kCFBundleNameKey?

I think they both could be set to something that is not identical to the name that Swift needs for the framework identifier. So I guess the current logic is good enough. Or is there an alternative (better way) to get the correct name that Swift needs?

**Comment by evermeer** [comment]
Assuming the current solution is the best. Any comment about this is welcome.
