### ISSUE TITLE
Warning for Structs

### ISSUE THREAD

**Issue by christophercotton** [evermeer/EVReflection#94]
Right now there is a warning for Structs:

``` swift
        if type == "Struct" {
            (original as? EVObject)?.addStatusMessage(.InvalidClass, message: "Structs should be handled with 'setvalue forUndefinedKey'\ndict:\(dict)")
            print("WARNING: Structs should be handled with 'setvalue forUndefinedKey'\ndict:\(dict)")
        } else {
```

Except, it gives that warning before attempting to do the `setValue forUndefinedKey`. So even though I correctly implement the undefined key, I still get the warning. I think that it should just remove the warning, and only give the next error there if the type != Struct. Or is there another way to not get the warning?

**Comment by evermeer** [comment]
I think you have a valid point. I will do some test this evening.

**Comment by evermeer** [comment]
I just pushed version 2.38.1 where the warning for structs is removed.
