### ISSUE TITLE
Swift 3.0 Integration?

### ISSUE THREAD

**Issue by nzayatz14** [evermeer/EVReflection#95]
I'm sure this is on the agenda, but I don't want to update to Swift 3.0 until I'm sure you guys (and the rest of my pods) have Swift 3.0 support

**Comment by evermeer** [comment]
Indeed it's on the agenda. Now that the official XCode beta is out I will probably start creating an Swift 3.0 compatible version soon.

**Comment by tdouglas1313** [comment]
Is there an update on this?

**Comment by evermeer** [comment]
There is now a Swift 2.3 branch which is OK
There is also a Swift 3 branch but there are still 11 tests failing because of type changes which needs to be fixed one by one.
Tested with XCode 8 beta 3

**Comment by evermeer** [comment]
Now 7 tests fail. They all fail because type Date has changed. I will try to fix that later today.

**Comment by evermeer** [comment]
Almost there... Only 2 tests still fail (UUID datatype related). So If you don't use UUID's this version could be used...

**Comment by evermeer** [comment]
And now all unit tests pass... Please let me know if you find any issues.

**Comment by just-doit** [comment]
I get an error at line 700 in EVRefelection.swift:
EVReflection.swift:700:36: Boolean condition requires 'where' to separate it from variable binding.
Replacing the "," with "where" fixes the compiler error but I'm not sure if this has the same meaning. (I'm new to swift)

**Comment by evermeer** [comment]
@just-doit Did you use the Swift3 branch with Xcode 8 beta 3? I think that replace of where with , was introduced in beta 3

**Comment by just-doit** [comment]
Yes, I did. Downloaded it an hour ago or so.

**Comment by just-doit** [comment]
Oh, sorry. Did read your question completely. I'm using Swift3 branch, but with Xcode 8 beta 2.
