### ISSUE TITLE
Could not create instance for type

### ISSUE THREAD

**Issue by OliverZiegler** [evermeer/EVReflection#96]
I'm not able to parse my not really complex json to Swift Objects and always get an **Could not create instance for type B**
I'm not sure if I'm missing something or if this is a bug.

Help would be appreciated!

So my setting is as follows:

```
class SuperA: EVObject { }

class A1: SuperA {
  var b : [B] = []
}

class A2: SuperA {
  var i : [Int] = []
}

class B: EVObject {
  var id: Int = 0
  var text: String = ""
  var date: NSDate = NSDate()
}
```

My json contains properly escaped html in B.text.

Trying to parse only B is working. Parsing A2 with an Int-Array in "i" also works. But as soon as I try to parse A1 I get the Error and A.b is an empty array.
I'm kinda getting crazy over this.

Thanks for any help!

**Comment by xeaone** [comment]
I am having the same issue.

I found that it will parse the data as an `Array<NSDictionary>`. But I to would like to know if you are able to use `Array<CustomClass>`.

Thanks guys.

**Comment by OliverZiegler** [comment]
So I tried this further and further and I'm not able to parse things like that.
As the Readme states this should be handled automatically like here

```
class User: EVObject {
  var id: Int = 0
  var name: String = ""
  var friends: [User]? = []
}
```

I also tried to use custom property converters, but the array given is always empty cause property conversion is handled after parsing (?? seems like).

Parsing native Swift dictionaries like `[String: CustomClass]` via `setValue(value: AnyObject!, forUndefinedKey key: String)` works like a charm.
And parsing to native Swift type arrays like `[String]` or `[Int]` also works...

@AlexanderElias Do you have any smooth workaround with `Array<NSDictionary>` to get your object as `CustomClass`?

**Comment by xeaone** [comment]
Not smooth yet but I was trying the following and it seems to work. The IIF then parses `b` into our custom class. 

``` Swift
class a: EVObject  {

    class b: EVObject {
        var str: String = ""
    }

    var b: Array<NSDictionary> = []

    var bArray: Array<b> {

        var childs: Array<b> = []

        self.b.forEach({ (dic) -> () in
            childs.append(b(dictionary: dic))
        })

        return childs
    }
}
```

It allows use to use `a.bArray` as we would have used `a.b`.
What do you think?

**Comment by evermeer** [comment]
Great to see the interaction between users  😀

Could you provide me with the json so that I can see where it goes wrong? 
Both an array of dictionaries or an array of custom objects should work.

One comment to the code of @AlexanderElias : Nesting classes should work, but is not extensively testen. I cannot guarantee that there are no side effects.

**Comment by OliverZiegler** [comment]
I [forked](https://github.com/OliverZiegler/EVReflection/tree/issue96) this repo and added a [TestCase](https://github.com/OliverZiegler/EVReflection/blob/issue96/EVReflection/EVReflectionTests/EVReflectionIssue96.swift) for this issue.

 When I run this test it fails creating the array from json (this worked in my setting).
Commenting this out and trying to instantiate the surrounding object tells me **The class 'PayloadNews' is not key value coding-compliant for the key 'news'**.

**Comment by evermeer** [comment]
Thanks for the TestCase! That really helps.
Fixing this was easy. You only have to add EVObject as the base class of your News object.
I have added a merge request for your fork

**Comment by evermeer** [comment]
I was able to change this to a compile time error. When you have this you will get this:
<img width="564" alt="screen shot 2016-06-16 at 9 27 55 pm" src="https://cloud.githubusercontent.com/assets/130834/16131575/25cd47ae-340f-11e6-8a66-c5757c78adca.png">
This is now pushed to GitHub and CocoaPods as version 2.36.0

Thanks again for reporting this.

**Comment by OliverZiegler** [comment]
I will try the new version and see if this was the problem. Thanks for the fast solution!
