### ISSUE TITLE
Getting back bad Json

### ISSUE THREAD

**Issue by mattjaffa** [evermeer/EVReflection#99]
Here is my object and when I call toDictionary on an instance, I get weird dictionary properties in my json when I call toJson:

```
import Foundation
import EVReflection

public class Message : EVObject, EVDictionaryConvertable {
    var body: String? = ""
    var email: String? = ""
    var subject: String? = "Message"
    var sysId: String? = "7b68dea1-c8b1-46b5-9556-21bf013635c7"
    var user: String? = ""
    var threadId: String? = ""
    var users: [String:String] = [String:String]()

    public func convertDictionary(key: String, dict: Any) -> NSDictionary {
        assert(key == "users", "convertArray for key \(key) should be handled.")

        let returnDict = NSMutableDictionary()
        for (key, value) in dict as? NSDictionary ?? NSDictionary() {
            returnDict[key as? String ?? ""] = value
        }
        return returnDict
    }
}
```

**Comment by evermeer** [comment]
I just found out that there is a difference when reflecting an object that has a dictionary that contains simple types like strings (like there is in your case) I just pushed a fix for that to GitHub and Cocoapods as version 2.37.0

You can found your issue as a unit test at:
https://github.com/evermeer/EVReflection/blob/master/EVReflection/EVReflectionTests/EVReflectionIssue99.swift#L62

**Comment by chriscohoat** [comment]
I'm using 2.37.0 with a simple string dictionary and I'm also getting some weird properties:

```
import EVReflection
class TestObject: EVObject {
    var params: [String: String]?
}
```

and

```
let paramsRequest = TestObject()
paramsRequest.params = [
     "foo": "bar",
     "baz": "buzz"
]
print(paramsRequest.toJsonString())
```

produces:

```
ERROR: valueForAny unkown type _NativeDictionaryStorageImpl<String, String> for value: Swift._NativeDictionaryStorageImpl<Swift.String, Swift.String>.
ERROR: valueForAny unkown type _NativeDictionaryStorageImpl<String, String> for value: Swift._NativeDictionaryStorageImpl<Swift.String, Swift.String>.
ERROR: valueForAny unkown type _NativeDictionaryStorageImpl<String, String> for value: Swift._NativeDictionaryStorageImpl<Swift.String, Swift.String>.
{
  "params" : {
    "_heapBufferBridged_DoNotUse" : null,
    "nativeStorage" : {
      "keys" : {
        "pointerValue" : 140524782787672
      },
      "buffer" : null,
      "initializedEntries" : {
        "values" : {
          "pointerValue" : 140524782787576
        },
        "bitCount" : 4
      },
      "values" : {
        "pointerValue" : 140524782787768
      }
    }
  }
}
```

Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)

**Comment by evermeer** [comment]
@chriscohoat This is because a Swift Dictionary is a special kind of struct that will return extra keys when  doing a Mirror on it. To solve this I have added the EVDictionaryConvertable protocol which will handle the conversion between a Swift Dictionary and a NSDictionary. 

Originally this function was meant to handle the case where you would have a dictionary of EVObject derived objects. I think I will be able to change EVReflection so that you don't need the EVDictionaryConvertable protocol for when you use a Dictionary of Strings.  I will have a look at that.

I have added your sample to the unit test. So for now you can see how to implement the EVDictionaryConvertable here:
https://github.com/evermeer/EVReflection/blob/3e0ee09c9ded9d2af583a6a3d85307968a87ef4f/EVReflection/EVReflectionTests/EVReflectionIssue99.swift#L86-L86

**Comment by evermeer** [comment]
I now have implemented a standard dictionary conversion that is in EVObject. You don't need to implement EVDictionaryConvertable anymore. If you want a custom conversion, then you can override the method.

**Comment by nshutov** [comment]
Set< String > produce _heapBufferBridged_DoNotUse too
To fix it i change Set< String > to  [String]
v 2.40.0

**Comment by evermeer** [comment]
@nshutov Do you mean that you have an object with a property of `Set<String>` and you are asked to convert it to `[String]`?

I could indeed see the problem and created a new issue for this: https://github.com/evermeer/EVReflection/issues/110
